CREATE OR REPLACE PACKAGE GA_COMMON_PKG

AS

TYPE REF_CURSOR IS REF CURSOR;

DATE_FMT_YYYYMMDD VARCHAR2(10)        :=  'YYYYMMDD';

DATE_FMT_SLASH_MMDDYYYY VARCHAR2(10)  :=  'MM/DD/YYYY';

DATE_FMT_DEFAULT  VARCHAR2(10)        :=  DATE_FMT_YYYYMMDD;

END GA_COMMON_PKG;
/