CREATE TABLE AS_ITM (
ID_ITM               VARCHAR2(128) NOT NULL,
ID_LN_PRC            VARCHAR2(128) NULL,
ID_STRC_MR           VARCHAR2(128) NULL,
LU_HRC_MR_LV         VARCHAR2(40) NULL,
FL_ITM_DSC           DECIMAL(1) NULL,
LU_SBSN              VARCHAR2(20) NULL,
LU_SN                VARCHAR2(20) NULL,
FY                   CHAR(4) NULL,
FL_ADT_ITM_PRC       DECIMAL(1) NULL,
NM_BRN               VARCHAR2(40) NULL,
FL_AZN_FR_SLS        DECIMAL(1) NULL,
LU_ITM_USG           VARCHAR2(20) NULL,
NM_ITM               VARCHAR2(40) NULL,
DE_ITM               VARCHAR2(255) NULL,
TY_ITM               VARCHAR2(40) NULL,
LU_KT_ST             VARCHAR2(20) NULL,
FL_ITM_SBST_IDN      DECIMAL(1) NULL,
LU_CLN_ORD           VARCHAR2(20) NULL,
ID_DPT_POS           VARCHAR2(128) NULL,
CD_CLB_MKTG          VARCHAR(50) NULL,
ID_CLSS              VARCHAR2(128) NULL,
ID_SBCL              VARCHAR2(128) NULL,
LU_EXM_TX            VARCHAR2(20) NULL,
ID_PRT_ITM           VARCHAR2(128) NULL
);

CREATE TABLE AS_ITM_BLK (
ID_ITM               VARCHAR2(128) NOT NULL,
PE_WST_BLK_SLS       DECIMAL(5,2) DEFAULT 0 NULL,
TY_WST_BLK_SLS       CHAR(2) NULL
);

CREATE TABLE AS_ITM_RTL_STR (
ID_STR_RT            VARCHAR2(128) NULL,
ID_ITM               VARCHAR2(128) NOT NULL,
SC_ITM_SLS           VARCHAR2(20) NULL,
ID_GP_TX             VARCHAR2(128) NULL,
DC_ITM_SLS           DATE NULL,
SC_ITM               VARCHAR2(20) NULL,
RP_PR_SLS            VARCHAR2(75) DEFAULT 0 NULL,
FL_MKD_ORGL_PRC_PR   DECIMAL(1) NULL,
QU_MKD_PR_PRC_PR     DECIMAL(7,0) DEFAULT 0 NULL,
FL_STK_UPDT_ON_HD    DECIMAL(1) NULL,
DC_PRC_EF_PRN_RT     DATE NULL,
RP_SLS_CRT           VARCHAR2(75) DEFAULT 0 NULL,
TY_PRC_RT            VARCHAR2(20) NULL,
FL_PRC_RT_PNT_ALW    DECIMAL(1) NULL,
DC_PRC_SLS_EF_CRT    DATE NULL,
DC_PRC_SLS_EP_CRT    DATE NULL,
RP_PRC_MF_RCM_RT     VARCHAR2(75) DEFAULT 0 NULL,
DC_PRC_MF_RCM_RT     DATE NULL,
RP_PRC_CMPR_AT_SLS   VARCHAR2(75) DEFAULT 0 NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
CD_VAT               VARCHAR2(128) NULL,
VAT_RATE             DECIMAL(7,4) DEFAULT 0 NULL,
FL_VAT_CLS           DECIMAL(1) NULL
);

CREATE TABLE AS_ITM_STK (
ID_ITM               VARCHAR2(128) NOT NULL,
TY_ITM_STK           CHAR(2) NULL,
LU_CNT_SLS_WT_UN     CHAR(2) NULL,
TY_PKP_CT_STK_ITM    CHAR(2) NULL,
FA_PRC_UN_STK_ITM    DECIMAL(9,2) DEFAULT 0 NULL,
DC_AVLB_FR_SLS       DATE NULL,
TY_ENV_STK_ITM       CHAR(2) NULL,
TY_SCTY_RQ           CHAR(2) NULL,
TY_MTR_HZ_STK_ITM    CHAR(2) NULL,
LU_MTH_INV_ACNT      CHAR(2) NULL,
CP_UN_SL_LS_RCV_BS   DECIMAL(10,5) DEFAULT 0 NULL,
CP_CST_NT_LS_RCV     DECIMAL(10,5) DEFAULT 0 NULL,
CP_UN_SL_LND         DECIMAL(10,5) DEFAULT 0 NULL,
DC_CST_EST_LS_RCV    DATE NULL,
FL_SHRK_SH_ITM       DECIMAL(1) NULL,
FL_SWL_SH_ITM        DECIMAL(1) NULL,
LU_UOM_OLD           CHAR(2) NULL,
LU_UOM               CHAR(2) NOT NULL
);

CREATE TABLE AS_TL (
ID_RPSTY_TND         VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_OPR               VARCHAR2(128) NULL,
SC_TL                VARCHAR2(20) NULL,
TS_STS_TL            DATE NULL,
CP_BLNC_DFLT_OPN     VARCHAR2(75) DEFAULT 0 NULL,
LU_TND_MXM_ALW       VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE AS_TR (
ID_TR_BLK_ITM        VARCHAR2(128) NOT NULL,
QW_WT_TR             DECIMAL(9,2) DEFAULT 0 NULL,
ID_ITM               VARCHAR2(128) NOT NULL,
DE_WT_TR             VARCHAR2(255) NULL,
PCT_PRPT             DECIMAL(5,2) DEFAULT 0 NULL,
LU_UOM               CHAR(2) NULL
);

CREATE TABLE CO_ACS_PSWD (
ID_OPR               VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
PS_ACS_OPR           VARCHAR2(20) DEFAULT '' NULL,
PS_SCND_ACS_OPR      VARCHAR2(20) DEFAULT '' NULL
);

CREATE TABLE CO_ASCTN_RLTD_ITM (
ID_ITM               VARCHAR2(128) NOT NULL,
ID_ITM_RLTD          VARCHAR2(128) NOT NULL,
NM_ASCTN_RLTD_ITM    VARCHAR2(40) NULL,
NA_ASCTN_RLTD_ITM    VARCHAR2(1024) NULL
);

CREATE TABLE CO_CFG (
ID_CFG               VARCHAR2(128) NOT NULL
);

CREATE TABLE CO_CFG_BTTN (
ID_BTTN              VARCHAR2(128) NOT NULL,
DE_BTTN              VARCHAR2(255) NULL,
DE_CFG               VARCHAR2(255) NULL,
AM_LYR               DECIMAL(30) NULL,
AM_SQNC              DECIMAL(30) NULL,
TY_BTTN              CHAR(4) NULL,
DT_EF                DATE NULL,
CD_CLR               CHAR(4) NULL,
CO_BKGD              CHAR(4) NULL,
NM_DPT               VARCHAR(100) NULL,
ME_TXT               VARCHAR(100) NULL,
ID_BTTN_PRNT         VARCHAR2(128) NULL,
CD_STS               CHAR(4) NULL,
ID_CFG               VARCHAR2(128) NOT NULL
);

CREATE TABLE CO_CFG_CPN (
ID_CPN               VARCHAR2(128) NOT NULL,
DE_CPN               VARCHAR2(255) NULL,
CD_CNY               VARCHAR2(20) NULL,
MO_MX_DSC_AMT        VARCHAR2(75) DEFAULT 0 NULL,
MO_AMT               VARCHAR2(75) DEFAULT 0 NULL,
FL_PCT               DECIMAL(1) NULL,
ID_PFT_CTR           VARCHAR2(128) NULL,
CD_TX_CLS            CHAR(4) NULL,
CD_XPT               CHAR(4) NULL,
DT_EF                DATE NULL,
DT_EX                DATE NULL,
FL_PRMPT             DECIMAL(1) NULL,
FL_DPLY              DECIMAL(1) NULL,
CD_STS               CHAR(4) NULL,
ID_CFG               VARCHAR2(128) NOT NULL
);

CREATE TABLE CO_CFG_MNY_ORD (
ID_MNY_ORD           VARCHAR2(128) NOT NULL,
DE_MNY_ORD           VARCHAR2(255) NULL,
CD_CNY               VARCHAR2(20) NULL,
MO_FE                VARCHAR2(75) DEFAULT 0 NULL,
MO_MX_FC_VL          VARCHAR2(75) DEFAULT 0 NULL,
MO_MX_SL_AMT         VARCHAR2(75) DEFAULT 0 NULL,
CD_TX_CLS            CHAR(4) NULL,
FL_CSH               DECIMAL(1) NULL,
FL_SRZ               DECIMAL(1) NULL,
QV_PCK_SZ            DECIMAL(9,2) DEFAULT 0 NULL,
FL_RFD_FE            DECIMAL(1) NULL,
DT_EX                DATE NULL,
DT_EF                DATE NULL,
CD_STS               CHAR(4) NULL,
ID_CFG               VARCHAR2(128) NOT NULL
);

CREATE TABLE CO_CFG_PDT_RST (
ID_PDT_RST           VARCHAR2(128) NOT NULL,
DE_PDT_RST           VARCHAR2(255) NULL,
TY_PDT_RST           CHAR(4) NULL,
DT_EF                DATE NULL,
CD_CNY               VARCHAR2(20) NULL,
MO_AMT               VARCHAR2(75) DEFAULT 0 NULL,
DT_AG_MNM            DATE NULL,
ID_CFG               VARCHAR2(128) NOT NULL
);

CREATE TABLE CO_CFG_PY_IN_OT (
ID_PY_IN_OT          VARCHAR2(128) NOT NULL,
DE_PY_IN_OT          VARCHAR2(255) NULL,
CD_TYP               CHAR(4) NULL,
ID_PFT_CTR           VARCHAR2(128) NULL,
CD_XPT               CHAR(4) NULL,
CD_TX_CHRT           CHAR(4) NULL,
ID_INVC_LNK          VARCHAR2(128) NULL,
FL_DPLY              DECIMAL(1) NULL,
DT_EF                DATE NULL,
CD_STS               CHAR(4) NULL,
ID_CFG               VARCHAR2(128) NOT NULL
);

CREATE TABLE CO_CFG_SPR_PY_TYP (
ID_SPR_PY_TYP        VARCHAR2(128) NOT NULL,
ID_SPR               VARCHAR2(128) NOT NULL,
CD_PY_TYP            CHAR(4) NULL,
DT_EF                DATE NULL,
CD_STS               CHAR(4) NULL,
ID_CFG               VARCHAR2(128) NOT NULL
);

CREATE TABLE CO_CFG_TND_TYP (
ID_TND_TYP           VARCHAR2(128) NOT NULL,
DE_TND_TYP           VARCHAR2(255) NULL,
ID_GRP               VARCHAR2(128) NULL,
DT_EF                DATE NULL,
CD_CNY               VARCHAR2(20) NULL,
MO_PST_AMT           VARCHAR2(75) DEFAULT 0 NULL,
MO_AUTH_MNM          VARCHAR2(75) DEFAULT 0 NULL,
FL_OPN_DRW           DECIMAL(1) NULL,
FL_XCT_CHN           DECIMAL(1) NULL,
FL_ACCM_CSH          DECIMAL(1) NULL,
FL_NXT_DLLR          DECIMAL(1) NULL,
FL_DS_BK             DECIMAL(1) NULL,
FL_DS_OVRD           DECIMAL(1) NULL,
FL_AUTO_DS           DECIMAL(1) NULL,
FL_PY_IN_DS          DECIMAL(1) NULL,
FL_ASK_INVC          DECIMAL(1) NULL,
FL_IMPT              DECIMAL(1) NULL,
CD_TYP_TND_IMPT      CHAR(4) NULL,
FL_SHW_IN_BRDN       DECIMAL(1) NULL,
FL_DPLY              DECIMAL(1) NULL,
FL_DSCP_DPLY         DECIMAL(1) NULL,
CD_TYP_PRO           CHAR(4) NULL,
CD_XPT               CHAR(4) NULL,
ID_PFT_CTR           VARCHAR2(128) NULL,
CD_TYP_PH_AZN        CHAR(4) NULL,
CD_STS               CHAR(4) NULL,
ID_CFG               VARCHAR2(128) NOT NULL
);

CREATE TABLE CO_CLS_GF_CF (
TY_GF_CF             VARCHAR2(40) NOT NULL,
ID_STR_RT            VARCHAR2(128) NULL,
ID_ACNT_LDG          VARCHAR2(128) NULL,
DE_TYP_GF_CF         VARCHAR2(255) NULL,
NM_AF_BSN_GF_CF      VARCHAR2(40) NULL,
QU_DY_RDM_PRD        DECIMAL(3,0) DEFAULT 0 NULL,
ID_FRM_GF_CF         VARCHAR2(128) NULL,
DP_BLNC_UNSP_GF_CF   VARCHAR2(40) NULL
);

CREATE TABLE CO_CLS_TND (
LU_CLS_TND           VARCHAR2(40) NOT NULL,
DE_CLS_TND           VARCHAR2(255) NULL
);

CREATE TABLE CO_CTAF (
ID_CT                VARCHAR2(128) NOT NULL,
ID_GP_ID             VARCHAR2(128) NOT NULL,
FL_IDN_CTAF_VR_RQ    DECIMAL(1) NULL
);

CREATE TABLE CO_EV (
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_EV                VARCHAR2(128) NOT NULL,
DC_DY_BSN_SS         DATE NULL,
DC_DY_BSN_SE         DATE NULL,
DC_DY_BSN_AS         DATE NULL,
DC_DY_BSN_AE         DATE NULL,
TY_EV                CHAR(4) NULL,
DE_EV                VARCHAR2(255) NULL,
NM_EV                VARCHAR2(40) NULL,
SC_EV                CHAR(2) NULL,
CC_EV                CHAR(2) NULL,
NM_EV_OWNR           VARCHAR2(40) NULL,
TS_EV_PL_EF          DATE NULL,
TS_EV_PL_EP          DATE NULL,
TS_EV_ACT_EF         DATE NULL,
TS_EV_ACT_EP         DATE NULL
);

CREATE TABLE CO_EV_MNT (
ID_EV                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_EM                VARCHAR2(128) NULL,
ID_CMP               VARCHAR2(128) NULL,
NM_EV_MNT            VARCHAR2(40) NULL,
DE_EV_MNT            VARCHAR2(255) NULL,
RC_EV_MNT            CHAR(4) NULL,
TS_EV_MNT_EF         DATE NULL,
TS_EV_MNT_EP         DATE NULL,
TY_EV_MNT            CHAR(2) NULL,
SC_EV_MNT            CHAR(2) NULL,
TS_EV_MNT_APLY       DATE NULL,
TS_EV_MNT_CRT        DATE NULL,
TY_EV_MNT_ORG        CHAR(4) NULL
);

CREATE TABLE CO_ITM_CFG (
ID_ITM_CFG           VARCHAR2(128) NOT NULL,
CD_STS               CHAR(4) NULL,
ID_BTTN              VARCHAR2(128) NULL,
ID_STR_CFG           VARCHAR2(128) NULL
);

CREATE TABLE CO_MNT_ITM (
ID_EV                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
LU_EV_ITM_MNT        CHAR(2) NULL,
ID_ITM               VARCHAR2(128) NULL
);

CREATE TABLE CO_PLN_EM_CMN (
ID_PLN_EM_CMN        VARCHAR2(20) NOT NULL,
ID_STR_RT            VARCHAR2(128) NULL,
ID_ACNT_LDG          VARCHAR2(128) NULL,
DE_PLN_EM_CMN        VARCHAR2(255) NULL
);

CREATE TABLE CO_PRM (
ID_PRM               VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NULL,
ID_ACNT_LDG          VARCHAR2(128) NULL,
DC_PRM_EF            VARCHAR(96) NULL,
DC_PRM_EP            VARCHAR(96) NULL,
CD_MLP_EL            CHAR(2) NULL,
TY_CNCRN             CHAR(2) NULL,
TY_UP_SELL           CHAR(2) NULL,
NM_PRM_OPR           VARCHAR2(40) NULL,
NM_PRM_CT            VARCHAR2(40) NULL,
NM_PRM_PRT           VARCHAR2(40) NULL,
DP_ACNT              CHAR(4) NULL
);

CREATE TABLE CO_PST (
ID_PST               VARCHAR2(128) NOT NULL,
CD_JOB               VARCHAR2(60) NULL,
DE_PST               VARCHAR2(1024) NULL,
NM_PST_TTL           VARCHAR2(40) NULL,
CD_PYRL_TYP          VARCHAR2(60) NULL,
FL_PST_SHR           DECIMAL(1) NULL,
FL_CMN               DECIMAL(1) NULL,
CD_ACS_LV            VARCHAR2(60) NULL
);

CREATE TABLE CO_STR_CFG (
ID_STR_CFG           VARCHAR2(128) NOT NULL,
CD_STS               CHAR(4) NULL,
ID_CFG               VARCHAR2(128) NULL
);

CREATE TABLE CO_TH_MPR_UN (
ID_LV_TH             VARCHAR2(128) NOT NULL,
ID_ITM               VARCHAR2(128) NULL,
QU_CNT_UN            DECIMAL(9,2) DEFAULT 0 NULL,
MO_VL_TH             DECIMAL(14,3) DEFAULT 0 NULL,
MO_RDN_TH_PR         DECIMAL(14,3) DEFAULT 0 NULL,
PE_RDN_TH_PR         DECIMAL(5,2) DEFAULT 0 NULL,
QU_CNT_UN_OLD        DECIMAL(9,2) DEFAULT 0 NULL,
MO_VL_TH_OLD         DECIMAL(14,3) DEFAULT 0 NULL,
LU_UOM_OLD           CHAR(2) NULL,
LU_UOM               CHAR(2) NULL
);

CREATE TABLE CO_TYP_TRN (
TY_TRN               VARCHAR2(60) NOT NULL,
ID_RS                VARCHAR2(128) NULL
);

CREATE TABLE CO_UOM (
LU_UOM               CHAR(2) NOT NULL,
TY_UOM               CHAR(2) NULL,
FL_UOM_ENG_MC        BOOLEAN NULL,
NM_UOM               VARCHAR2(40) NULL,
DE_UOM               VARCHAR2(255) NULL
);

CREATE TABLE DO_CF_GF (
ID_STR_ISSG          VARCHAR2(128) NULL,
ID_NMB_SRZ_GF_CF     VARCHAR2(40) NOT NULL,
TY_GF_CF             VARCHAR2(40) NOT NULL,
TS_ISS_GF_CF         DATE NULL,
DC_EP_GF_CF          DATE NULL,
MO_VL_FC_GF_CF       VARCHAR2(75) DEFAULT 0 NULL,
MO_BLNC_UNSP_GF_CF   VARCHAR2(75) DEFAULT 0 NULL,
TY_ISS_GF_CF         VARCHAR2(20) NULL,
NM_DNR_GF_CF         VARCHAR2(40) NULL,
AD_DNR_GF_CF         VARCHAR2(40) NULL,
CI_DNR_GF_CF         VARCHAR2(30) NULL,
ST_DNR_GF_CF         CHAR(2) NULL,
CC_DNR_GF_CF         VARCHAR2(10) NULL,
PC_DNR_GF_CF         VARCHAR2(15) DEFAULT '' NULL,
TA_DNR_GF_CF         VARCHAR2(10) NULL,
TL_DNR_GF_CF         VARCHAR2(15) NULL,
FN_DNR_GF_CF         VARCHAR2(40) NULL,
DELETED              DECIMAL(1) NULL,
GIFT_CONTROL         VARCHAR(200) NULL,
AUDIT_NOTE           VARCHAR(200) NULL
);

CREATE TABLE ID_DPT_PS (
ID_DPT_POS           VARCHAR2(128) NOT NULL,
NM_DPT_POS           VARCHAR2(40) NULL,
ID_DPT_POS_PRNT      VARCHAR2(128) NULL
);

CREATE TABLE ID_IDN_PS (
ID_ITM_POS           CHAR(14) NOT NULL,
ID_ITM               VARCHAR2(128) NOT NULL,
LU_GP_TND_RST        VARCHAR2(20) NULL,
FL_PNT_FQ_SHPR_EL    DECIMAL(1) NULL,
ID_MF                VARCHAR2(128) NULL,
FL_DSC_AF_DSC_ALW    DECIMAL(1) NULL,
FL_DSC_MRK_BSK_ALW   DECIMAL(1) NULL,
FC_FMY_MF            CHAR(3) NULL,
FL_DSC_CT_ACNT_ALW   DECIMAL(1) NULL,
ID_ITM_MF_UPC        CHAR(14) NULL,
ID_AGNT_RTN          VARCHAR2(128) NULL,
DE_ITM_POS           VARCHAR2(255) NULL,
FL_DSC_EM_ALW        DECIMAL(1) NULL,
FL_CPN_ALW_MULTY     DECIMAL(1) NULL,
LU_VL_CPN            DECIMAL(2,2) NULL,
DT_END_PS_CPN_OFR    VARCHAR2(20) NULL,
FL_FD_STP_ALW        DECIMAL(1) NULL,
QU_UN_BLK_MNM        DECIMAL(3,0) DEFAULT 0 NULL,
FL_CPN_ELTNC         DECIMAL(1) NULL,
QU_UN_BLK_MXM        DECIMAL(3,0) DEFAULT 0 NULL,
FL_CPN_RST           DECIMAL(1) NULL,
CD_ENR_PRC_RQ        VARCHAR2(20) NULL,
FL_ENR_WT_RQ         DECIMAL(1) NULL,
FL_KY_PRH_QTY        DECIMAL(1) NULL,
FL_RTN_PRH           DECIMAL(1) NULL,
FL_ITM_GWY           DECIMAL(1) NULL,
FL_ITM_WIC           DECIMAL(1) NULL,
FL_PRC_VS_VR         DECIMAL(1) NULL,
FL_KY_PRH_RPT        DECIMAL(1) NULL,
QU_PNT_FQ_SHPR       DECIMAL(9,2) DEFAULT 0 NULL,
RP_SLS_POS_CRT       VARCHAR2(75) DEFAULT 0 NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
FL_SL_STP            DECIMAL(1) NULL,
FL_RFND              DECIMAL(1) NULL,
FL_BKOR              DECIMAL(1) NULL
);

CREATE TABLE LE_ACNT_STR_FN (
ID_ACNT_LDG          VARCHAR2(128) NOT NULL,
TY_ACNT_FN_LDG       VARCHAR2(20) NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
DE_ACNT_FN_LDG       VARCHAR2(255) NULL,
MO_BLNC_BGN_FN_LDG   VARCHAR2(75) DEFAULT 0 NULL,
MO_BLNC_CRT_FN_LDG   VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE LE_HST_ITM_SLS_PRC (
AI_PRC_RT            SMALLINT NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_EV                VARCHAR2(128) NULL,
TS_PR_EF             DATE NULL,
TS_PR_END            DATE NULL,
RP_UN_ITM_HST_SL     VARCHAR2(75) DEFAULT 0 NULL,
RP_UN_ITM_SLS_PRC_OLD VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE LE_PRC_SPL_CT_TYP (
ID_GP_ID             VARCHAR2(128) NOT NULL,
RP_SLS_CRT           VARCHAR2(75) DEFAULT 0 NULL,
FL_PRC_SLS_SPL_DSC   DECIMAL(1) NULL,
ID_ITM               VARCHAR2(128) NOT NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL
);

CREATE TABLE LO_ADS (
ID_ADS               VARCHAR2(128) NOT NULL
);

CREATE TABLE LO_ADS_LCN_PHY (
CD_LCN_PHY           VARCHAR2(60) NOT NULL,
TY_CRDN              VARCHAR2(20) NOT NULL,
ID_ADS               VARCHAR2(128) NOT NULL
);

CREATE TABLE LO_ADS_NSTD (
ID_ADS               VARCHAR2(128) NOT NULL,
A1_ADS               VARCHAR2(40) NULL,
A2_ADS               VARCHAR2(40) NULL,
NM_UN                VARCHAR2(40) NULL,
TE_NM                VARCHAR2(40) NULL,
CO_NM                VARCHAR2(40) NULL,
PC_NM                VARCHAR2(15) DEFAULT '' NULL
);

CREATE TABLE LO_ADS_PRTY (
ID_ADS               VARCHAR2(128) NOT NULL,
ID_PRTY              VARCHAR2(128) NOT NULL,
SC_PRTY_ADS          VARCHAR2(20) NULL,
TY_RO_PRTY           VARCHAR2(60) NOT NULL,
DC_EF                DATE NULL,
DC_EP                DATE NULL
);

CREATE TABLE LO_CRDN_TYP (
TY_CRDN              VARCHAR2(20) NOT NULL,
DE_CRDN_TYP          VARCHAR2(1024) NULL
);

CREATE TABLE LO_EML_ADS (
EM_ADS               VARCHAR2(64) NOT NULL,
ID_PRTY              VARCHAR2(128) NOT NULL
);

CREATE TABLE LO_LCN_PHY (
CD_LCN_PHY           VARCHAR2(60) NOT NULL,
TY_CRDN              VARCHAR2(20) NOT NULL
);

CREATE TABLE LO_PH (
ID_PRTY              VARCHAR2(128) NOT NULL,
ID_PH_TYP            VARCHAR2(128) NOT NULL,
CC_PH                VARCHAR2(10) NULL,
TA_PH                VARCHAR2(10) NULL,
TL_PH                VARCHAR2(15) NULL,
PH_EXTN              VARCHAR2(10) NULL
);

CREATE TABLE LO_PH_TYP (
ID_PH_TYP            VARCHAR2(128) NOT NULL,
DE_PH_TYP            VARCHAR2(1024) NULL
);

CREATE TABLE MA_CRT_ITM (
ID_EV                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
TY_NO                VARCHAR2(20) NULL,
ID_FRMT              VARCHAR2(20) NULL,
UN_PRFX              DECIMAL(3) NULL
);

CREATE TABLE MA_DLT_ITM (
ID_EV                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL
);

CREATE TABLE MA_ITM_PRN_PRC_ITM (
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_EV                VARCHAR2(128) NOT NULL
);

CREATE TABLE MA_ITM_TMP_PRC_CHN (
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_EV                VARCHAR2(128) NOT NULL
);

CREATE TABLE MA_PRC_ITM (
ID_EV                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
TY_PRC_MNT           CHAR(2) NULL
);

CREATE TABLE MA_UPDT_ITM_DSCR (
ID_EV                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL
);

CREATE TABLE PA_CT (
ID_CT                VARCHAR2(128) NOT NULL,
TY_RO_PRTY           VARCHAR2(60) NOT NULL,
TY_CT_LFC            VARCHAR2(40) NULL,
MO_CT_INCM_ANN       VARCHAR2(75) DEFAULT 0 NULL,
SC_MRTL              VARCHAR2(20) NULL,
NM_RLG_AFLN          VARCHAR2(40) NULL,
NM_HGH_EDC_LV        VARCHAR2(40) NULL,
ID_PRTY              VARCHAR2(128) NOT NULL,
FL_RC_ML             DECIMAL(1) NULL,
DE_COMMENTS          VARCHAR2(255) NULL
);

CREATE TABLE PA_EM (
ID_EM                VARCHAR2(128) NOT NULL,
ID_PLN_EM_CMN        VARCHAR2(20) NULL,
NM_EM                VARCHAR2(40) NULL,
UN_NMB_SCL_SCTY      CHAR(9) NULL,
TY_EM_CMPSN          VARCHAR2(20) NULL,
ID_PRTY              VARCHAR2(128) NOT NULL,
TY_RO_PRTY           VARCHAR2(60) NOT NULL,
HI_LV_VCTN           DECIMAL(9,2) DEFAULT 0 NULL,
IT_ACCESS_SCRTY      DECIMAL(22) NULL,
QY_LV_SCK            DECIMAL(9,2) DEFAULT 0 NULL,
SC_EM                VARCHAR2(20) NULL
);

CREATE TABLE PA_GP_CT (
ID_GP_ID             VARCHAR2(128) NOT NULL,
NM_GP                VARCHAR2(40) NULL,
DE_GP_CT             VARCHAR2(255) NULL
);

CREATE TABLE PA_KY_CT (
ID_CT                VARCHAR2(128) NOT NULL
);

CREATE TABLE PA_OPR (
ID_OPR               VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_EM                VARCHAR2(128) NULL,
PW_ACS_OPR           VARCHAR2(20) DEFAULT '' NULL
);

CREATE TABLE PA_ORGN (
NM_ORGN              VARCHAR2(40) NULL,
ID_TX_ORGN           VARCHAR2(255) NULL,
SC_ORGN_LG           VARCHAR2(20) NULL,
ID_TX_FDL            VARCHAR2(255) NULL,
ID_TX_ST             VARCHAR2(255) NULL,
CD_FRNK_CMY          VARCHAR2(20) NULL,
ON_FRNK_CMY          VARCHAR2(40) NULL,
ID_GRP_MSG           VARCHAR2(128) NULL,
ID_PRTY_ORGN         VARCHAR2(128) NOT NULL
);

CREATE TABLE PA_PRS (
NM_PRS_SLN           VARCHAR2(40) NULL,
FN_PRS               VARCHAR2(40) NOT NULL,
MD_PRS               CHAR(1) NULL,
LN_PRS               VARCHAR2(40) NOT NULL,
TY_GND_PRS           VARCHAR2(20) NULL,
DC_PRS_BRT           DATE NULL,
ID_PRTY_PRS          VARCHAR2(128) NOT NULL,
MN_PRS               VARCHAR2(40) NULL,
NN_PRS               VARCHAR2(40) NULL,
FL_HND_PRS           DECIMAL(1) NULL
);

CREATE TABLE PA_PRTY (
ID_PRTY              VARCHAR2(128) NOT NULL,
LU_ORG_LG            VARCHAR2(20) NULL,
TY_PRTY              VARCHAR2(20) NULL,
ED_CO                VARCHAR2(20) NULL,
ED_LA                VARCHAR2(20) NULL
);

CREATE TABLE PA_RO_PRTY (
ID_PRTY              VARCHAR2(128) NOT NULL,
TY_RO_PRTY           VARCHAR2(60) NOT NULL,
DC_RO_PRTY_EF        DATE NULL,
DC_RO_PRTY_EP        DATE NULL
);

CREATE TABLE PA_RO_PRTY_TYP (
TY_RO_PRTY           VARCHAR2(60) NOT NULL,
NM_RO_PRTY           VARCHAR2(40) NULL,
DE_RO_PRTY           VARCHAR2(1024) NULL
);

CREATE TABLE PA_STR_RTL (
ID_STR_RT            VARCHAR2(128) NOT NULL,
DC_OPN_RT_STR        DATE NULL,
ID_PRTY              VARCHAR2(128) NOT NULL,
DC_CL_RT_STR         DATE NULL,
TY_RO_PRTY           VARCHAR2(60) NOT NULL,
QU_SZ_STR            DECIMAL(9,2) DEFAULT 0 NULL,
QU_SZ_AR_SL          DECIMAL(9,2) DEFAULT 0 NULL,
LU_ZN_PRC_RT_STR     VARCHAR2(40) NULL,
FL_TX_RGNL           DECIMAL(1) NULL,
DE_TX_RGNL           VARCHAR2(255) NULL,
DE_TX                VARCHAR2(255) NULL,
PE_TX_RGNL           DECIMAL(9,4) NULL,
PE_TX                DECIMAL(9,4) NULL,
PW_ACS_STR           VARCHAR2(20) DEFAULT '' NULL,
TY_CNY               VARCHAR2(40) NULL
);

CREATE TABLE RK_COLLECTION (
TYPE                 VARCHAR(100) NULL,
AMOUNT               VARCHAR2(75) DEFAULT 0 NULL,
COMMENT              VARCHAR(200) NULL,
AI_TRN               VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_COMP_PRM_PK (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
ID_ITM               VARCHAR2(128) NOT NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
COMP_NUM             DECIMAL(3) NOT NULL
);

CREATE TABLE RK_EMP_APP_FORM (
ID                   VARCHAR(50) NOT NULL,
CREATE_DATE          DATE NULL,
SINGED               DATE NULL,
MILITARY_RANK        VARCHAR(100) NULL,
DAYTIME_PHONE        VARCHAR(50) NULL,
FULLTIME             DECIMAL(1) NULL,
PARTTIME             DECIMAL(1) NULL,
TEMP                 DECIMAL(1) NULL,
SALARY               VARCHAR2(75) DEFAULT 0 NULL,
AVAILABLE            DATE NULL,
MOONLIGHTING         DECIMAL(1) NULL,
RELATED_SKILLS       VARCHAR(200) NULL,
SECOND_LANGUAGES     VARCHAR(200) NULL,
VALID_LICENSE        DECIMAL(1) NULL,
EMPLOYMENT_VERIFY    DECIMAL(1) NULL,
AGE                  DECIMAL(22) NULL,
CONVICTION           VARCHAR(200) NULL,
ABLE_TO_PERFORM      DECIMAL(1) NULL,
NECC_ACCOM           VARCHAR(100) NULL,
EMERGENCY_CONTACT    VARCHAR(100) NULL,
EMERGENCY_PHONE      VARCHAR(50) NULL,
ADDITIONAL_INFO      VARCHAR(200) NULL,
SSN                  VARCHAR(50) NULL,
HOME_PHONE           VARCHAR(50) NULL,
FIRST_NAME           VARCHAR(100) NULL,
MIDDLE_NAME          VARCHAR(100) NULL,
ADDRESS              VARCHAR(100) NULL,
LAST_NAME            VARCHAR(100) NULL,
CITY                 VARCHAR(50) NULL,
STATE                VARCHAR(50) NULL,
ZIP_CODE             VARCHAR(50) NULL,
HIRING_STORE_ID      VARCHAR(50) NULL,
PREVIOUS_STORE_ID    VARCHAR(50) NULL,
APPLYING_FOR         VARCHAR2(60) NULL
);

CREATE TABLE RK_EMP_FORM (
ID                   VARCHAR(50) NOT NULL,
TYPE_ID              DECIMAL(3) NULL,
SSN                  VARCHAR(50) NOT NULL,
SIGNED               DATE NULL,
ID_EM                VARCHAR2(128) NULL,
ID_STR_RT            VARCHAR2(128) NULL
);

CREATE TABLE RK_EMP_GL_CH_DT (
SEQ_NUM              DECIMAL(3) NOT NULL,
CHANGE_DATE          DATE NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_EM                VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_EMP_GOAL (
GOAL                 DECIMAL(22) NULL,
STARTING_DATE        DATE NULL,
ENDING_DATE          DATE NULL,
IS_DELETED           DECIMAL(1) NULL,
IS_MODIFIED          DECIMAL(1) NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_EM                VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_EMP_HISTORY (
FORM_ID              VARCHAR(50) NOT NULL,
SEQ_NUM              DECIMAL(22) NOT NULL,
EMPLOYER             VARCHAR(100) NULL,
TYPE_BUSINESS        VARCHAR(100) NULL,
TITLE                VARCHAR(100) NULL,
ADDRESS              VARCHAR(100) NULL,
CITY                 VARCHAR(100) NULL,
STATE                VARCHAR(100) NULL,
ZIP                  VARCHAR(50) NULL,
HIRED                DATE NULL,
LEFT_HANDED          DATE NULL,
SUPERVISOR           VARCHAR(100) NULL,
PHONE                VARCHAR(50) NULL,
MAY_CONTACT          DECIMAL(1) NULL,
EMPLOYMENT           DECIMAL(22) NULL,
DUTIES               VARCHAR(200) NULL,
REASON_LEFT          VARCHAR(200) NULL,
SALARY               VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE RK_EMP_REFERENCE (
FORM_ID              VARCHAR(50) NOT NULL,
SEQ_NUM              DECIMAL(22) NOT NULL,
NAME                 VARCHAR(100) NULL,
OCCUPATION           VARCHAR(100) NULL,
PHONE                VARCHAR(50) NULL
);

CREATE TABLE RK_EMP_RSC (
PREFERRED_MINUTES    DECIMAL(22) NULL,
MAXIMUM_MINUTES      DECIMAL(22) NULL,
STORE_ID             VARCHAR2(128) NULL,
EMPLOYEE_ID          VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_EMP_RSC_ROL (
TYPE_ID              DECIMAL(3) NOT NULL,
SEQ_NUM              DECIMAL(22) NOT NULL,
ROLE_ID              VARCHAR(50) NULL,
EMPLOYEE_ID          VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_EMP_RSC_ROL_TY (
ID                   DECIMAL(3) NOT NULL,
DESCRIPTION          VARCHAR(100) NULL
);

CREATE TABLE RK_EMP_SALE (
SALE_DATE            DATE NULL,
AMOUNT               VARCHAR2(75) DEFAULT 0 NULL,
TRANSACTION_NUMBER   VARCHAR(50) NULL,
NET_AMOUNT           VARCHAR2(75) DEFAULT 0 NULL,
ID_EM                VARCHAR2(128) NULL,
ID_STR_RT            VARCHAR2(128) NULL
);

CREATE TABLE RK_EMP_STATUS (
ID                   VARCHAR2(20) NOT NULL,
DESCRIPTION          VARCHAR(100) NULL
);

CREATE TABLE RK_EMP_TIMECARD (
CUR_STATUS           DECIMAL(3) NULL,
WORK_TIME            DECIMAL(22) NULL,
WEEK_ENDING          VARCHAR(50) NOT NULL,
IS_FINALIZED         DECIMAL(1) NULL,
IS_ADJSTABLE         DECIMAL(1) NULL,
FINALIZ_TIME         VARCHAR(96) NULL,
FINALIZ_MGR          VARCHAR(50) NULL,
COMMENT              VARCHAR(200) NULL,
ID_EM                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NULL
);

CREATE TABLE RK_EOD (
MGR_SAYS_CASH_LIST   VARCHAR(200) NULL,
MGR_SAYS_CHEK_LIST   VARCHAR(200) NULL,
MGR_SAYS_BCRD        VARCHAR2(75) DEFAULT 0 NULL,
MGR_SAYS_AMEX        VARCHAR2(75) DEFAULT 0 NULL,
MGR_SAYS_DISC        VARCHAR2(75) DEFAULT 0 NULL,
MGR_SAYS_TR_CHKS     VARCHAR2(75) DEFAULT 0 NULL,
MGR_SAYS_MNY_ODR     VARCHAR2(75) DEFAULT 0 NULL,
REG_DRWR_FUND        VARCHAR2(75) DEFAULT 0 NULL,
AI_TRN               VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_FORM_TYPE (
ID                   DECIMAL(3) NOT NULL,
DESCRIPTION          VARCHAR(100) NULL
);

CREATE TABLE RK_HOLIDAY (
COUNTY               VARCHAR(50) NULL,
STATE                VARCHAR(50) NULL,
DESCRIPTION          VARCHAR(50) NULL,
TYPE                 VARCHAR(50) NULL,
HOLIDAY_DATE         VARCHAR(50) NULL
);

CREATE TABLE RK_I9_FORM (
ID                   VARCHAR(50) NOT NULL,
EXAMINED_DATE        DATE NULL,
MAIDEN_SURNAME       VARCHAR(100) NULL,
NEW_NAME             VARCHAR(100) NULL,
BIRTH_DATE           DATE NULL,
PREPARED_DATE        DATE NULL,
AUTH_EXPIRATION      DATE NULL,
REHIRE_DATE          DATE NULL,
CITIZENSHIP          DECIMAL(22) NULL,
ALIEN_ID             VARCHAR(100) NULL,
PREPARER_ID          VARCHAR2(128) NULL,
EXAMINER_ID          VARCHAR2(128) NULL
);

CREATE TABLE RK_ID_DOC (
FORM_ID              VARCHAR(50) NOT NULL,
TYPE_ID              DECIMAL(3) NOT NULL,
TYPE                 DECIMAL(22) NULL,
DOCUMENT_NUMBER      VARCHAR(100) NULL,
ISSUER               VARCHAR(100) NULL,
EXPIRATION_DATE      DATE NULL
);

CREATE TABLE RK_ID_DOC_TYPE (
ID                   DECIMAL(3) NOT NULL,
DESCRIPTION          VARCHAR(100) NULL
);

CREATE TABLE RK_LAY (
ID                   VARCHAR(50) NOT NULL,
ORGL_DATE            DATE NULL,
ORGL_AMOUNT          VARCHAR2(75) DEFAULT 0 NULL,
ORGL_NET_AMOUNT      VARCHAR2(75) DEFAULT 0 NULL,
CURR_AMOUNT_DUE      VARCHAR2(75) DEFAULT 0 NULL,
STORE_ID             VARCHAR(50) NULL,
CONSULTANT_ID        VARCHAR(50) NULL,
AUDIT_FLAG           VARCHAR(50) NULL,
DELETED              DECIMAL(1) DEFAULT 0 NULL,
RESTOCK_PERCENT      DECIMAL(9,4) NULL,
IS_RESTOCK_FREE      DECIMAL(1) NULL,
ID_CT                VARCHAR2(128) NULL,
AI_TRN               VARCHAR2(128) NULL
);

CREATE TABLE RK_LAY_PAY (
AMOUNT               VARCHAR2(75) DEFAULT 0 NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
ORIGINAL_ID          VARCHAR(50) NULL
);

CREATE TABLE RK_LAY_PAY_INFO (
ID                   VARCHAR(50) NOT NULL,
PAID_DATE            DATE NOT NULL,
SEQUENCE_NUMBER      DECIMAL(3) NOT NULL,
AMOUNT               VARCHAR2(75) DEFAULT 0 NOT NULL,
TXN_ID               VARCHAR(50) NULL,
STORE_ID             VARCHAR(50) NULL
);

CREATE TABLE RK_LAY_RTS (
REFUND_AMOUNT        VARCHAR2(75) DEFAULT 0 NULL,
RESTOCKING_FEE       VARCHAR2(75) DEFAULT 0 NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
ORGN_LAY_ID          VARCHAR(50) NULL
);

CREATE TABLE RK_LOT (
ID                   VARCHAR(50) NOT NULL,
RECEIVED_DATE        DATE NULL,
INITIAL_QTY          DECIMAL(22) NULL,
REMOVED_QTY          DECIMAL(22) NULL,
RESERVED_QTY         DECIMAL(22) NULL,
IN_TRANSIT_QTY       DECIMAL(22) NULL,
LAYAWAY_QTY          DECIMAL(22) NULL,
RENTED_QTY           DECIMAL(22) NULL,
ITEM_ID              VARCHAR2(128) NULL,
STORE_ID             VARCHAR2(128) NULL
);

CREATE TABLE RK_LOT_TRN (
LOT_ID               VARCHAR(50) NOT NULL,
REMOVED_QTY          DECIMAL(22) NULL,
RETURNED_QTY         DECIMAL(22) NULL,
RESERVED_QTY         DECIMAL(22) NULL,
RELEASED_QTY         DECIMAL(22) NULL,
IN_TRANSIT_QTY       DECIMAL(22) NULL,
CNCL_TRANSIT_QTY     DECIMAL(22) NULL,
LAID_AWAY_QTY        DECIMAL(22) NULL,
RTN_TO_STOCK_QTY     DECIMAL(22) NULL,
RENTED_QTY           DECIMAL(22) NULL,
RENTAL_RTN_QTY       DECIMAL(22) NULL,
TRANSACTION_ID       VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_NO_SALE (
COMMENT              VARCHAR(200) NULL,
AI_TRN               VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_PAID_OUT (
TYPE                 VARCHAR(100) NULL,
AMOUNT               VARCHAR2(75) DEFAULT 0 NULL,
COMMENT              VARCHAR(200) NULL,
AI_TRN               VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_PAY_SUM (
ID                   VARCHAR(50) NOT NULL,
PAYMENT_DATE         DATE NOT NULL,
REGISTER_ID          VARCHAR(50) NULL,
PAYMENT_TYPE         VARCHAR(50) NULL,
PAYMENT_TOTAL        VARCHAR2(75) DEFAULT 0 NULL,
ID_STR_RT            VARCHAR2(128) NULL,
ID_EM                VARCHAR2(128) NULL
);

CREATE TABLE RK_PAY_TRN (
PAY_TYPES            VARCHAR(1024) NULL,
TOTAL_AMT            VARCHAR2(75) DEFAULT 0 NULL,
CUST_ID              VARCHAR(50) NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
TYPE_ID              VARCHAR2(60) NULL
);

CREATE TABLE RK_POS_LAY (
DEPOSIT_PERCENT      DECIMAL(9,4) NULL,
RESTOCKING_PERCENT   DECIMAL(9,4) NULL,
RESTOCKING_FREE      DECIMAL(1) NULL,
DESIRED_AMOUNT_DUE   VARCHAR2(75) DEFAULT 0 NULL,
PAYMENT_FREQUENCY    DECIMAL(3) NULL,
LAYAWAY_ID           VARCHAR(50) NULL,
AI_TRN               VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_POS_LN_ITM_DTL (
SEQUENCE_NUMBER      DECIMAL(3) NOT NULL,
NET_AMT              VARCHAR2(75) DEFAULT 0 NULL,
TAX_AMT              VARCHAR2(75) DEFAULT 0 NULL,
MANUAL_TAX_AMT       VARCHAR2(75) DEFAULT 0 NULL,
REGIONAL_TAX_AMT     VARCHAR2(75) DEFAULT 0 NULL,
DEAL_MKDN_AMT        VARCHAR2(75) DEFAULT 0 NULL,
USER_ENTERED_FL      DECIMAL(1) NULL,
MAN_REG_TAX_AMT      VARCHAR2(75) DEFAULT 0 NULL,
GIFT_CERT_ID         VARCHAR(100) NULL,
SALE_RETURNED        DECIMAL(1) NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL,
DEAL_ID              VARCHAR(50) NULL,
VAT_AMT              VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE RK_POS_LN_ITM_TYP (
ID                   DECIMAL(3) NOT NULL,
DESCRIPTION          VARCHAR(100) NULL
);

CREATE TABLE RK_PRM_IT (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
TRIGGER_QTY          DECIMAL(3) NULL,
TRIGGER_AMT          VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE RK_PRM_ITM (
ID_ITM               VARCHAR2(128) NOT NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
ID_RU_PRDV           VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_PRM_MB (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
SEQ_NUM              DECIMAL(3) NOT NULL,
AMOUNT               VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE RK_PRM_MU (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
QTY_BREAK            DECIMAL(3) NULL
);

CREATE TABLE RK_PRM_PK (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
COMP_COUNTS          DECIMAL(3) NULL,
IS_PERCENT           DECIMAL(1) NULL
);

CREATE TABLE RK_PRM_PK_AMT (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
SEQ_NUM              DECIMAL(3) NOT NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
AMOUNT               VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE RK_PRM_PK_PE (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
SEQ_NUM              DECIMAL(3) NOT NULL,
PERCENT              DECIMAL(7,4) DEFAULT 0 NULL
);

CREATE TABLE RK_REDM_BYBK (
AMOUNT               VARCHAR2(75) DEFAULT 0 NULL,
COMMENT              VARCHAR(200) NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
ID_NMB_SRZ_GF_CF     VARCHAR2(40) NULL,
TY_GF_CF             VARCHAR2(40) NULL
);

CREATE TABLE RK_REDM_HIST (
SEQ_NUM              DECIMAL(3) NOT NULL,
DATE_USED            DATE NULL,
AMOUNT_USED          VARCHAR2(75) DEFAULT 0 NULL,
TRANS_ID_USED        VARCHAR(50) NULL,
ID_NMB_SRZ_GF_CF     VARCHAR2(40) NOT NULL,
TY_GF_CF             VARCHAR2(40) NOT NULL
);

CREATE TABLE RK_REDUCTION (
DETAIL_SEQ_NUMBER    DECIMAL(3) NULL,
AMOUNT               VARCHAR2(75) DEFAULT 0 NULL,
REASON               VARCHAR(200) NULL,
AI_TRN               VARCHAR2(128) NULL,
AI_LN_ITM            SMALLINT NULL
);

CREATE TABLE RK_RELATED_EMP (
FORM_ID              VARCHAR(50) NOT NULL,
NAME                 VARCHAR(100) NULL,
SEQ_NUM              DECIMAL(3) NOT NULL,
STORE                VARCHAR(100) NULL
);

CREATE TABLE RK_ROLE (
ID                   VARCHAR(50) NOT NULL,
LABEL                VARCHAR(100) NULL,
STRENGTH             DECIMAL(22) NULL,
PREFERRED            DECIMAL(1) NULL,
DISPLAY_BACKGROUND   VARCHAR(100) NULL,
SORT_PRECEDENCE      DECIMAL(3) NULL
);

CREATE TABLE RK_RTN_POS_LN_ITM (
SEQUENCE_NUMBER      DECIMAL(3) NOT NULL,
RTN_AI_TRN           VARCHAR2(128) NULL,
RTN_AI_LN_ITM        SMALLINT NULL,
SALE_AI_TRN          VARCHAR2(128) NULL,
SALE_AI_LN_ITM       SMALLINT NULL,
SALE_DTL_SEQ_NUM     DECIMAL(3) NULL
);

CREATE TABLE RK_SALES_SUMMARY (
ID                   VARCHAR(50) NOT NULL,
SALES_DATE           DATE NULL,
NET_AMOUNT           VARCHAR2(75) DEFAULT 0 NULL,
REGISTER_ID          VARCHAR(50) NULL,
TOTAL_QUANTITY       DECIMAL(22) NULL,
TAX_AMOUNT           VARCHAR2(75) DEFAULT 0 NULL,
REG_TAX_AMOUNT       VARCHAR2(75) DEFAULT 0 NULL,
ID_ITM               VARCHAR2(128) NULL,
ID_EM                VARCHAR2(128) NULL,
ID_STR_RT            VARCHAR2(128) NULL
);

CREATE TABLE RK_SCHEDULE (
ID                   VARCHAR(50) NOT NULL,
BEGIN_DATE           DATE NULL,
END_DATE             DATE NULL,
COMMENT              VARCHAR(200) NULL,
STORE_ID             VARCHAR2(128) NULL
);

CREATE TABLE RK_SHIFT (
SCHEDULE_ID          VARCHAR(50) NOT NULL,
SEQ_NUM              DECIMAL(22) NOT NULL,
ROLE_ID              VARCHAR(50) NULL,
DISPLAY_NAME         VARCHAR(100) NULL,
TM_RNG_BEGIN_TIME    DATE NULL,
TM_RNG_END_TIME      DATE NULL,
TM_RNG_REASON        VARCHAR(200) NULL,
TM_RNG_PREFERRED     DECIMAL(1) NULL,
EMPLOYEE_ID          VARCHAR2(128) NULL
);

CREATE TABLE RK_SHIP_REQ (
SEQ_NUM              DECIMAL(3) NOT NULL,
FIRST_NAME           VARCHAR(100) NULL,
LAST_NAME            VARCHAR(100) NULL,
ADDRESS              VARCHAR(100) NULL,
APARTMENT            VARCHAR(50) NULL,
CITY                 VARCHAR(50) NULL,
STATE                VARCHAR(50) NULL,
ZIP_CODE             VARCHAR(50) NULL,
COUNTRY              VARCHAR(50) NULL,
PHONE                VARCHAR(50) NULL,
SPECIAL_INSTR        VARCHAR(200) NULL,
GIFT_MESSAGE         VARCHAR(200) NULL,
AI_TRN               VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_SOS (
STORE_ID             VARCHAR(50) NULL,
DRAWER_FUND          VARCHAR2(75) DEFAULT 0 NULL,
AI_TRN               VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_STR_GL_CHG_DATE (
SEQ_NUM              DECIMAL(3) NOT NULL,
CHANGE_DATE          DATE NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_STR_GOAL (
THE_OPERATOR_ID      VARCHAR(50) NULL,
GOAL                 DECIMAL(22) NULL,
ENDING_DATE          DATE NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
STARTING_DATE        DATE NULL
);

CREATE TABLE RK_TH_PRM (
ID                   VARCHAR2(128) NOT NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
START_DATE           DATE NULL,
END_DATE             DATE NULL,
AMOUNT_OFF           VARCHAR2(75) DEFAULT 0 NULL,
PERCENT_OFF          DECIMAL(7,4) DEFAULT 0 NULL,
PERCENT_OFF_FL       DECIMAL(1) NULL,
THRESHOLD_AMT        VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE RK_TIMECARD (
TIME_STAMP           VARCHAR(96) NULL,
DELETED              DECIMAL(1) NULL,
ID                   VARCHAR(50) NOT NULL,
WEEK_ENDING          VARCHAR(50) NULL,
MANAGER_REASON       VARCHAR(200) NULL,
TY_TRN               VARCHAR2(60) NULL,
ID_OP                VARCHAR2(128) NULL,
ID_EM                VARCHAR2(128) NULL,
ID_RPSTY_TND         VARCHAR2(128) NULL,
ID_STR_RT            VARCHAR2(128) NULL
);

CREATE TABLE RK_TIMECARD_BEN (
ID                   VARCHAR(50) NOT NULL,
CODE                 VARCHAR(50) NULL,
MINUTES              DECIMAL(22) NULL,
BEN_DATE             DATE NULL
);

CREATE TABLE RK_TIMECARD_MOD (
ID                   VARCHAR(50) NOT NULL,
APPROVED_STATUS      DECIMAL(22) NULL,
REASON               VARCHAR(200) NULL,
MOD_ACTION           DECIMAL(22) NULL,
OLD_ID               VARCHAR(50) NULL,
NEW_ID               VARCHAR(50) NULL
);

CREATE TABLE RK_TIME_RANGE (
TYPE_ID              DECIMAL(3) NOT NULL,
SEQ_NUM              DECIMAL(22) NOT NULL,
BEGIN_TIME           DATE NULL,
END_TIME             DATE NULL,
REASON               VARCHAR(200) NULL,
PREFER               DECIMAL(1) NULL,
EMPLOYEE_ID          VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_TIME_RANGE_TYPE (
ID                   DECIMAL(3) NOT NULL,
DESCRIPTION          VARCHAR(100) NULL
);

CREATE TABLE RK_TRANSFER (
FROM_STORE_ID        VARCHAR(50) NULL,
TO_STORE_ID          VARCHAR(50) NULL,
COMMENTS             VARCHAR(200) NULL,
ID                   VARCHAR2(128) NOT NULL,
TRN_TYPE_ID          VARCHAR2(60) NULL
);

CREATE TABLE RK_TRANSFER_IN (
DATE_RECEIVED        DATE NULL,
ID                   VARCHAR2(128) NOT NULL,
TRANSFER_OUT_ID      VARCHAR2(128) NULL
);

CREATE TABLE RK_TRANSFER_LN_ITM (
SEQ_NUM              DECIMAL(3) NOT NULL,
QUANTITY             DECIMAL(22) NULL,
ITEM_RETAIL          VARCHAR2(75) DEFAULT 0 NULL,
TRANSFER_ID          VARCHAR2(128) NOT NULL,
ITEM_ID              VARCHAR2(128) NULL
);

CREATE TABLE RK_TRANSFER_OUT (
DATE_SENT            DATE NULL,
COMPLETION_STATUS    DECIMAL(1) NULL,
ID                   VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_TXN_TY_SUM (
ID                   VARCHAR(50) NOT NULL,
SUMMARY_DATE         DATE NULL,
REGISTER_ID          VARCHAR(50) NULL,
TOTAL                VARCHAR2(75) DEFAULT 0 NULL,
TXN_TYPE             VARCHAR(50) NULL,
VOIDED_TYPE          VARCHAR(50) NULL,
TAX_TOTAL            VARCHAR2(75) DEFAULT 0 NULL,
TXN_COUNT            DECIMAL(30) NULL,
REDUCTION_TOT        VARCHAR2(75) DEFAULT 0 NULL,
REG_TAX_TOTAL        VARCHAR2(75) DEFAULT 0 NULL,
DEAL_TOTAL           VARCHAR2(75) DEFAULT 0 NULL,
MARKDOWN_TOT         VARCHAR2(75) DEFAULT 0 NULL,
DISCOUNT_TOT         VARCHAR2(75) DEFAULT 0 NULL,
ID_STR_RT            VARCHAR2(128) NULL,
ID_EM                VARCHAR2(128) NULL
);

CREATE TABLE RK_VAC_REQ_DATE (
FORM_ID              VARCHAR(50) NOT NULL,
SEQ_NUM              DECIMAL(22) NOT NULL,
VAC_DATE             DATE NULL
);

CREATE TABLE RK_VAC_REQ_FORM (
ID                   VARCHAR(50) NOT NULL,
TYPE                 DECIMAL(22) NULL,
REASON               VARCHAR(200) NULL,
TOTAL_HOURS          DECIMAL(9,4) NULL,
SUPERVISOR_ID        VARCHAR2(128) NULL,
AUTH_MGR_ID          VARCHAR2(128) NULL
);

CREATE TABLE RK_VOID_TRANSFER (
REASON               VARCHAR(200) NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
ORIGINAL_ID          VARCHAR2(128) NULL
);

CREATE TABLE RK_VOID_TRN (
ORIGINAL_ID          VARCHAR(50) NOT NULL,
REASON               VARCHAR(200) NULL,
VOIDED_AMOUNT        VARCHAR2(75) DEFAULT 0 NULL,
AI_TRN               VARCHAR2(128) NOT NULL
);

CREATE TABLE RK_W4_FORM (
ID                   VARCHAR(50) NOT NULL,
EXEMPT               DECIMAL(1) NULL,
DIFFERS              DECIMAL(1) NULL,
STATUS               DECIMAL(22) NULL,
ALLOWANCES           DECIMAL(22) NULL,
ADDITIONAL_AMOUNT    VARCHAR2(75) DEFAULT 0 NULL,
IDENTIFICATION       VARCHAR(100) NULL,
OFFICE_CODE          VARCHAR(100) NULL
);

CREATE TABLE RU_DS (
ID_AGNT_RTN          VARCHAR2(128) NULL,
LU_UOM_DS_PD         CHAR(2) NULL,
ID_ITM               VARCHAR2(128) NOT NULL,
MO_UOM_DS_PD         DECIMAL(14,3) DEFAULT 0 NULL
);

CREATE TABLE RU_PRDV (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
NM_RU_PRDV           VARCHAR2(40) NULL,
DE_RU_PRDV           VARCHAR2(255) NULL,
LU_CBRK_PRDV_TRN     CHAR(2) NULL,
SC_RU_PRDV           CHAR(2) NULL,
TY_RU_PRDV           CHAR(2) NULL
);

CREATE TABLE RU_PRDV_ITM (
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
CURRENCY_CODE        VARCHAR(50) NOT NULL,
CD_RDN_MTH           VARCHAR(50) NULL,
MO_RDN               VARCHAR2(75) DEFAULT 0 NULL,
PE_RDN               DECIMAL(7,4) DEFAULT 0 NULL,
MO_PRC               VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE RU_PRM_PRDV (
ID_PRM               VARCHAR2(128) NOT NULL,
ID_RU_PRDV           VARCHAR2(128) NOT NULL,
ID_GP_TM             VARCHAR2(256) NULL
);

CREATE TABLE ST_ASGMT_EM_STR (
ID_EM                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
DC_ASGMT_STR_EF      DATE NULL,
DC_ASGMT_STR_EP      DATE NULL,
SC_ASGMT_STR         VARCHAR2(20) NOT NULL
);

CREATE TABLE ST_EM_ASGMT (
ID_EM                VARCHAR2(128) NOT NULL,
ID_PST               VARCHAR2(128) NOT NULL,
SC_EM_ASGMT          VARCHAR2(20) NULL,
DC_EF                DATE NULL,
DC_EP                DATE NULL
);

CREATE TABLE ST_JOB (
CD_JOB               VARCHAR2(60) NOT NULL,
NM_JOB               VARCHAR2(40) NULL,
DE_JOB               VARCHAR2(1024) NULL
);

CREATE TABLE ST_ORGN_STRC (
ID_PRTY_ORGN_SUB     VARCHAR2(128) NULL,
ID_PRTY_ORGN_PRNT    VARCHAR2(128) NOT NULL
);

CREATE TABLE TR_CHN_PRN_PRC (
ID_EV                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
MO_CHN_PRN_UN_PRC    VARCHAR2(75) DEFAULT 0 NULL,
TY_CHN_PRN_UN_PRC    CHAR(2) NULL
);

CREATE TABLE TR_CHN_TMP_PRC (
ID_EV                VARCHAR2(128) NOT NULL,
ID_STR_RT            VARCHAR2(128) NOT NULL,
MO_UN_TMP_PRC_CHN    VARCHAR2(75) DEFAULT 0 NULL,
TY_UN_TMP_PRC_CHN    CHAR(2) NULL
);

CREATE TABLE TR_DSC (
TY_DSC               VARCHAR2(20) NOT NULL,
ID_STR_RT            VARCHAR2(128) NULL,
ID_ACNT_LDG          VARCHAR2(128) NULL,
NM_DSC               VARCHAR2(40) NULL,
DE_DSC               VARCHAR2(255) NULL,
CD_RDN_MTH           VARCHAR2(20) NULL,
MO_RDN_AMT           VARCHAR2(75) DEFAULT 0 NULL,
PE_RDN_AMT           DECIMAL(7,4) DEFAULT 0 NULL,
MO_NW_PRC            VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE TR_LTM_CHK_TND (
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL,
ID_BK_CHK            VARCHAR2(128) NULL,
ID_ACNT_CHK          VARCHAR2(128) NULL,
AI_CHK               VARCHAR(50) NULL,
TY_ID_PRSL_RQ        VARCHAR2(20) NULL,
ID_PRSL_AZN          VARCHAR2(128) NULL,
ID_ADJN_CHK          VARCHAR2(40) NULL,
DC_BRT_CHK           CHAR(2) NULL,
LU_CLS_TND           VARCHAR2(40) NULL,
TRANSIT_NUMBER       VARCHAR(100) NULL,
MICR_DATA            VARCHAR(200) NULL,
TENDER_TYPE          VARCHAR(100) NULL,
MSG_TYPE             VARCHAR(100) NULL,
MSG_IDENTIFIER       VARCHAR(100) NULL,
EMPLOYEE_ID          VARCHAR(50) NULL,
MANUAL_OVERRIDE      DECIMAL(1) NULL,
AUTH_REQUIRED        DECIMAL(1) NULL,
RSP_AUTH_RESP_CODE   VARCHAR(100) NULL,
RSP_AUTH_CODE        VARCHAR(100) NULL,
RSP_STAT_CODE_DESC   VARCHAR(100) NULL,
RSP_STAT_CODE        VARCHAR(100) NULL,
RSP_HOST_ACT_CODE    VARCHAR(100) NULL,
APPROVAL_DATE        DATE NULL,
RESP_ID              VARCHAR(100) NULL,
IS_ID_SCANNED_IN     DECIMAL(1) NULL,
DRVR_LICENSE_NUM     VARCHAR(100) NULL,
STATE_ID_CODE        VARCHAR(100) NULL,
ACTION_DATE          VARCHAR(100) NULL,
CHECK_SCANNED_IN     DECIMAL(1) NULL
);

CREATE TABLE TR_LTM_CPN_TND (
ID_STR_RT            VARCHAR2(128) NOT NULL,
DC_DY_BSN            DATE NOT NULL,
ID_WS                VARCHAR2(128) NOT NULL,
ID_MF                VARCHAR2(128) NULL,
UC_CPN_SC            VARCHAR2(15) DEFAULT '' NULL,
FC_FMY_MF            CHAR(3) NULL,
TY_CPN               VARCHAR2(20) NULL,
AI_LN_ITM_VL         SMALLINT NULL,
DC_CPN_EP            VARCHAR2(20) NULL,
LU_CPN_PRM           VARCHAR2(60) NULL,
FL_ENR_CPN_KY        DECIMAL(1) NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL
);

CREATE TABLE TR_LTM_CRDB_CRD_TN (
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL,
ID_ISSR_TND_MD       VARCHAR2(128) NULL,
ID_ACNT_DB_CR_CRD    VARCHAR2(40) NULL,
TY_ID_PRSL_RQ        VARCHAR2(20) NULL,
ID_RFC_PRSL_ID       VARCHAR2(128) NULL,
LU_MTH_AZN           VARCHAR2(40) NULL,
DE_TRCK_2_BT_MP      VARCHAR(200) NULL,
LU_ADJN_CR_DB        VARCHAR2(60) NULL,
LU_NMB_CRD_SWP_KY    VARCHAR2(20) NULL,
CH_IM_TND_AZN_CT     VARCHAR2(20) NULL,
LU_CLS_TND           VARCHAR2(40) NULL,
APPROVAL_DATE        DATE NULL,
RESP_ID              VARCHAR(100) NULL,
TRACK_DATA           VARCHAR(200) NULL,
TRACK_NUMBER         VARCHAR(100) NULL,
EXPIRATION_DATE      DATE NULL,
TENDER_TYPE          VARCHAR(100) NULL,
MESSAGE_TYPE         VARCHAR(100) NULL,
MESSAGE_IDENTIFIER   VARCHAR(100) NULL,
RESP_STATUS_DESC     VARCHAR(100) NULL,
RESP_STATUS_CODE     VARCHAR(100) NULL,
RESP_HOST_ACTION     VARCHAR(100) NULL,
AMEX_CID_NUMBER      VARCHAR(50) NULL,
MANUAL_OVERRIDE      DECIMAL(1) NULL,
AUTH_REQUIRED        DECIMAL(1) NULL,
COMPANY_NAME         VARCHAR(100) NULL,
HOLDER_NAME          VARCHAR(100) NULL,
RESP_VALID_CODE      VARCHAR(100) NULL,
RESP_TRANS_IDFR      VARCHAR(100) NULL,
RESP_PAY_SERVICE     VARCHAR(100) NULL,
RESP_ADDRESS_VERIF   VARCHAR(100) NULL,
RESP_AUTH_SOURCE     VARCHAR(100) NULL,
RESP_POS_ENTRY_MOD   VARCHAR(100) NULL,
RESP_AUTH_RESPONSE   VARCHAR(100) NULL,
RESP_AUTHORIZATION   VARCHAR(100) NULL
);

CREATE TABLE TR_LTM_DSC (
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL,
TY_DSC               VARCHAR2(20) NULL,
MO_DSC               VARCHAR2(75) DEFAULT 0 NULL,
CNVT_TO_MKDN         DECIMAL(1) NULL,
IS_DSC_PERCENT       DECIMAL(1) NULL,
IS_ADDITION_TO_MD    DECIMAL(1) NULL,
IS_SIG_REQUIRED      DECIMAL(1) NULL,
ADVERTISING_CODE     VARCHAR(200) NULL,
CORPORATE_ID         VARCHAR2(128) NULL,
EMPLOYEE_ID          VARCHAR2(128) NULL,
REASON               VARCHAR(200) NULL,
PERCENT              DECIMAL(7,4) DEFAULT 0 NULL,
GUI_LABEL            VARCHAR(200) NULL,
TYPE                 VARCHAR(200) NULL
);

CREATE TABLE TR_LTM_EM__DSC (
AI_LN_ITM            SMALLINT NOT NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
ID_EM                VARCHAR2(128) NULL,
ID_GP_EM_DSC         VARCHAR2(128) NULL,
MO_ITM_LN_EM_DSC     VARCHAR2(75) DEFAULT 0 NULL
);

CREATE TABLE TR_LTM_GF_CF (
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL,
LU_NMB_SRZ_SC_KY     VARCHAR2(20) NULL
);

CREATE TABLE TR_LTM_GF_CF_TND (
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL,
ID_STR_ISSG          VARCHAR2(128) NULL,
ID_NMB_SRZ_GF_CF     VARCHAR2(40) NULL,
CONTROL_NUMBER       VARCHAR(200) NULL,
AUDIT_NOTE           VARCHAR(200) NULL,
TYPE                 VARCHAR(50) NULL,
ISSUE_AMOUNT         VARCHAR2(75) DEFAULT 0 NULL,
CREATE_DATE          DATE NULL,
FIRST_NAME           VARCHAR(200) NULL,
LAST_NAME            VARCHAR(200) NULL,
PHONE_NUMBER         VARCHAR(50) NULL,
LU_CLS_TND           VARCHAR2(40) NULL
);

CREATE TABLE TR_LTM_RTL_TRN (
AI_LN_ITM            SMALLINT NOT NULL,
TY_LN_ITM            VARCHAR2(20) NULL,
TS_LN_ITM_BGN        DATE NULL,
TS_LN_ITM_END        DATE NULL,
FL_VD_LN_ITM         DECIMAL(1) NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
ID_ITM               VARCHAR2(128) NULL,
POS_LN_ITM_TY_ID     DECIMAL(3) NULL,
ADD_CONSULTANT_ID    VARCHAR2(128) NULL,
MANUAL_UNIT_PRICE    VARCHAR2(75) DEFAULT 0 NULL,
MANUAL_MD_AMT        VARCHAR2(75) DEFAULT 0 NULL,
VALID_NET_AMT_FL     DECIMAL(1) NULL,
ITM_SEL_PRICE        VARCHAR2(75) DEFAULT 0 NULL,
ITM_RETAIL_PRICE     VARCHAR2(75) DEFAULT 0 NULL,
MISC_ITEM_RG_TXBL    DECIMAL(1) NULL,
MISC_ITEM_TXBL       DECIMAL(1) NULL,
MISC_ITEM_DESC       VARCHAR(200) NULL,
MISC_ITEM_ID         VARCHAR2(128) NULL,
RETURN_COMMENTS      VARCHAR(200) NULL,
RETURN_REASON_ID     VARCHAR(200) NULL,
MANUAL_MD_REASON     VARCHAR(200) NULL,
REG_TAX_EXEMPT_ID    VARCHAR2(128) NULL,
TAX_EXEMPT_ID        VARCHAR2(128) NULL,
SHIP_REQ_SEQ_NUM     DECIMAL(3) NULL,
MISC_ITEM_COMMENT    VARCHAR(200) NULL,
MISC_ITEM_GL_ACC     VARCHAR(200) NULL,
QUANTITY             DECIMAL(22) NULL
);

CREATE TABLE TR_LTM_SLS_RTN (
ID_STR_RT            VARCHAR2(128) NOT NULL,
ID_STR_RT_ORG        VARCHAR2(128) NULL,
ID_WS                VARCHAR2(128) NOT NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL,
DC_DY_BSN            DATE NOT NULL,
ID_WS_ORG            VARCHAR2(128) NULL,
DC_DY_BSN_ORG        DATE NULL,
AI_LN_ITM_ORG        SMALLINT NULL,
AI_TRN_ORG           VARCHAR2(128) NULL,
ID_DPT_POS           VARCHAR2(128) NULL,
ID_GP_TX             VARCHAR2(128) NULL,
ID_ITM_POS           CHAR(14) NOT NULL,
QU_ITM_LM_RTN_SLS    DECIMAL(9,2) DEFAULT 0 NULL,
MO_EXTND             VARCHAR2(75) DEFAULT 0 NULL,
FL_RTN_MR            DECIMAL(1) NULL,
RC_RTN_MR            VARCHAR2(20) NULL,
FL_RFD_SV            DECIMAL(1) NULL,
RC_RFD_SV            VARCHAR2(20) NULL,
LU_MTH_ID_ENR        VARCHAR2(40) NULL,
LU_ENR_RT_PRC        VARCHAR2(40) NULL,
LU_PRC_RT_DRVN       VARCHAR2(40) NULL
);

CREATE TABLE TR_LTM_TND (
AI_TRN               VARCHAR2(128) NOT NULL,
AI_LN_ITM            SMALLINT NOT NULL,
TY_TND               VARCHAR2(40) NULL,
ID_ACNT_NMB          VARCHAR2(128) NULL,
ID_ACNT_TND          VARCHAR2(128) NULL,
MO_ITM_LN_TND        VARCHAR2(75) DEFAULT 0 NULL,
LU_CLS_TND           VARCHAR2(40) NULL
);

CREATE TABLE TR_RTL (
IN_RNG_ELPSD         DECIMAL(5,0) DEFAULT 0 NULL,
IN_TND_ELPSD         DECIMAL(5,0) DEFAULT 0 NULL,
IN_ELPSD_IDL         DECIMAL(5,0) DEFAULT 0 NULL,
IN_LCK_ELPSD         DECIMAL(5,0) DEFAULT 0 NULL,
QU_ITM_LN_SC         DECIMAL(7,0) DEFAULT 0 NULL,
QU_ITM_LN_KY         DECIMAL(7,0) DEFAULT 0 NULL,
PE_ITM_LN_SC         DECIMAL(7,4) DEFAULT 0 NULL,
PE_ITM_LN_KY         DECIMAL(7,4) DEFAULT 0 NULL,
ID_CT                VARCHAR2(128) NULL,
QU_DPT_KY            DECIMAL(7,0) DEFAULT 0 NULL,
PE_DPT_KY            DECIMAL(7,4) DEFAULT 0 NULL,
AI_TRN               VARCHAR2(128) NOT NULL,
CONSULTANT_ID        VARCHAR2(128) NULL,
TAX_EXEMPT_ID        VARCHAR2(128) NULL,
REG_TAX_EXMP_ID      VARCHAR2(128) NULL,
NOT_RTN_REASON       VARCHAR(200) NULL,
REDUCTION_AMOUNT     VARCHAR2(75) DEFAULT 0 NULL,
NET_AMOUNT           VARCHAR2(75) DEFAULT 0 NULL,
DISCOUNT_TYPES       VARCHAR(200) NULL,
REGISTER_ID          VARCHAR2(128) NULL,
ITEMS_IDS            VARCHAR(1024) NULL
);

CREATE TABLE TR_TRN (
AI_TRN               VARCHAR2(128) NOT NULL,
ID_OPR               VARCHAR2(128) NULL,
TY_TRN               VARCHAR2(60) NULL,
TS_TM_SRT            DATE NULL,
TS_TRN_BGN           DATE NULL,
TS_TRN_END           DATE NULL,
FL_TRG_TRN           DECIMAL(1) NULL,
FL_KY_OFL            DECIMAL(1) NULL,
TS_TRN_PST           DATE NULL,
TS_TRN_SBM           DATE NULL,
TS_TRN_CRT           DATE NULL,
TS_TRN_PRC           DATE NULL,
TY_GUI_TRN           VARCHAR2(128) NULL,
ID_VOID              VARCHAR2(128) NULL,
DE_HND_TCK           VARCHAR2(255) NULL,
NOT_VOID_REASON      VARCHAR(200) NULL,
ID_RPSTY_TND         VARCHAR2(128) NULL,
ID_STR_RT            VARCHAR2(128) NULL
);

