create table ARM_CURRENCY_RATE
(
    ID_CNY_FROM  varchar2(10),
    ID_CNY_TO  varchar2(10),
    MO_RT_TO_BUY number,
    UPDATE_DT date,
    CONSTRAINT CNY_FROM_TO_PK PRIMARY KEY (ID_CNY_FROM,ID_CNY_TO)
);

ALTER TABLE AS_TL
ADD (
 DE_RPSTY_TND VARCHAR2(50),
 TY_RND VARCHAR2(10)
 TY_RPSTY_TND VARCHAR2(10)
);

ALTER TABLE PA_STR_RTL
ADD (
   ID_BRAND VARCHAR2(30),
   FISCAL_CODE VARCHAR2(30),
   DE_STR_RT VARCHAR2(50),
   DE_CNY VARCHAR2(50),
   ID_STR_RT VARCHAR2(128),
   DE_CMY VARCHAR2(50)
);

ALTER TABLE PA_EM
ADD (
  ARM_EXTERNAL_ID VARCHAR2(30),
  ID_CT VARCHAR2(128)
 );

ALTER TABLE RU_PRM_PRDV
ADD ( ID_STR_RT  VARCHAR2(128) );

ALTER TABLE RK_PRM_ITM
ADD ( ID_STR_RT  VARCHAR2(128) );

ALTER TABLE LO_ADS_PRTY ADD TY_ADS VARCHAR2 (30);

ALTER TABLE CO_PRM DROP CONSTRAINT PRIMARY KEY CASCADE;

ALTER TABLE CO_PRM 
ADD   CONSTRAINT CO_PRM_PK PRIMARY KEY ( ID_PRM, ID_STR_RT );

ALTER TABLE RU_PRM_PRDV DROP CONSTRAINT PRIMARY KEY CASCADE;

ALTER TABLE RU_PRM_PRDV
ADD   CONSTRAINT RU_PRM_PRDV PRIMARY KEY ( id_prm, id_ru_prdv, id_str_rt );

CREATE TABLE ARM_MISC_LOOKUP (
 LOOKUP_TYPE  VARCHAR2(30) NOT NULL,
 LOOKUP_CODE  VARCHAR2(30) NOT NULL,
 MEANING      VARCHAR2(80) NOT NULL,
 DESCRIPTION  VARCHAR2(240),
 ENABLED_FLAG VARCHAR2(1) NOT NULL 
);

ALTER TABLE RU_PRDV ADD APPLICABLE_ITM CHAR(1);

ALTER TABLE RK_TH_PRM ADD ID_STR_RT VARCHAR2(128);

ALTER TABLE RU_PRDV ADD IS_DISCOUNT CHAR(1);

ALTER TABLE PA_EM ADD CONSTRAINT ARM_EXTERNAL_ID_UNIQ UNIQUE (ARM_EXTERNAL_ID);

