ALTER TABLE PA_STR_RTL ADD MESSAGE VARCHAR2(256);

ALTER TABLE TR_LTM_CRDB_CRD_TN ADD PLAN_CODE VARCHAR2(50);

CREATE TABLE ARM_PAY_PLAN (
	CRD_PLAN_CODE VARCHAR2(10) NOT NULL,
	CRD_PLAN_DESC VARCHAR2(255)
);
 
ALTER TABLE ARM_PAY_PLAN ADD PRIMARY KEY (CRD_PLAN_CODE); 

CREATE TABLE ARM_GRP_CLS_TND_PLAN (
	TND_CODE VARCHAR2(10) NOT NULL,
	ED_CO VARCHAR2(20) NOT NULL,
	ED_LA VARCHAR2(20) NOT NULL,
	CRD_PLAN_CODE VARCHAR2(20) NULL
);
 
ALTER TABLE ARM_GRP_CLS_TND_PLAN ADD PRIMARY KEY(TND_CODE,ED_CO,ED_LA,CRD_PLAN_CODE);

ALTER TABLE ARM_GRP_CLS_TND ADD PRIMARY KEY(TND_CODE,ED_CO,ED_LA);
 
ALTER TABLE ARM_GRP_CLS_TND_PLAN
ADD ( FOREIGN KEY (TND_CODE,ED_CO,ED_LA)
REFERENCES ARM_GRP_CLS_TND) ;

ALTER TABLE ARM_GRP_CLS_TND_PLAN
ADD FOREIGN KEY (CRD_PLAN_CODE) REFERENCES ARM_PAY_PLAN(CRD_PLAN_CODE);
 
CREATE OR REPLACE VIEW V_ARM_GRP_PAY_PLAN 
(TND_CODE, CRD_PLAN_CODE, ED_CO, ED_LA, DE_CRD_PLAN ) 
AS 
SELECT ARM_GRP_CLS_TND_PLAN.TND_CODE, ARM_GRP_CLS_TND_PLAN.CRD_PLAN_CODE, 
	ARM_GRP_CLS_TND_PLAN.ED_CO, ARM_GRP_CLS_TND_PLAN.ED_LA, ARM_PAY_PLAN.CRD_PLAN_DESC  
FROM ARM_GRP_CLS_TND_PLAN INNER JOIN ARM_PAY_PLAN 
	ON ARM_GRP_CLS_TND_PLAN.CRD_PLAN_CODE=ARM_PAY_PLAN.CRD_PLAN_CODE;

CREATE OR REPLACE VIEW V_ARM_TXN_HDR
(CUST_ID, TY_TRN, PAY_TRN_TYPE, ID_STR_RT, ID_OPR, 
 TS_TRN_PRC, TS_TRN_SBM, TY_GUI_TRN, PAY_TYPES, TOTAL_AMT, 
 AI_TRN, CONSULTANT_ID, REDUCTION_AMOUNT, NET_AMOUNT, DISCOUNT_TYPES, 
 ITEMS_IDS, REGISTER_ID, FN_PRS, LN_PRS, EXP_DT, 
 REF_ID, VOID_ID, CUST_FIRST_NAME, CUST_LAST_NAME)
AS 
SELECT RK_PAY_TRN.CUST_ID, TR_TRN.TY_TRN, RK_PAY_TRN.TYPE_ID PAY_TRN_TYPE, TR_TRN.ID_STR_RT,  
TR_TRN.ID_OPR, TR_TRN.TS_TRN_PRC, TR_TRN.TS_TRN_SBM,  
TR_TRN.TY_GUI_TRN, RK_PAY_TRN.PAY_TYPES, RK_PAY_TRN.TOTAL_AMT,  
RK_PAY_TRN.AI_TRN, PA_EM.ARM_EXTERNAL_ID CONSULTANT_ID, TR_RTL.REDUCTION_AMOUNT,  
TR_RTL.NET_AMOUNT, TR_RTL.DISCOUNT_TYPES, TR_RTL.ITEMS_IDS,  
TR_RTL.REGISTER_ID, PA_PRS.FN_PRS, PA_PRS.LN_PRS,  
ARM_POS_PRS.EXP_DT, ARM_POS_PRS.ID_PRESALE REF_ID, TR_TRN.ID_VOID,  
CUSTOMER.FN_PRS CUST_FIRST_NAME,CUSTOMER.LN_PRS CUST_LAST_NAME  
FROM TR_TRN INNER JOIN  
(  
	RK_PAY_TRN INNER JOIN  
	(  
		TR_RTL INNER JOIN ARM_POS_PRS ON TR_RTL.AI_TRN=ARM_POS_PRS.AI_TRN  
		LEFT OUTER JOIN PA_PRS ON TR_RTL.CONSULTANT_ID=PA_PRS.ID_PRTY_PRS  
		LEFT OUTER JOIN PA_PRS CUSTOMER ON TR_RTL.ID_CT = CUSTOMER.ID_PRTY_PRS  
		LEFT OUTER JOIN PA_EM ON TR_RTL.CONSULTANT_ID=PA_EM.ID_EM  
		INNER JOIN (SELECT AI_TRN, COUNT(*) FROM RK_POS_LN_ITM_DTL WHERE NVL(FL_PROCESSED,'0') IN ('0') GROUP BY AI_TRN   HAVING COUNT(*) > 0) LN_ITM_DTL  
		ON TR_RTL.AI_TRN = LN_ITM_DTL.AI_TRN  
	)  
	ON RK_PAY_TRN.AI_TRN = TR_RTL.AI_TRN  
)  
ON TR_TRN.AI_TRN = RK_PAY_TRN.AI_TRN  
UNION ALL  
SELECT RK_PAY_TRN.CUST_ID, TR_TRN.TY_TRN, RK_PAY_TRN.TYPE_ID PAY_TRN_TYPE, TR_TRN.ID_STR_RT,  
TR_TRN.ID_OPR, TR_TRN.TS_TRN_PRC, TR_TRN.TS_TRN_SBM,  
TR_TRN.TY_GUI_TRN, RK_PAY_TRN.PAY_TYPES, RK_PAY_TRN.TOTAL_AMT,  
RK_PAY_TRN.AI_TRN, PA_EM.ARM_EXTERNAL_ID CONSULTANT_ID, TR_RTL.REDUCTION_AMOUNT,  
TR_RTL.NET_AMOUNT, TR_RTL.DISCOUNT_TYPES, TR_RTL.ITEMS_IDS,  
TR_RTL.REGISTER_ID, PA_PRS.FN_PRS, PA_PRS.LN_PRS,  
ARM_POS_CSG.EXP_DT, ARM_POS_CSG.ID_CONSIGNMENT REF_ID, TR_TRN.ID_VOID,  
CUSTOMER.FN_PRS CUST_FIRST_NAME,CUSTOMER.LN_PRS CUST_LAST_NAME  
FROM TR_TRN INNER JOIN  
(  
	RK_PAY_TRN INNER JOIN  
	(  
		TR_RTL INNER JOIN ARM_POS_CSG ON TR_RTL.AI_TRN=ARM_POS_CSG.AI_TRN  
		LEFT OUTER JOIN PA_PRS CUSTOMER ON TR_RTL.ID_CT = CUSTOMER.ID_PRTY_PRS  
		LEFT OUTER JOIN PA_PRS ON TR_RTL.CONSULTANT_ID=PA_PRS.ID_PRTY_PRS  
		LEFT OUTER JOIN PA_EM ON TR_RTL.CONSULTANT_ID=PA_EM.ID_EM  
		INNER JOIN (SELECT AI_TRN, COUNT(*) FROM RK_POS_LN_ITM_DTL WHERE NVL(FL_PROCESSED,'0') IN ('0') GROUP BY AI_TRN   HAVING COUNT(*) > 0) LN_ITM_DTL  
		ON TR_RTL.AI_TRN = LN_ITM_DTL.AI_TRN  
	)  
	ON RK_PAY_TRN.AI_TRN = TR_RTL.AI_TRN  
)  
ON TR_TRN.AI_TRN = RK_PAY_TRN.AI_TRN  
UNION ALL  
SELECT RK_PAY_TRN.CUST_ID, TR_TRN.TY_TRN, RK_PAY_TRN.TYPE_ID PAY_TRN_TYPE, TR_TRN.ID_STR_RT,  
TR_TRN.ID_OPR, TR_TRN.TS_TRN_PRC, TR_TRN.TS_TRN_SBM,  
TR_TRN.TY_GUI_TRN, RK_PAY_TRN.PAY_TYPES, RK_PAY_TRN.TOTAL_AMT,  
RK_PAY_TRN.AI_TRN, PA_EM.ARM_EXTERNAL_ID CONSULTANT_ID, TR_RTL.REDUCTION_AMOUNT,  
TR_RTL.NET_AMOUNT, TR_RTL.DISCOUNT_TYPES, TR_RTL.ITEMS_IDS,  
TR_RTL.REGISTER_ID, PA_PRS.FN_PRS, PA_PRS.LN_PRS,  
ARM_POS_RSV.EXP_DT, ARM_POS_RSV.ID_RESERVATION REF_ID, TR_TRN.ID_VOID,  
CUSTOMER.FN_PRS CUST_FIRST_NAME,CUSTOMER.LN_PRS CUST_LAST_NAME  
FROM TR_TRN INNER JOIN  
(  
	RK_PAY_TRN INNER JOIN  
	(  
		TR_RTL INNER JOIN ARM_POS_RSV ON TR_RTL.AI_TRN=ARM_POS_RSV.AI_TRN  
		LEFT OUTER JOIN PA_PRS CUSTOMER ON TR_RTL.ID_CT = CUSTOMER.ID_PRTY_PRS  
		LEFT OUTER JOIN PA_PRS ON TR_RTL.CONSULTANT_ID=PA_PRS.ID_PRTY_PRS  
		LEFT OUTER JOIN PA_EM ON TR_RTL.CONSULTANT_ID=PA_EM.ID_EM  
		INNER JOIN (SELECT RK_POS_LN_ITM_DTL.AI_TRN, COUNT(*) FROM RK_POS_LN_ITM_DTL INNER JOIN TR_LTM_RTL_TRN  
		ON RK_POS_LN_ITM_DTL.AI_TRN = TR_LTM_RTL_TRN.AI_TRN  
		AND RK_POS_LN_ITM_DTL.AI_LN_ITM = TR_LTM_RTL_TRN.AI_LN_ITM  
		WHERE NVL(FL_PROCESSED,'0') IN ('0') AND TR_LTM_RTL_TRN.POS_LN_ITM_TY_ID IN ('6') GROUP BY RK_POS_LN_ITM_DTL.AI_TRN   HAVING COUNT(*) > 0) LN_ITM_DTL  
		ON TR_RTL.AI_TRN = LN_ITM_DTL.AI_TRN  
	)  
	ON RK_PAY_TRN.AI_TRN = TR_RTL.AI_TRN  
)  
ON TR_TRN.AI_TRN = RK_PAY_TRN.AI_TRN;

ALTER TABLE PA_PRS
MODIFY (DB_FN_PRS	VARCHAR2(60),
	DB_LN_PRS	VARCHAR2(60));

ALTER TABLE LO_ADS_NSTD
MODIFY (A1_ADS		VARCHAR2(60),
	A2_ADS		VARCHAR2(60));
