ALTER TABLE AS_ITM
ADD  ( PRIMARY KEY (ID_ITM) ) ;

ALTER TABLE AS_ITM_BLK
ADD  ( PRIMARY KEY (ID_ITM) ) ;

ALTER TABLE AS_ITM_RTL_STR
ADD  ( PRIMARY KEY (ID_ITM, CURRENCY_CODE) ) ;

ALTER TABLE AS_ITM_STK
ADD  ( PRIMARY KEY (ID_ITM) ) ;

ALTER TABLE AS_TL
ADD  ( PRIMARY KEY (ID_RPSTY_TND, ID_STR_RT) ) ;

ALTER TABLE AS_TR
ADD  ( PRIMARY KEY (ID_TR_BLK_ITM, ID_ITM) ) ;

ALTER TABLE CO_ACS_PSWD
ADD  ( PRIMARY KEY (ID_OPR, ID_STR_RT) ) ;

ALTER TABLE CO_ASCTN_RLTD_ITM
ADD  ( PRIMARY KEY (ID_ITM, ID_ITM_RLTD) ) ;

ALTER TABLE CO_CFG
ADD  ( PRIMARY KEY (ID_CFG) ) ;

ALTER TABLE CO_CFG_BTTN
ADD  ( PRIMARY KEY (ID_BTTN, ID_CFG) ) ;

ALTER TABLE CO_CFG_CPN
ADD  ( PRIMARY KEY (ID_CPN, ID_CFG) ) ;

ALTER TABLE CO_CFG_MNY_ORD
ADD  ( PRIMARY KEY (ID_MNY_ORD, ID_CFG) ) ;

ALTER TABLE CO_CFG_PDT_RST
ADD  ( PRIMARY KEY (ID_PDT_RST, ID_CFG) ) ;

ALTER TABLE CO_CFG_PY_IN_OT
ADD  ( PRIMARY KEY (ID_PY_IN_OT, ID_CFG) ) ;

ALTER TABLE CO_CFG_SPR_PY_TYP
ADD  ( PRIMARY KEY (ID_SPR_PY_TYP, ID_CFG) ) ;

ALTER TABLE CO_CFG_TND_TYP
ADD  ( PRIMARY KEY (ID_TND_TYP, ID_CFG) ) ;

ALTER TABLE CO_CLS_GF_CF
ADD  ( PRIMARY KEY (TY_GF_CF) ) ;

ALTER TABLE CO_CLS_TND
ADD  ( PRIMARY KEY (LU_CLS_TND) ) ;

ALTER TABLE CO_CTAF
ADD  ( PRIMARY KEY (ID_CT, ID_GP_ID) ) ;

ALTER TABLE CO_EV
ADD  ( PRIMARY KEY (ID_STR_RT, ID_EV) ) ;

ALTER TABLE CO_EV_MNT
ADD  ( PRIMARY KEY (ID_STR_RT, ID_EV) ) ;

ALTER TABLE CO_ITM_CFG
ADD  ( PRIMARY KEY (ID_ITM_CFG) ) ;

ALTER TABLE CO_MNT_ITM
ADD  ( PRIMARY KEY (ID_STR_RT, ID_EV) ) ;

ALTER TABLE CO_PLN_EM_CMN
ADD  ( PRIMARY KEY (ID_PLN_EM_CMN) ) ;

ALTER TABLE CO_PRM
ADD  ( PRIMARY KEY (ID_PRM) ) ;

ALTER TABLE CO_PST
ADD  ( PRIMARY KEY (ID_PST) ) ;

ALTER TABLE CO_STR_CFG
ADD  ( PRIMARY KEY (ID_STR_CFG) ) ;

ALTER TABLE CO_TH_MPR_UN
ADD  ( PRIMARY KEY (ID_LV_TH, ID_ITM, QU_CNT_UN) ) ;

ALTER TABLE CO_TYP_TRN
ADD  ( PRIMARY KEY (TY_TRN) ) ;

ALTER TABLE CO_UOM
ADD  ( PRIMARY KEY (LU_UOM) ) ;

ALTER TABLE DO_CF_GF
ADD  ( PRIMARY KEY (ID_NMB_SRZ_GF_CF, TY_GF_CF) ) ;

ALTER TABLE ID_DPT_PS
ADD  ( PRIMARY KEY (ID_DPT_POS) ) ;

ALTER TABLE ID_IDN_PS
ADD  ( PRIMARY KEY (ID_ITM_POS) ) ;

ALTER TABLE LE_ACNT_STR_FN
ADD  ( PRIMARY KEY (ID_STR_RT, ID_ACNT_LDG) ) ;

ALTER TABLE LE_HST_ITM_SLS_PRC
ADD  ( PRIMARY KEY (AI_PRC_RT) ) ;

ALTER TABLE LE_PRC_SPL_CT_TYP
ADD  ( PRIMARY KEY (ID_GP_ID, ID_ITM, CURRENCY_CODE) ) ;

ALTER TABLE LO_ADS
ADD  ( PRIMARY KEY (ID_ADS) ) ;

ALTER TABLE LO_ADS_LCN_PHY
ADD  ( PRIMARY KEY (CD_LCN_PHY, TY_CRDN, ID_ADS) ) ;

ALTER TABLE LO_ADS_NSTD
ADD  ( PRIMARY KEY (ID_ADS) ) ;

ALTER TABLE LO_ADS_PRTY
ADD  ( PRIMARY KEY (ID_ADS, ID_PRTY, TY_RO_PRTY) ) ;

ALTER TABLE LO_CRDN_TYP
ADD  ( PRIMARY KEY (TY_CRDN) ) ;

ALTER TABLE LO_EML_ADS
ADD  ( PRIMARY KEY (EM_ADS, ID_PRTY) ) ;

ALTER TABLE LO_LCN_PHY
ADD  ( PRIMARY KEY (TY_CRDN, CD_LCN_PHY) ) ;

ALTER TABLE LO_PH
ADD  ( PRIMARY KEY (ID_PRTY, ID_PH_TYP) ) ;

ALTER TABLE LO_PH_TYP
ADD  ( PRIMARY KEY (ID_PH_TYP) ) ;

ALTER TABLE MA_CRT_ITM
ADD  ( PRIMARY KEY (ID_EV, ID_STR_RT) ) ;

ALTER TABLE MA_DLT_ITM
ADD  ( PRIMARY KEY (ID_EV, ID_STR_RT) ) ;

ALTER TABLE MA_ITM_PRN_PRC_ITM
ADD  ( PRIMARY KEY (ID_STR_RT, ID_EV) ) ;

ALTER TABLE MA_ITM_TMP_PRC_CHN
ADD  ( PRIMARY KEY (ID_STR_RT, ID_EV) ) ;

ALTER TABLE MA_PRC_ITM
ADD  ( PRIMARY KEY (ID_EV, ID_STR_RT) ) ;

ALTER TABLE MA_UPDT_ITM_DSCR
ADD  ( PRIMARY KEY (ID_EV, ID_STR_RT) ) ;

ALTER TABLE PA_CT
ADD  ( PRIMARY KEY (ID_CT) ) ;

ALTER TABLE PA_EM
ADD  ( PRIMARY KEY (ID_EM) ) ;

ALTER TABLE PA_GP_CT
ADD  ( PRIMARY KEY (ID_GP_ID) ) ;

ALTER TABLE PA_KY_CT
ADD  ( PRIMARY KEY (ID_CT) ) ;

ALTER TABLE PA_OPR
ADD  ( PRIMARY KEY (ID_STR_RT, ID_OPR) ) ;

ALTER TABLE PA_ORGN
ADD  ( PRIMARY KEY (ID_PRTY_ORGN) ) ;

ALTER TABLE PA_PRS
ADD  ( PRIMARY KEY (ID_PRTY_PRS) ) ;

ALTER TABLE PA_PRTY
ADD  ( PRIMARY KEY (ID_PRTY) ) ;

ALTER TABLE PA_RO_PRTY
ADD  ( PRIMARY KEY (ID_PRTY, TY_RO_PRTY) ) ;

ALTER TABLE PA_RO_PRTY_TYP
ADD  ( PRIMARY KEY (TY_RO_PRTY) ) ;

ALTER TABLE PA_STR_RTL
ADD  ( PRIMARY KEY (ID_STR_RT) ) ;

ALTER TABLE RK_COLLECTION
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_COMP_PRM_PK
ADD  ( PRIMARY KEY (ID_RU_PRDV, ID_ITM, CURRENCY_CODE,
COMP_NUM) ) ;

ALTER TABLE RK_EMP_APP_FORM
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_EMP_FORM
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_EMP_GL_CH_DT
ADD  ( PRIMARY KEY (SEQ_NUM, ID_EM, ID_STR_RT) ) ;

ALTER TABLE RK_EMP_GOAL
ADD  ( PRIMARY KEY (ID_EM, ID_STR_RT) ) ;

ALTER TABLE RK_EMP_HISTORY
ADD  ( PRIMARY KEY (FORM_ID, SEQ_NUM) ) ;

ALTER TABLE RK_EMP_REFERENCE
ADD  ( PRIMARY KEY (FORM_ID, SEQ_NUM) ) ;

ALTER TABLE RK_EMP_RSC
ADD  ( PRIMARY KEY (EMPLOYEE_ID) ) ;

ALTER TABLE RK_EMP_RSC_ROL
ADD  ( PRIMARY KEY (TYPE_ID, SEQ_NUM, EMPLOYEE_ID) ) ;

ALTER TABLE RK_EMP_RSC_ROL_TY
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_EMP_STATUS
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_EMP_TIMECARD
ADD  ( PRIMARY KEY (WEEK_ENDING, ID_EM) ) ;

ALTER TABLE RK_EOD
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_FORM_TYPE
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_I9_FORM
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_ID_DOC
ADD  ( PRIMARY KEY (FORM_ID, TYPE_ID) ) ;

ALTER TABLE RK_ID_DOC_TYPE
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_LAY
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_LAY_PAY
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_LAY_PAY_INFO
ADD  ( PRIMARY KEY (ID, SEQUENCE_NUMBER) ) ;

ALTER TABLE RK_LAY_RTS
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_LOT
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_LOT_TRN
ADD  ( PRIMARY KEY (LOT_ID, TRANSACTION_ID) ) ;

ALTER TABLE RK_NO_SALE
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_PAID_OUT
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_PAY_SUM
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_PAY_TRN
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_POS_LAY
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_POS_LN_ITM_DTL
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM, SEQUENCE_NUMBER) ) ;

ALTER TABLE RK_POS_LN_ITM_TYP
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_PRM_IT
ADD  ( PRIMARY KEY (ID_RU_PRDV, CURRENCY_CODE) ) ;

ALTER TABLE RK_PRM_ITM
ADD  ( PRIMARY KEY (ID_ITM, CURRENCY_CODE, ID_RU_PRDV) ) ;

ALTER TABLE RK_PRM_MB
ADD  ( PRIMARY KEY (ID_RU_PRDV, CURRENCY_CODE, SEQ_NUM) ) ;

ALTER TABLE RK_PRM_MU
ADD  ( PRIMARY KEY (ID_RU_PRDV) ) ;

ALTER TABLE RK_PRM_PK
ADD  ( PRIMARY KEY (ID_RU_PRDV) ) ;

ALTER TABLE RK_PRM_PK_AMT
ADD  ( PRIMARY KEY (ID_RU_PRDV, SEQ_NUM, CURRENCY_CODE) ) ;

ALTER TABLE RK_PRM_PK_PE
ADD  ( PRIMARY KEY (ID_RU_PRDV, SEQ_NUM) ) ;

ALTER TABLE RK_REDM_BYBK
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_REDM_HIST
ADD  ( PRIMARY KEY (SEQ_NUM, ID_NMB_SRZ_GF_CF, TY_GF_CF) ) ;

ALTER TABLE RK_RELATED_EMP
ADD  ( PRIMARY KEY (FORM_ID, SEQ_NUM) ) ;

ALTER TABLE RK_ROLE
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_SALES_SUMMARY
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_SCHEDULE
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_SHIFT
ADD  ( PRIMARY KEY (SCHEDULE_ID, SEQ_NUM) ) ;

ALTER TABLE RK_SHIP_REQ
ADD  ( PRIMARY KEY (SEQ_NUM, AI_TRN) ) ;

ALTER TABLE RK_SOS
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_STR_GL_CHG_DATE
ADD  ( PRIMARY KEY (SEQ_NUM, ID_STR_RT) ) ;

ALTER TABLE RK_STR_GOAL
ADD  ( PRIMARY KEY (ID_STR_RT) ) ;

ALTER TABLE RK_TH_PRM
ADD  ( PRIMARY KEY (ID, CURRENCY_CODE) ) ;

ALTER TABLE RK_TIMECARD
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_TIMECARD_BEN
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_TIMECARD_MOD
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_TIME_RANGE
ADD  ( PRIMARY KEY (TYPE_ID, SEQ_NUM, EMPLOYEE_ID) ) ;

ALTER TABLE RK_TIME_RANGE_TYPE
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_TRANSFER
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_TRANSFER_IN
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_TRANSFER_LN_ITM
ADD  ( PRIMARY KEY (SEQ_NUM, TRANSFER_ID) ) ;

ALTER TABLE RK_TRANSFER_OUT
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_TXN_TY_SUM
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_VAC_REQ_DATE
ADD  ( PRIMARY KEY (FORM_ID, SEQ_NUM) ) ;

ALTER TABLE RK_VAC_REQ_FORM
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RK_VOID_TRANSFER
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_VOID_TRN
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE RK_W4_FORM
ADD  ( PRIMARY KEY (ID) ) ;

ALTER TABLE RU_DS
ADD  ( PRIMARY KEY (ID_ITM) ) ;

ALTER TABLE RU_PRDV
ADD  ( PRIMARY KEY (ID_RU_PRDV) ) ;

ALTER TABLE RU_PRDV_ITM
ADD  ( PRIMARY KEY (ID_RU_PRDV, CURRENCY_CODE) ) ;

ALTER TABLE RU_PRM_PRDV
ADD  ( PRIMARY KEY (ID_PRM, ID_RU_PRDV) ) ;

ALTER TABLE ST_ASGMT_EM_STR
ADD  ( PRIMARY KEY (ID_EM, ID_STR_RT, SC_ASGMT_STR) ) ;

ALTER TABLE ST_EM_ASGMT
ADD  ( PRIMARY KEY (ID_EM, ID_PST) ) ;

ALTER TABLE ST_JOB
ADD  ( PRIMARY KEY (CD_JOB) ) ;

ALTER TABLE ST_ORGN_STRC
ADD  ( PRIMARY KEY (ID_PRTY_ORGN_PRNT) ) ;

ALTER TABLE TR_CHN_PRN_PRC
ADD  ( PRIMARY KEY (ID_EV, ID_STR_RT) ) ;

ALTER TABLE TR_CHN_TMP_PRC
ADD  ( PRIMARY KEY (ID_EV, ID_STR_RT) ) ;

ALTER TABLE TR_DSC
ADD  ( PRIMARY KEY (TY_DSC) ) ;

ALTER TABLE TR_LTM_CHK_TND
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_CPN_TND
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_CRDB_CRD_TN
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_DSC
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_EM__DSC
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_GF_CF
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_GF_CF_TND
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_RTL_TRN
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_SLS_RTN
ADD  ( PRIMARY KEY (ID_WS, DC_DY_BSN, AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_LTM_TND
ADD  ( PRIMARY KEY (AI_TRN, AI_LN_ITM) ) ;

ALTER TABLE TR_RTL
ADD  ( PRIMARY KEY (AI_TRN) ) ;

ALTER TABLE TR_TRN
ADD  ( PRIMARY KEY (AI_TRN) ) ;

