INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','HOME','IT','it','Home',0);

INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','SECR','IT','it','Secondary Home',1);

INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','WORK','IT','it','Work',2);

INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','VACA','IT','it','Vaccation Home',3);

INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','DORM','IT','it','Dorm',4);


INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','1','IT','it','Home',2);

INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','2','IT','it','Cellular',1);

INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','3','IT','it','Office',3);

INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','4','IT','it','Alternate',4);

INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','5','IT','it','Fax',5);


INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','1','IT','it',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','2','IT','it','Preferred',1);

INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','3','IT','it','Premio',2);

INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','4','IT','it','VIP',3);

INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','5','IT','it','Employee',4);


INSERT INTO ARM_CFG_DETAIL VALUES('GENDER','1','IT','it',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('GENDER','2','IT','it','Male',1);

INSERT INTO ARM_CFG_DETAIL VALUES('GENDER','3','IT','it','Female',2);


INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','1','IT','it',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','2','IT','it','Executive',1);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','3','IT','it','Finance',2);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','4','IT','it','Media/Publishing',3);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','5','IT','it','Healthcare',4);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','6','IT','it','Sales',5);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','7','IT','it','Technology/IT',6);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','8','IT','it','Education',7);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','9','IT','it','Other',8);


INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','1','IT','it',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','2','IT','it','Graduate',1);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','3','IT','it','College',2);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','4','IT','it','Some College',3);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','5','IT','it','High School',4);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','6','IT','it','Other',5);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','1','IT','it',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','2','IT','it','Birthday',1);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','3','IT','it','Anniversary',2);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','4','IT','it','Baby Arrival',3);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','5','IT','it','ReligioIT Event',4);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','6','IT','it','Other',4);


INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','0','IT','it','AITtria',0);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','1','IT','it','Belgium',1);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','2','IT','it','CyprIT',2);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','3','IT','it','Czech Republic',3);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','4','IT','it','Denmark',4);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','5','IT','it','Others',5);

INSERT INTO ARM_CFG_DETAIL VALUES('POST_VOID_REASON_CD','1','IT','it','Wrong Tender',0);

INSERT INTO ARM_CFG_DETAIL VALUES('POST_VOID_REASON_CD','2','IT','it','CITtomer Changed Mind',1);

INSERT INTO ARM_CFG_DETAIL VALUES('POST_VOID_REASON_CD','3','IT','it','Entry Error',2);


INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','01','IT','it','PUBLIC RELATIONS',0);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','02','IT','it','PROMOTION',1);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','03','IT','it','PREMIO',2);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','04','IT','it','VIP',3);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','05','IT','it','OTHER',4);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','06','IT','it','EMPLOYEE DISCOUNT',5);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','07','IT','it','FRIENDS AND FAMILY',6);


INSERT INTO ARM_CFG_DETAIL VALUES('NO_SL_REASON_CD','1','IT','it','CITtomer Change',1);

INSERT INTO ARM_CFG_DETAIL VALUES('NO_SL_REASON_CD','2','IT','it','Cash Pick-Up',2);

INSERT INTO ARM_CFG_DETAIL VALUES('NO_SL_REASON_CD','3','IT','it','LP Audit',3);


INSERT INTO ARM_CFG_DETAIL VALUES('PRICE_OVERRIDE_REASON_CD','1','IT','it','Wrong Marked Price',1);

INSERT INTO ARM_CFG_DETAIL VALUES('PRICE_OVERRIDE_REASON_CD','2','IT','it','Sale',2);

INSERT INTO ARM_CFG_DETAIL VALUES('PRICE_OVERRIDE_REASON_CD','3','IT','it','Other',3);

