INSERT INTO ST_JOB(CD_JOB,NM_JOB,DE_JOB) VALUES('0000','UNDECLARED','UNDECLARED');

INSERT INTO TR_DSC ( TY_DSC, ID_STR_RT, ID_ACNT_LDG, NM_DSC, DE_DSC, CD_RDN_MTH, MO_RDN_AMT,
PE_RDN_AMT, MO_NW_PRC ) VALUES ( 'RD', NULL, NULL, 'REWARD DISCOUNT', 'REWARD DISCOUNT', NULL, '0', 0, '0');

INSERT INTO CO_CLS_GF_CF ( TY_GF_CF, ID_STR_RT, ID_ACNT_LDG, DE_TYP_GF_CF, NM_AF_BSN_GF_CF, QU_DY_RDM_PRD, ID_FRM_GF_CF, DP_BLNC_UNSP_GF_CF ) VALUES ( 
'HOUSE_ACCOUNT', NULL, NULL, 'HOUSE_ACCOUNT', NULL, 0, NULL, NULL); 

INSERT INTO CO_CLS_TND (LU_CLS_TND, DE_CLS_TND) values ('HOUSE_ACCOUNT', 'HOUSE_ACCOUNT');
INSERT INTO CO_CLS_TND (LU_CLS_TND, DE_CLS_TND) values ('JCB', 'JCB');
INSERT INTO CO_CLS_TND (LU_CLS_TND, DE_CLS_TND) values ('DINERS', 'DINERS');
INSERT INTO CO_CLS_TND (LU_CLS_TND, DE_CLS_TND) values ('JPY_CASH', 'JPY_CASH');
INSERT INTO CO_CLS_TND (LU_CLS_TND, DE_CLS_TND) values ('COUPON', 'COUPON');
INSERT INTO CO_CLS_TND (LU_CLS_TND, DE_CLS_TND) values ('MAIL_CHECK', 'MAIL_CHECK');
INSERT INTO CO_CLS_TND (LU_CLS_TND, DE_CLS_TND) values ('MALL_CERTIFICATE', 'MALL_CERTIFICATE');
INSERT INTO CO_CLS_TND ( LU_CLS_TND, DE_CLS_TND ) VALUES ('OUT_OF_AREA_CHECK', 'OUT_OF_AREA_CHECK'); 
INSERT INTO CO_CLS_TND ( LU_CLS_TND, DE_CLS_TND ) VALUES ('LOCAL_CHECK', 'LOCAL_CHECK'); 
INSERT INTO CO_CLS_TND ( LU_CLS_TND, DE_CLS_TND ) VALUES ('ROUND_PAYMENT', 'ROUND_PAYMENT'); 
INSERT INTO CO_CLS_TND ( LU_CLS_TND, DE_CLS_TND ) VALUES ('MONETA', 'MONETA');


INSERT INTO RK_POS_LN_ITM_TYP ( ID, DESCRIPTION ) VALUES (4, 'PRESALE');
INSERT INTO RK_POS_LN_ITM_TYP ( ID, DESCRIPTION ) VALUES (5, 'CONSIGNMENT'); 
INSERT INTO RK_POS_LN_ITM_TYP (ID, DESCRIPTION) values (6, 'RESERVATION');
INSERT INTO RK_POS_LN_ITM_TYP (ID, DESCRIPTION) values (7, 'VOID');

INSERT INTO CO_TYP_TRN ( TY_TRN, ID_RS ) VALUES ('TRNPSO', '170'); 
INSERT INTO CO_TYP_TRN ( TY_TRN, ID_RS ) VALUES ('TRNCGO', '180'); 


insert into CO_CLS_GF_CF(TY_GF_CF, ID_STR_RT, ID_ACNT_LDG, DE_TYP_GF_CF, NM_AF_BSN_GF_CF, QU_DY_RDM_PRD, ID_FRM_GF_CF, DP_BLNC_UNSP_GF_CF)
values('REWARD_CARD', null, null, 'REWARD_CARD', null, 0, null, null);

insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1011', 'CASHIER');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1012', 'TECHNICAL SUPPORT');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1013', 'NON STORE ASSOCIATE');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1014', 'TAILOR');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1015', 'FITTER');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1001', 'MANAGER LEVEL 1');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1004', 'SALES LEVEL 1');

INSERT INTO ARM_EOD_GROUP(CD_GROUP,DE_GROUP) VALUES('TND','EOD - Tender Details');
INSERT INTO ARM_EOD_GROUP(CD_GROUP,DE_GROUP) VALUES('TXN','EOD - Transaction Details');
INSERT INTO ARM_EOD_GROUP(CD_GROUP,DE_GROUP) VALUES('TAX','EOD - Tax Details');



