ALTER TABLE ARM_STG_TXN_HDR
MODIFY (REDUCTION_AMOUNT NUMBER(10,2),
	NET_AMOUNT NUMBER(10,2)
);

ALTER TABLE ARM_STG_TXN_DTL
MODIFY (ITM_RTL_PRICE		NUMBER(10,2),
	ITM_SEL_PRICE		NUMBER(10,2),
	MANUAL_MD_AMT		NUMBER(10,2),
	MANUAL_UNIT_PRICE	NUMBER(10,2),
	NET_AMT			NUMBER(10,2),
	TAX_AMT			NUMBER(10,2),
	DEAL_MKDN_AMT		NUMBER(10,2),
	REDUCTION_AMOUNT	NUMBER(10,2),
	DSC_AMOUNT		NUMBER(10,2),
	TND_AMOUNT		NUMBER(10,2),
	FC_XCHANGE_RATE		NUMBER(10,2),
	RDM_FACE_VALUE_AMT	NUMBER(10,2),
	RDM_BALANCE_AMT		NUMBER(10,2),
	RDM_BUYBACK_AMT		NUMBER(10,2),
	OPENING_DRWR_FND	NUMBER(10,2)
);

ALTER TABLE ARM_STG_CUST_IN
MODIFY (DBYTE_FIRST_NM	VARCHAR2(60),
	DBYTE_LAST_NM	VARCHAR2(60),
	ADDRESS_LINE_1	VARCHAR2(60),
	ADDRESS_LINE_2	VARCHAR2(60));

ALTER TABLE ARM_STG_CUST_OUT
MODIFY (DB_FIRST_NM	VARCHAR2(60),
	DB_LAST_NM	VARCHAR2(60),
	ADDRESS_LINE_1	VARCHAR2(60),
	ADDRESS_LINE_2	VARCHAR2(60));


