CREATE TABLE ARM_STG_TAX_RATE
(
  ZIP_CODE      VARCHAR2(10),
  CITY          VARCHAR2(50),
  COUNTY        VARCHAR2(50),
  STATE         VARCHAR2(10),
  TAX_RATE      NUMBER(9,4),
  EFFECTIVE_DT  DATE,
  STG_EVENT_ID        NUMBER,
  STG_STATUS          NUMBER                    DEFAULT 0,
  STG_ERROR_MESSAGE   VARCHAR2(255),
  STG_LOAD_DATE       DATE,
  STG_PROCESS_DATE    DATE
);

DROP SYNONYM &&2..ARM_STG_TAX_RATE;

CREATE SYNONYM &&2..ARM_STG_TAX_RATE FOR &&1..ARM_STG_TAX_RATE;

GRANT ALL ON  &&2..ARM_STG_TAX_RATE TO &&2;
