ALTER TABLE ARM_STG_TXN_DTL
ADD NOT_IN_FILE_SKU_DTL VARCHAR2(100);

ALTER TABLE ARM_STG_TXN_DTL
ADD (
  STATUS CHAR DEFAULT 0,
  DATA_POPULATION_DT DATE,
  EXTRACTED_DT DATE
);

ALTER TABLE ARM_STG_TXN_HDR
ADD (
  STATUS CHAR DEFAULT 0,
  DATA_POPULATION_DT DATE,
  EXTRACTED_DT DATE
);
