ALTER TABLE ARM_STG_CURRENCY_RT
ADD (COUNTRY_CD VARCHAR2(10),
LANG_CD VARCHAR2(10),
FIN_CD VARCHAR2(10));

ALTER TABLE ARM_STG_TXN_DTL
ADD (DOC_TYPE CHAR(2),
VAT_COMMENTS VARCHAR2(200));

ALTER TABLE ARM_STG_RSVO_CSGO
ADD DEPOSIT_AMT NUMBER;

ALTER TABLE ARM_STG_FISCAL_DOC
MODIFY DATE_OF_ISSUE DATE;

ALTER TABLE ARM_STG_TXN_HDR
MODIFY(ASIS_FISCAL_RECEIPT_NO VARCHAR2(50),
ASIS_FISCAL_DOC_NUM VARCHAR2(50),
ASIS_TXN_NUM VARCHAR2(50)
);