ALTER TABLE ARM_STG_CUST_IN
ADD (
    CA_STORE_ID VARCHAR2(30),
    CA_COMPANY_CODE VARCHAR2(30),
    CA_BRAND    VARCHAR2(30),
    CA_ASSOCIATE_ID VARCHAR2(30)
);

ALTER TABLE ARM_STG_TXN_DTL 
DROP (
    EOD_CASH_TOTAL,    
    EOD_CHECK_TOTAL,    
    EOD_CC_TOTAL,       
    EOD_AMEX_TOTAL,     
    EOD_DISC_TOTAL,     
    EOD_TR_CHKS_TOTAL,   
    EOD_DRWR_FND
);