WHENEVER SQLERROR CONTINUE
REM ..............................
REM Execute these as "ARMANI_ext" user
REM ..............................

DROP SYNONYM &&2..ARM_STG_TAX_FREE;
DROP SYNONYM &&2..ARM_STG_FISCAL_DOC_NO;
DROP SYNONYM &&2..ARM_STG_FISCAL_DOC;

CREATE SYNONYM &&2..ARM_STG_TAX_FREE FOR &&1..ARM_STG_TAX_FREE;

CREATE SYNONYM &&2..ARM_STG_FISCAL_DOC_NO FOR &&1..ARM_STG_FISCAL_DOC_NO;

CREATE SYNONYM &&2..ARM_STG_FISCAL_DOC FOR &&1..ARM_STG_FISCAL_DOC;


