REM ..................................
REM Execute these as "ARMANI_EXT" user
REM ..................................
DROP TABLE ARM_STG_CURRENCY_RT;

CREATE TABLE ARM_STG_CURRENCY_RT 
(
  FROM_CURRENCY  VARCHAR2 (10), 
  TO_CURRENCY    VARCHAR2 (10), 
  CURRENCY_RATE  NUMBER, 
  UPDATE_DATE    CHAR(8),
  STG_EVENT_ID       NUMBER,
  STG_STATUS         NUMBER DEFAULT 0, 
  STG_ERROR_MESSAGE  VARCHAR2 (255), 
  STG_LOAD_DATE      DATE, 
  STG_PROCESS_DATE   DATE
);

DROP TABLE ARM_STG_EMPLOYEE;

CREATE TABLE ARM_STG_EMPLOYEE 
(
  TRAN_TYPE          NUMBER (2), 
  ID                 VARCHAR2 (30), 
  FIRST_NAME         VARCHAR2 (30), 
  LAST_NAME          VARCHAR2 (30), 
  DATE_OF_BIRTH      DATE, 
  EMAIL              VARCHAR2 (30), 
  HOME_PHONE_AREA    VARCHAR2 (4), 
  HOME_PHONE_NUMBER  VARCHAR2 (10), 
  ADDRESS_LINE1      VARCHAR2 (50), 
  ADDRESS_LINE2      VARCHAR2 (50), 
  CITY               VARCHAR2 (30), 
  STATE              VARCHAR2 (30), 
  POSTAL_CODE        VARCHAR2 (30), 
  COUNTRY            VARCHAR2 (20), 
  STATUS             NUMBER, 
  HOME_STORE_ID      VARCHAR2 (30), 
  HIRE_DATE          DATE, 
  TERM_DATE          DATE, 
  ROLE               CHAR (1), 
  STG_EVENT_ID       NUMBER,
  STG_STATUS         NUMBER,
  STG_ERROR_MESSAGE  VARCHAR2 (255), 
  STG_LOAD_DATE      DATE, 
  STG_PROCESS_DATE   DATE
);

REM ..............................................
DROP TABLE ARM_STG_PRM;

CREATE TABLE ARM_STG_PRM 
(
  START_DATE         DATE,
  START_TIME         VARCHAR2(10),
  END_DATE           DATE, 
  END_TIME       VARCHAR2(10),
  STORE_ID           VARCHAR2 (10), 
  PROMOTION_NUM      VARCHAR2 (10), 
  PROMOTION_NAME     VARCHAR2(50),
  APPLY_TO           CHAR (1), 
  DISCOUNT_AMOUNT    NUMBER (20), 
  DISCOUNT_PERCENT   NUMBER (20), 
  DISCOUNT_TYPE      CHAR (1), 
  THRESHOLD_AMT      NUMBER (20), 
  IS_DISCOUNT        CHAR (1), 
  APPLICABLE_ITM     CHAR (1), 
  STG_EVENT_ID       NUMBER,
  STG_STATUS         NUMBER DEFAULT 0, 
  STG_ERROR_MESSAGE  VARCHAR2 (255), 
  STG_LOAD_DATE      DATE, 
  STG_PROCESS_DATE   DATE
);

REM ..............................................
DROP TABLE ARM_STG_REGISTER;

CREATE TABLE ARM_STG_REGISTER 
(
  COMPANY_CD         VARCHAR2 (50), 
  STORE_ID           VARCHAR2 (50), 
  REGISTER_ID        VARCHAR2 (10), 
  DESCRIPTION        VARCHAR2 (50), 
  ARROUNDING_TYPE    VARCHAR2 (10), 
  MAX_TILL_AMOUNT    NUMBER (10),
  REGISTER_TYPE      VARCHAR2(1),
  STG_EVENT_ID       NUMBER,
  STG_STATUS         NUMBER DEFAULT 0, 
  STG_ERROR_MESSAGE  VARCHAR2 (255), 
  STG_LOAD_DATE      DATE, 
  STG_PROCESS_DATE   DATE
);

REM ..............................................
DROP TABLE ARM_STG_STORE;

CREATE TABLE ARM_STG_STORE 
(
  TRAN_TYPE            NUMBER (2), 
  COMPANY_CODE         VARCHAR2 (30), 
  COMPANY_DESC         VARCHAR2(50),
  COMP_OFFICE_PHONE_AREA VARCHAR2(4),
  COMP_OFFICE_PHONE_NUMBER VARCHAR2(10),
  COMP_ADDRESS_LINE1    VARCHAR2(50),
  COMP_ADDRESS_LINE2    VARCHAR2(50),
  COMP_CITY             VARCHAR2(30),
  COMP_STATE            VARCHAR2(30),
  COMP_POSTAL_CODE      VARCHAR2(30),
  COMP_COUNTRY          VARCHAR2(20),
  SHOP_CODE             VARCHAR2(30), 
  SHOP_DESC         VARCHAR2(50),
  OFFICE_PHONE_AREA     VARCHAR2 (4), 
  OFFICE_PHONE_NUMBER   VARCHAR2 (10), 
  ADDRESS_LINE1         VARCHAR2 (50), 
  ADDRESS_LINE2         VARCHAR2 (50), 
  CITY                  VARCHAR2 (30), 
  STATE                 VARCHAR2 (30), 
  POSTAL_CODE           VARCHAR2 (30), 
  COUNTRY               VARCHAR2 (20), 
  CURRENCY              VARCHAR2 (10), 
  TAX_RATE              NUMBER (4,2), 
  COUNTRY_CODE          VARCHAR2 (5), 
  LANGUAGE_CODE         VARCHAR2 (5), 
  BRAND_ID              VARCHAR2(30),
  FRANKING_COMPANY_NAME VARCHAR2(30),
  FRANKING_COMPANY_AC_NUM VARCHAR2(30),
  FISCAL_CODE          VARCHAR2(30),
  STG_EVENT_ID         NUMBER,
  STG_STATUS           NUMBER, 
  STG_ERROR_MESSAGE    VARCHAR2 (255), 
  STG_LOAD_DATE        DATE, 
  STG_PROCESS_DATE     DATE
);

REM ..............................................
DROP TABLE ARM_OUT_STG_TIMECARD;

CREATE TABLE ARM_OUT_STG_TIMECARD 
(
  TRN_CODE           VARCHAR2 (20), 
  COMPANY_CODE       VARCHAR2 (30), 
  SHOP_CODE          VARCHAR2 (30), 
  EMP_HR_ID          VARCHAR2 (30), 
  WEEK_ENDING        VARCHAR2 (8), 
  TIMESTAMP          TIMESTAMP(6), 
  STATUS         CHAR(1),
  DATA_POPULATION_DT DATE,
  EXTRACTED_DT       DATE
);

REM ..............................................
DROP TABLE ARM_OUT_STG_TIMECARD_MODS;

CREATE TABLE ARM_OUT_STG_TIMECARD_MODS 
(
  TRN_CODE           VARCHAR2 (20), 
  COMPANY_CODE       VARCHAR2 (30), 
  SHOP_CODE          VARCHAR2 (30), 
  EMP_HR_ID          VARCHAR2 (30), 
  WEEK_ENDING        VARCHAR2 (8), 
  BF_TIMESTAMP       TIMESTAMP(6), 
  AF_TIMESTAMP       TIMESTAMP(6), 
  MOD_TIMESTAMP      TIMESTAMP(6), 
  MOD_EMP_HR_ID      VARCHAR2 (30), 
  MOD_REASON         VARCHAR2 (200), 
  STATUS         CHAR(1),
  DATA_POPULATION_DT DATE,
  EXTRACTED_DT       DATE
);

DROP SEQUENCE STG_EVENT_ID_S;

CREATE SEQUENCE STG_EVENT_ID_S;

DROP TABLE ARM_PROCESS_LOG;

CREATE TABLE ARM_PROCESS_LOG
(
  INTERFACE_KEY  VARCHAR2(20),
  START_TIME     DATE,
  END_TIME       DATE,
  STATUS         CHAR(1),
  RECORD_NUM     NUMBER,
  FILE_NAME      VARCHAR2(100)
);

DROP TABLE ARM_MISC_LOOKUP;

CREATE TABLE ARM_MISC_LOOKUP
(
  LOOKUP_TYPE   VARCHAR2(30)               NOT NULL PRIMARY KEY,
  LOOKUP_CODE   VARCHAR2(30)               NOT NULL,
  MEANING       VARCHAR2(80)               NOT NULL,
  DESCRIPTION   VARCHAR2(240),
  ENABLED_FLAG  VARCHAR2(1)                NOT NULL
);
