REM ..................................
REM Execute these as "ARMANI_EXT" user
REM ..................................

DROP TABLE ARM_STG_TAX_FREE;

CREATE TABLE ARM_STG_TAX_FREE (
    TRAN_TYPE           NUMBER(2) NOT NULL,
    STORE_CODE          VARCHAR2(20) NOT NULL,
    DETAX_CODE          VARCHAR2(50) NOT NULL,
    DESC_CODE           VARCHAR2(50),
    RATIO               NUMBER(9,2),
    START_DATE          DATE NOT NULL,
    NET_MIN_VALUE       VARCHAR2(75),
    GROSS_MIN_VALUE     VARCHAR2(75),
    PAYMENT_CODE        VARCHAR2(20),
    MIN_PRICE           VARCHAR2(75),
    MAX_PRICE           VARCHAR2(75),
    MIN_AMOUNT          VARCHAR2(75),
    MAX_AMOUNT          VARCHAR2(75),
    REFUND_AMOUNT       VARCHAR2(75),
    REFUND_PERCENT      VARCHAR2(10),
    COMMISSION          VARCHAR2(20),
    STG_EVENT_ID        NUMBER,
    STG_STATUS          NUMBER DEFAULT 0, 
    STG_ERROR_MESSAGE   VARCHAR2(255), 
    STG_LOAD_DATE       DATE, 
    STG_PROCESS_DATE    DATE
);

DROP TABLE ARM_FISCAL_DOC_NO;

CREATE TABLE ARM_STG_FISCAL_DOC_NO (
    TRAN_TYPE           NUMBER(2) NOT NULL,
    REGISTER_ID         VARCHAR2(10) NOT NULL,
    ID_STR_RT           VARCHAR2(20) NOT NULL,
    LAST_DDT_NO         VARCHAR2(20),
    LAST_VAT_NO         VARCHAR2(20),
    LAST_CREDIT_NOTE    VARCHAR2(20),
    STG_EVENT_ID        NUMBER,
    STG_STATUS          NUMBER DEFAULT 0, 
    STG_ERROR_MESSAGE   VARCHAR2(255), 
    STG_LOAD_DATE       DATE, 
    STG_PROCESS_DATE    DATE
);

DROP TABLE ARM_STG_FISCAL_DOC;

CREATE TABLE ARM_STG_FISCAL_DOC ( 
    TRANSACTION_ID     VARCHAR2 (20)  NOT NULL, 
    DOC_NUM            VARCHAR2 (10)  NOT NULL, 
    DOC_TYPE           VARCHAR2 (2)   NOT NULL, 
    COMPANY_NAME       VARCHAR2 (30)  NOT NULL, 
    COMPANY_NAME2      VARCHAR2 (30)  NOT NULL, 
    ADDRESS            VARCHAR2 (60)  NOT NULL, 
    ADDRESS_2          VARCHAR2 (60)  NOT NULL, 
    CITY               VARCHAR2 (30)  NOT NULL, 
    COUNTY             VARCHAR2 (30)  NOT NULL, 
    ZIP_CODE           VARCHAR2 (10)  NOT NULL, 
    COUNTRY            VARCHAR2 (30)  NOT NULL, 
    PRE_VAT_AMOUNT     NUMBER (9,2), 
    POST_VAT_AMOUNT    NUMBER (9,2), 
    VAT_EXEMPT_CD      VARCHAR2 (20), 
    FISCAL_CD          VARCHAR2 (20), 
    SUPP_PAYMENT_TYPE  VARCHAR2 (20), 
    VAT_NUM            VARCHAR2 (20), 
    TAX_FREE_CD        VARCHAR2 (20), 
    PAYMENT_TYPE       VARCHAR2 (20), 
    ID_TYPE            VARCHAR2 (20), 
    PLACE_OF_ISSUE     VARCHAR2 (20), 
    DATE_OF_ISSUE      VARCHAR2 (20), 
    REFUND_AMOUNT      NUMBER(9,2), 
    DESTINATION_CD     VARCHAR2 (10), 
    SENDER             VARCHAR2 (30), 
    SENDER_CD          VARCHAR2 (20), 
    CARRIER_TYPE       VARCHAR2 (20), 
    EXPEDITION_CD      VARCHAR2 (10), 
    GOODS_NUM          VARCHAR2 (20), 
    CARRIER_CD         VARCHAR2 (10), 
    CARRIER_DESC       VARCHAR2 (50), 
    PACKAGE_TYPE       VARCHAR2 (10), 
    WEIGHT             NUMBER(5,2), 
    NOTE               VARCHAR2 (100) 
 ); 
 
 ALTER TABLE ARM_STG_FISCAL_DOC ADD PRIMARY KEY (TRANSACTION_ID, DOC_NUM, DOC_TYPE);



