SELECT * FROM rk_item_vw WHERE id_str_Rt='102'

CREATE INDEX INDX_ARM_HIST ON ARM_ITM_HIST (ID_ITM,ID_STR_RT,KEY);

CREATE INDEX INDX_ARM_HIST_DT ON ARM_ITM_HIST(EFFECTIVE_DT,EXPIRATION_DT);

CREATE INDEX indx_as_itm_rtl_store ON AS_ITM_RTL_STR(id_str_rt);

SELECT * FROM ARM_ITM_HIST_NOW WHERE ID_ITM='60009997' AND ID_STR_RT='102' AND KEY='MARKDOWN'

ANALYZE TABLE ARM_ITM_HIST COMPUTE STATISTICS

-----------------------------

CREATE INDEX INDX_ARM_HIST ON ARM_ITM_HIST (ID_ITM,ID_STR_RT,KEY,EFFECTIVE_DT,EXPIRATION_DT);

ANALYZE TABLE ARM_ITM_HIST COMPUTE STATISTICS

CREATE INDEX indx_asrtl_item ON AS_ITM_RTL_STR(id_itm);

---------------------------------
SELECT/*+FIRST_ROWS*/ * FROM AS_ITM_RTL_STR  left outer join ARM_ITM_HIST  HISTORY_TABLE_RETAIL 
ON 
	(HISTORY_TABLE_RETAIL.ID_ITM=AS_ITM_RTL_STR.ID_ITM 
	AND HISTORY_TABLE_RETAIL.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT) 	
WHERE AS_ITM_RTL_STR.id_str_rt='102'


CREATE INDEX indx_as_itm_rtl_store ON AS_ITM_RTL_STR(id_str_rt);

CREATE INDEX INDX_ARM_HIST_ITM_STR ON ARM_ITM_HIST (ID_ITM,ID_STR_RT);

SELECT /*+FIRST_ROWS*/ * FROM ARM_ITM_HISt_now

CREATE OR REPLACE VIEW v_arm_itm_hist
AS
SELECT /*+FIRST_ROWS*/ * FROM ARM_ITM_HIST WHERE  KEY='RETAIL_PRICE' AND effective_dt <=SYSDATE AND NVL(expiration_dt,SYSDATE) >=SYSDATE
	
	
SELECT * FROM v_arm_itm_hist	
WHERE  id_itm='60009997' AND id_str_rt='102'
 
 DROP INDEX INDX_ARM_HIST;
 
 CREATE INDEX INDX_ARM_HIST ON ARM_ITM_HIST (KEY, effective_dt, expiration_dt);
 
 ANALYZE TABLE ARM_ITM_HIST COMPUTE STATISTICS
 
SELECT /*+FIRST_ROWS*/ * FROM ARM_ITM_HIST WHERE  KEY='RETAIL_PRICE' AND effective_dt <=SYSDATE AND NVL(expiration_dt,SYSDATE) >=SYSDATE