REM ..................................
REM Execute these as "ARMANI_Ext" user
REM ..................................
GRANT ALL ON &&2..ARM_STG_CURRENCY_RT TO &&2;

GRANT ALL ON &&2..ARM_STG_EMPLOYEE TO &&2;

GRANT ALL ON &&2..ARM_STG_PRM TO &&2;

GRANT ALL ON &&2..ARM_STG_REGISTER TO &&2;

GRANT ALL ON &&2..ARM_STG_STORE TO &&2;

GRANT ALL ON &&2..ARM_OUT_STG_TIMECARD TO &&2;

GRANT ALL ON &&2..ARM_OUT_STG_TIMECARD_MODS TO &&2;

GRANT ALL ON &&2..ARM_MISC_LOOKUP TO &&2;

GRANT ALL ON &&2..ARM_PROCESS_LOG TO &&2;

GRANT ALL ON &&2..STG_EVENT_ID_S TO &&2;

