CLEAR BUFFER
PROMPT Enter Folder (sub-direcotry) on Database Server Writable to ORACLE fpr Item Interface.
ACCEPT FOLDER CHAR PROMPT 'Folder: '
PROMPT Enter NLS Characters to be used for the interface for example ., (US) or ,. (EU)
ACCEPT NLS_CHARS CHAR PROMPT 'NLS Characters: '
MERGE INTO ARM_MISC_LOOKUP DESTINATION
USING (SELECT
'ITEM_DOWNLOAD_SUB_DIRECTORY' LOOKUP_TYPE,
'&FOLDER' FOLDER
FROM DUAL) SOURCE
ON (DESTINATION.LOOKUP_TYPE=SOURCE.LOOKUP_TYPE)
WHEN MATCHED THEN
UPDATE SET LOOKUP_CODE=TO_CHAR(FOLDER)
WHEN NOT MATCHED THEN
INSERT (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, ENABLED_FLAG)
VALUES
(SOURCE.LOOKUP_TYPE, SOURCE.FOLDER, 'Sub-Dir for item download',
'This is the write enabled sub-directory given in INIT.ORA for creating item download files',
'Y')
/
MERGE INTO ARM_MISC_LOOKUP DESTINATION
USING (SELECT
'NLS_NUMERIC_CHARACTERS' LOOKUP_TYPE,
'''' || '&NLS_CHARS' || '''' NLS_CHARS
FROM DUAL) SOURCE
ON (DESTINATION.LOOKUP_TYPE=SOURCE.LOOKUP_TYPE)
WHEN MATCHED THEN
UPDATE SET LOOKUP_CODE=TO_CHAR(NLS_CHARS)
WHEN NOT MATCHED THEN
INSERT (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, ENABLED_FLAG)
VALUES
(SOURCE.LOOKUP_TYPE, SOURCE.NLS_CHARS, 'NLS Characters for Group/Decimal',
'These are the characters used in function ARM_TO_NUMBER',
'Y')
/
MERGE INTO ARM_MISC_LOOKUP DESTINATION
USING (SELECT
'NLS_NUMBER_FORMAT' lookup_type,
'&NLS_NUMBER_FORMAT' NUMBER_FORMAT
FROM DUAL) SOURCE
ON (DESTINATION.LOOKUP_TYPE=SOURCE.LOOKUP_TYPE)
WHEN MATCHED THEN
UPDATE SET LOOKUP_CODE=TO_CHAR(NUMBER_FORMAT)
WHEN NOT MATCHED THEN
INSERT (LOOKUP_TYPE, LOOKUP_CODE, MEANING, DESCRIPTION, ENABLED_FLAG)
VALUES
(SOURCE.LOOKUP_TYPE, SOURCE.NUMBER_FORMAT,
'Number format for Group/Decimal',
'These are the characters used in function ARM_TO_NUMBER',
'Y')
/
exit
/

