ALTER TABLE ARM_STG_TXN_DTL
MODIFY (LINE_ITEM_TYPE VARCHAR2(2),
     RETURN_COMMENTS VARCHAR2(200),
     VAT_RATE NUMBER(10,5)
);

ALTER TABLE ARM_STG_TXN_HDR
MODIFY (ASIS_COMMENTS VARCHAR2(200));

ALTER TABLE ARM_STG_FISCAL_DOC
ADD FISCAL_DATE DATE;

ALTER TABLE ARM_STG_CUST_IN
MODIFY REAL_BIRTHDAY  DATE;

ALTER TABLE ARM_STG_TXN_HDR
ADD (ASIS_ORDER_NO VARCHAR2(50),
     ASIS_ORDER_DATE DATE,
     ASIS_SUPPLIER_NO VARCHAR2(50),
     ASIS_SUPPLIER_DATE DATE,
     ASIS_NOTES VARCHAR2(200)
);

ALTER TABLE ARM_MISC_LOOKUP
ADD CURRENCY_CD CHAR(3) DEFAULT 'JPY';

ALTER TABLE ARM_STG_ITEM
ADD FILE_IDENTIFIER VARCHAR2(128);

DROP SEQUENCE PURGE_TXN_SEQ;

CREATE SEQUENCE PURGE_TXN_SEQ START WITH 100 INCREMENT BY 1;

DROP TABLE ARM_TXN_PURGE_PROCESS_LOG;

CREATE TABLE ARM_TXN_PURGE_PROCESS_LOG
(
  SEQ_ID        NUMBER(7),
  TXN_ID        VARCHAR2(128),
  REF_TXN_ID    VARCHAR2(128),
  STATUS        NUMBER(1),
  LOAD_DATE     DATE,
  PROCESS_DATE  DATE
);

DROP SYNONYM &&2..ARM_TXN_PURGE_PROCESS_LOG;

CREATE SYNONYM &&2..ARM_TXN_PURGE_PROCESS_LOG FOR &&1..ARM_TXN_PURGE_PROCESS_LOG;

DROP SYNONYM &&2..PURGE_TXN_SEQ;

CREATE SYNONYM &&2..PURGE_TXN_SEQ FOR &&1..PURGE_TXN_SEQ;

GRANT ALL ON &&2..ARM_TXN_PURGE_PROCESS_LOG TO &&2;

GRANT ALL ON &&2..PURGE_TXN_SEQ TO &&2;




