WHENEVER SQLERROR CONTINUE
REM ..............................
REM Execute these as "ARMANI_ext" user
REM ..............................

CREATE SYNONYM &&2..ARM_STG_CURRENCY_RT FOR &&1..ARM_STG_CURRENCY_RT;
CREATE SYNONYM &&2..ARM_STG_EMPLOYEE FOR &&1..ARM_STG_EMPLOYEE;
CREATE SYNONYM &&2..ARM_STG_PRM FOR &&1..ARM_STG_PRM;
CREATE SYNONYM &&2..ARM_STG_REGISTER FOR &&1..ARM_STG_REGISTER;
CREATE SYNONYM &&2..ARM_STG_STORE FOR &&1..ARM_STG_STORE;
CREATE SYNONYM &&2..ARM_OUT_STG_TIMECARD FOR &&1..ARM_OUT_STG_TIMECARD;
CREATE SYNONYM &&2..ARM_OUT_STG_TIMECARD_MODS FOR &&1..ARM_OUT_STG_TIMECARD_MODS;
CREATE SYNONYM &&2..ARM_MISC_LOOKUP FOR &&1..ARM_MISC_LOOKUP;
CREATE SYNONYM &&2..ARM_PROCESS_LOG FOR &&1..ARM_PROCESS_LOG;
CREATE SYNONYM &&2..STG_EVENT_ID_S FOR &&1..STG_EVENT_ID_S;
CREATE SYNONYM &&2..ARM_STG_TAX_FREE FOR &&1..ARM_STG_TAX_FREE;
CREATE SYNONYM &&2..ARM_STG_FISCAL_DOC_NO FOR &&1..ARM_STG_FISCAL_DOC_NO;
CREATE SYNONYM &&2..ARM_STG_FISCAL_DOC FOR &&1..ARM_STG_FISCAL_DOC;
CREATE SYNONYM &&2..ARM_STG_ITEM FOR &&1..ARM_STG_ITEM;
CREATE SYNONYM &&2..ARM_STG_TAX_RATE FOR &&1..ARM_STG_TAX_RATE;
CREATE SYNONYM &&2..ARM_STG_CUST_OUT FOR &&1..ARM_STG_CUST_OUT;
CREATE SYNONYM &&2..ARM_STG_INVENTORY FOR &&1..ARM_STG_INVENTORY;
CREATE SYNONYM &&2..ARM_STG_CUST_IN FOR &&1..ARM_STG_CUST_IN;
CREATE SYNONYM &&2..ARM_STG_ITEM FOR &&1..ARM_STG_ITEM;
CREATE SYNONYM &&2..ARM_STG_REDEEMABLE FOR &&1..ARM_STG_REDEEMABLE;
CREATE SYNONYM &&2..ARM_STG_RSVO_CSGO FOR &&1..ARM_STG_RSVO_CSGO;
CREATE SYNONYM &&2..ARM_STG_TXN_HIST FOR &&1..ARM_STG_TXN_HIST;
CREATE SYNONYM &&2..ARM_STG_TXN_HDR FOR &&1..ARM_STG_TXN_HDR;
CREATE SYNONYM &&2..ARM_STG_TXN_DTL FOR &&1..ARM_STG_TXN_DTL;
CREATE SYNONYM &&2..ARM_STG_DEPT FOR &&1..ARM_STG_DEPT;
CREATE SYNONYM &&2..ARM_STG_CLASS FOR &&1..ARM_STG_CLASS;
CREATE SYNONYM &&2..ARM_STG_SUBCLASS FOR &&1..ARM_STG_SUBCLASS;
CREATE SYNONYM &&2..ARM_STG_SPR FOR &&1..ARM_STG_SPR;
CREATE SYNONYM &&2..ARM_STG_SIZE FOR &&1..ARM_STG_SIZE;
CREATE SYNONYM &&2..ARM_STG_SEASON FOR &&1..ARM_STG_SEASON;
CREATE SYNONYM &&2..ARM_STG_COLOR FOR &&1..ARM_STG_COLOR;
