WHENEVER SQLERROR CONTINUE
REM ..............................
REM Execute these as "ARMANI_ext" user
REM ..............................

DROP SYNONYM &&2..ARM_STG_CURRENCY_RT; 
DROP SYNONYM &&2..ARM_STG_EMPLOYEE; 
DROP SYNONYM &&2..ARM_STG_PRM;
DROP SYNONYM &&2..ARM_STG_REGISTER;
DROP SYNONYM &&2..ARM_STG_STORE;
DROP SYNONYM &&2..ARM_OUT_STG_TIMECARD;
DROP SYNONYM &&2..ARM_OUT_STG_TIMECARD_MODS;
DROP SYNONYM &&2..ARM_MISC_LOOKUP;
DROP SYNONYM &&2..ARM_PROCESS_LOG;
DROP SYNONYM &&2..STG_EVENT_ID_S;
DROP SYNONYM &&2..ARM_STG_TAX_FREE;
DROP SYNONYM &&2..ARM_STG_FISCAL_DOC_NO;
DROP SYNONYM &&2..ARM_STG_FISCAL_DOC;
DROP SYNONYM &&2..ARM_STG_ITEM;  
DROP SYNONYM &&2..ARM_STG_TAX_RATE;
DROP SYNONYM &&2..ARM_STG_CUST_OUT;
DROP SYNONYM &&2..ARM_STG_INVENTORY;
DROP SYNONYM &&2..ARM_STG_CUST_IN;
DROP SYNONYM &&2..ARM_STG_ITEM;
DROP SYNONYM &&2..ARM_STG_REDEEMABLE;
DROP SYNONYM &&2..ARM_STG_RSVO_CSGO;
DROP SYNONYM &&2..ARM_STG_TXN_HIST;
DROP SYNONYM &&2..ARM_STG_TXN_HDR;
DROP SYNONYM &&2..ARM_STG_TXN_DTL;
DROP SYNONYM &&2..ARM_STG_DEPT;
DROP SYNONYM &&2..ARM_STG_CLASS;
DROP SYNONYM &&2..ARM_STG_SUBCLASS;
DROP SYNONYM &&2..ARM_STG_SPR;
DROP SYNONYM &&2..ARM_STG_SIZE;
DROP SYNONYM &&2..ARM_STG_SEASON;
DROP SYNONYM &&2..ARM_STG_COLOR;



