REM ..................................
REM Execute these as "ARMANI_Ext" user
REM ..................................

GRANT ALL ON &&2..ARM_STG_CURRENCY_RT TO &&2;

GRANT ALL ON &&2..ARM_STG_EMPLOYEE TO &&2;

GRANT ALL ON &&2..ARM_STG_PRM TO &&2;

GRANT ALL ON &&2..ARM_STG_REGISTER TO &&2;

GRANT ALL ON &&2..ARM_STG_STORE TO &&2;

GRANT ALL ON &&2..ARM_OUT_STG_TIMECARD TO &&2;

GRANT ALL ON &&2..ARM_OUT_STG_TIMECARD_MODS TO &&2;

GRANT ALL ON &&2..ARM_MISC_LOOKUP TO &&2;

GRANT ALL ON &&2..ARM_PROCESS_LOG TO &&2;

GRANT ALL ON &&2..STG_EVENT_ID_S TO &&2;

GRANT ALL ON &&2..ARM_STG_TAX_FREE TO &&2;

GRANT ALL ON &&2..ARM_STG_FISCAL_DOC_NO TO &&2;

GRANT ALL ON &&2..ARM_STG_FISCAL_DOC TO &&2;

GRANT ALL ON  &&2..ARM_STG_ITEM TO &&2;

GRANT ALL ON  &&2..ARM_STG_TAX_RATE TO &&2;

GRANT ALL ON &&2..ARM_STG_CUST_OUT TO &&2;

GRANT ALL ON &&2..ARM_STG_INVENTORY TO &&2;

GRANT ALL ON &&2..ARM_STG_CUST_IN TO &&2;

GRANT ALL ON  &&2..ARM_STG_ITEM TO &&2;

GRANT ALL ON &&2..ARM_STG_REDEEMABLE TO &&2;

GRANT ALL ON &&2..ARM_STG_RSVO_CSGO TO &&2;

GRANT ALL ON &&2..ARM_STG_TXN_HIST TO &&2;

GRANT ALL ON &&2..ARM_STG_TXN_HDR TO &&2;

GRANT ALL ON &&2..ARM_STG_TXN_DTL TO &&2;

GRANT ALL ON  &&2..ARM_STG_DEPT TO &&2;

GRANT ALL ON  &&2..ARM_STG_CLASS TO &&2;

GRANT ALL ON  &&2..ARM_STG_SUBCLASS TO &&2;

GRANT ALL ON  &&2..ARM_STG_SPR TO &&2;

GRANT ALL ON  &&2..ARM_STG_SIZE TO &&2;

GRANT ALL ON  &&2..ARM_STG_SEASON TO &&2;

GRANT ALL ON  &&2..ARM_STG_COLOR TO &&2;

