ALTER TABLE TR_RTL
ADD LOYALTY_POINTS_EARNED  NUMBER(7);

ALTER TABLE ARM_LOYALTY
ADD (CURRENT_YEAR_BAL NUMBER(15,2),
     LAST_YEAR_BAL NUMBER(15,2),
     SECOND_LAST_YEAR_BAL NUMBER(15,2));

ALTER TABLE ARM_LOYALTY_RULE
MODIFY POINTS NUMBER(8,4);

ALTER TABLE ARM_POS_PRS
ADD (CREDIT_CARD_NUMBER           VARCHAR2(128),
     CREDIT_CARD_TYPE             VARCHAR2(40),
     CREDIT_CARD_EXPIRATION_DATE  DATE,
     BILLING_ZIP_CODE             VARCHAR2(20));

ALTER TABLE RK_EOD
ADD MGR_SAYS_MALLCERTIFICATE  VARCHAR2(75);

CREATE OR REPLACE VIEW V_ARM_TXN_ITEM
(ID_ITM, BARCODE, ID_STR_RT, FY, SEASON, 
 DE_SEASON, ID_SPR, NM_SPR, MODEL, FABRIC, 
 ID_COLOR, DE_COLOR, NM_ITM, STYLE_NUM)
AS 
SELECT 
AS_ITM.ID_ITM			ID_ITM 
, AS_ITM.BARCODE		BARCODE 
, AS_ITM_RTL_STR.ID_STR_RT	ID_STR_RT 
, AS_ITM.FY			FY 
, AS_ITM.LU_SN		SEASON 
, ARM_SEASON.DE_SEASON		DE_SEASON 
, AS_ITM.ID_SPR			ID_SPR 
, ARM_SPR.NM_SPR		NM_SPR 
, AS_ITM.MODEL			MODEL 
, AS_ITM.FABRIC			FABRIC 
, AS_ITM.ID_COLOR		ID_COLOR 
, ARM_COLOR.DE_COLOR		DE_COLOR 
, AS_ITM_RTL_STR.NM_ITM			NM_ITM 
, AS_ITM.STYLE_NUM		STYLE_NUM 
FROM 
AS_ITM INNER JOIN 
( 
	AS_ITM_RTL_STR INNER JOIN PA_PRTY ON AS_ITM_RTL_STR.ID_STR_RT = 
PA_PRTY.ID_PRTY 
) 
ON AS_ITM.ID_ITM = AS_ITM_RTL_STR.ID_ITM 
LEFT OUTER JOIN ARM_SEASON ON (AS_ITM.LU_SN=ARM_SEASON.ID_SEASON AND 
PA_PRTY.ED_LA=ARM_SEASON.ED_LA AND PA_PRTY.ED_CO=ARM_SEASON.ED_CO) 
LEFT OUTER JOIN ARM_COLOR ON (AS_ITM.ID_COLOR=ARM_COLOR.ID_COLOR) 
LEFT OUTER JOIN ARM_SPR ON (AS_ITM.ID_SPR=ARM_SPR.ID_SPR);

ALTER TABLE RK_SALES_SUMMARY
MODIFY MISC_ITEM_ID VARCHAR2(40);

ALTER TABLE ARM_LOYALTY_RULE
MODIFY POINTS NUMBER(8,4);

CREATE OR REPLACE VIEW V_ARM_PREMIO_HIST
(STORE_NAME, TXN_NUM, TXN_DATE, REDEEMED_POINTS, TXN_AMT, 
 LOYALTY_NUM)
AS 
SELECT DISTINCT 
PA_STR_RTL.DE_STR_RT AS STORE_NAME, 
TR_LTM_CPN_TND.AI_TRN AS TXN_NUM, 
TR_LTM_CPN_TND.DC_DY_BSN AS TXN_DATE, 
TR_LTM_CPN_TND.ID_WS AS REDEEMED_POINTS, 
TR_LTM_TND.MO_ITM_LN_TND AS TXN_AMT, 
TR_LTM_CPN_TND.UC_CPN_SC AS LOYALTY_NUM 
FROM 
PA_STR_RTL,TR_LTM_CPN_TND, TR_LTM_TND 
WHERE 
( TR_LTM_TND.TY_TND = 'PREMIO_DISCOUNT' 
AND TR_LTM_TND.AI_TRN = TR_LTM_CPN_TND.AI_TRN 
AND PA_STR_RTL.ID_STR_RT = TR_LTM_CPN_TND.ID_STR_RT) 
ORDER BY 
TXN_DATE DESC, 
STORE_NAME DESC;






