CREATE INDEX INDX_ARM_HIST ON ARM_ITM_HIST
(ID_ITM, ID_STR_RT, KEY, EFFECTIVE_DT, EXPIRATION_DT);

CREATE INDEXINDX_ARM_HIST_ITM_STR ON ARM_ITM_HIST
(ID_ITM, ID_STR_RT);

CREATE INDEX INDX_ASRTL_ITEM ON AS_ITM_RTL_STR
(ID_ITM);

CREATE INDEX INDX_AS_ITM_RTL_STORE ON AS_ITM_RTL_STR
(ID_STR_RT);

ANALYZE TABLE ARM_ITM_HIST COMPUTE STATISTICS;

ANALYZE TABLE AS_ITM_RTL_STR COMPUTE STATISTICS;


