ALTER TABLE TR_LTM_RTL_TRN DROP CONSTRAINT &&CONSTRAINT_NAME;

CREATE TABLE ARM_FISCAL_DOC_LN_ITM_DTL(
	AI_TRN VARCHAR2(128),
	AI_LN_ITM INTEGER,
	DOC_NUM VARCHAR2(20),
	TY_DOC VARCHAR2(10),
	VAT_COMMENTS VARCHAR2(200)
);

ALTER TABLE ARM_FISCAL_DOC_LN_ITM_DTL
ADD PRIMARY KEY (AI_TRN, AI_LN_ITM, DOC_NUM, TY_DOC);

ALTER TABLE ARM_FISCAL_DOC_LN_ITM_DTL
ADD FOREIGN KEY (AI_TRN, DOC_NUM, TY_DOC) REFERENCES ARM_FISCAL_DOCUMENT(AI_TRN, DOC_NUM, TY_DOC);