CREATE OR REPLACE VIEW RK_TXN_HEADER (CUST_ID, TY_TRN, ID_STR_RT, ID_OPR, TS_TRN_PRC, TS_TRN_SBM, TY_GUI_TRN, PAY_TYPES, TOTAL_AMT, AI_TRN, CONSULTANT_ID, REDUCTION_AMOUNT, NET_AMOUNT, DISCOUNT_TYPES, ITEMS_IDS, REGISTER_ID, FN_PRS, LN_PRS) AS
	SELECT RK_PAY_TRN.CUST_ID, TR_TRN.TY_TRN, TR_TRN.ID_STR_RT, TR_TRN.ID_OPR, TR_TRN.TS_TRN_PRC, TR_TRN.TS_TRN_SBM, TR_TRN.TY_GUI_TRN, RK_PAY_TRN.PAY_TYPES, RK_PAY_TRN.TOTAL_AMT, RK_PAY_TRN.AI_TRN, TR_RTL.CONSULTANT_ID, TR_RTL.REDUCTION_AMOUNT, TR_RTL.NET_AMOUNT, TR_RTL.DISCOUNT_TYPES, TR_RTL.ITEMS_IDS, TR_RTL.REGISTER_ID, PA_PRS.FN_PRS, PA_PRS.LN_PRS
	FROM RK_PAY_TRN, TR_TRN, TR_RTL, PA_PRS
	WHERE TR_TRN.AI_TRN = RK_PAY_TRN.AI_TRN 
		and RK_PAY_TRN.AI_TRN = TR_RTL.AI_TRN (+) 
		and TR_RTL.CONSULTANT_ID = PA_PRS.ID_PRTY_PRS (+) 
		and TR_TRN.TY_TRN = 'TRNPAY' order by TR_TRN.AI_TRN;
