ALTER TABLE CO_PRM DROP PRIMARY KEY CASCADE;

ALTER TABLE CO_PRM 
ADD   CONSTRAINT CO_PRM_PK PRIMARY KEY ( ID_PRM, ID_STR_RT );

ALTER TABLE RU_PRM_PRDV DROP PRIMARY KEY CASCADE;

ALTER TABLE RU_PRM_PRDV
ADD   CONSTRAINT RU_PRM_PRDV PRIMARY KEY ( ID_PRM, ID_RU_PRDV, ID_STR_RT );

ALTER TABLE ARM_BRN ADD PRIMARY KEY (ID_BRN, ED_CO, ED_LA);

ALTER TABLE ARM_SPR ADD PRIMARY KEY (ID_SPR);

ALTER TABLE ARM_SEASON ADD PRIMARY KEY (ID_SEASON, ED_CO, ED_LA);

ALTER TABLE ARM_SIZE ADD PRIMARY KEY (ID_SIZE, ED_CO, ED_LA);

ALTER TABLE ARM_COLOR ADD PRIMARY KEY (ID_COLOR);

ALTER TABLE ARM_CLASS ADD PRIMARY KEY (ID_DPT, ID_CLSS);

ALTER TABLE ARM_SUBCLASS ADD PRIMARY KEY (ID_DPT, ID_CLSS, ID_SBCL);

ALTER TABLE ARM_LABEL ADD PRIMARY KEY (ID_LABEL, ED_CO, ED_LA);

ALTER TABLE ARM_SUBLINE ADD PRIMARY KEY (ID_SUBLINE, ED_CO, ED_LA);

ALTER TABLE ARM_GENDER ADD PRIMARY KEY (ID_GENDER, ED_CO, ED_LA);

ALTER TABLE ARM_CATEGORY ADD PRIMARY KEY (ID_CATEGORY, ED_CO, ED_LA);

ALTER TABLE ARM_DROP ADD PRIMARY KEY (ID_DROP, ED_CO, ED_LA);

ALTER TABLE ARM_PRODUCT ADD PRIMARY KEY (ID_PRODUCT);

ALTER TABLE AS_ITM_RTL_STR 
DROP PRIMARY KEY CASCADE;

ALTER TABLE AS_ITM_RTL_STR 
ADD PRIMARY KEY (ID_ITM, ID_STR_RT);

ALTER TABLE RK_PRM_ITM
DROP PRIMARY KEY CASCADE;

ALTER TABLE RK_PRM_ITM
ADD PRIMARY KEY (ID_ITM, ID_STR_RT, CURRENCY_CODE, ID_RU_PRDV);

ALTER TABLE TR_LTM_DSC_DTL ADD PRIMARY KEY(AI_TRN, AL_LN_ITM, SEQ_NUM);

ALTER TABLE ARM_POS_PRS ADD PRIMARY KEY (AI_TRN);

ALTER TABLE ARM_PRS_POS_LN_ITM_DTL ADD PRIMARY KEY ( AI_TRN, AI_LN_ITM, SEQUENCE_NUM );

ALTER TABLE ARM_POS_CSG ADD PRIMARY KEY (AI_TRN);

ALTER TABLE ARM_CSG_POS_LN_ITM_DTL ADD PRIMARY KEY ( AI_TRN, AI_LN_ITM, SEQUENCE_NUM );

ALTER TABLE ARM_ITM_SOH ADD PRIMARY KEY (ITEM_ID, STORE_ID);

ALTER TABLE ARM_CT_DTL ADD PRIMARY KEY (ID_CT);

ALTER TABLE ARM_ADS_PH ADD PRIMARY KEY (ID_ADS, ID_PH_TYP);

ALTER TABLE ARM_CT_ASSOC ADD PRIMARY KEY (ID_CT, ID_STR_RT);

ALTER TABLE ARM_CT_COMMENTS ADD PRIMARY KEY (ID_CT, ID_STR_RT);

ALTER TABLE ARM_ALTERN_LN_ITM_DTL ADD  PRIMARY KEY ( AI_TRN, AI_LN_ITM, DET_SEQ_NUM, SEQ_NUM );

ALTER TABLE ARM_ALTERN_DTL ADD PRIMARY KEY ( AI_TRN, AI_LN_ITM, DET_SEQ_NUM, ALTERN_SEQ_NUM, CD_ALTERN);

ALTER TABLE ARM_LOYALTY_RULE
    ADD CONSTRAINT ARM_LOYALTY_RULE_PK PRIMARY KEY (ID_RULE);

ALTER TABLE ARM_LOYALTY
    ADD CONSTRAINT ARM_LOYALTY_PK PRIMARY KEY (LOYALTY_NUM);

ALTER TABLE ARM_CT_COMMENTS DROP PRIMARY KEY;

ALTER TABLE ARM_TAX_FREE ADD PRIMARY KEY (STORE_CODE, DETAX_CODE, START_DATE);

ALTER TABLE ARM_FISCAL_DOC_NO ADD PRIMARY KEY (REGISTER_ID, ID_STR_RT);

ALTER TABLE ARM_POS_RSV ADD PRIMARY KEY (ID_RESERVATION);

ALTER TABLE ARM_RSV_POS_LN_ITM_DTL ADD PRIMARY KEY ( AI_TRN, AI_LN_ITM, SEQUENCE_NUM );

ALTER TABLE ARM_FISCAL_DOCUMENT
ADD PRIMARY KEY (AI_TRN, DOC_NUM, TY_DOC);

ALTER TABLE ARM_SIZE
    DROP PRIMARY KEY;

ALTER TABLE ARM_SIZE
    ADD PRIMARY KEY (ID_SIZE, SIZE_INDEX, ED_CO, ED_LA);

ALTER TABLE ARM_EOD_GROUP
ADD PRIMARY KEY (CD_GROUP);

ALTER TABLE ARM_EOD_DTL
ADD PRIMARY KEY (AI_TRN, CD_GROUP, CD_TYPE);

ALTER TABLE ARM_ALTERN_GRP
ADD  ( PRIMARY KEY (GROUP_ID) ) ;

ALTER TABLE ARM_ALTERN_CODE
ADD  ( PRIMARY KEY (GROUP_ID, ALTERN_CODE) ) ;

ALTER TABLE ARM_CFG_DETAIL
ADD  ( PRIMARY KEY (TY_CFG, CD_CFG,ED_CO,ED_LA) ) ;

ALTER TABLE ARM_CURRENCY_RATE
ADD PRIMARY KEY (ID_CNY_FROM, ID_CNY_TO, ED_CO, ED_LA);

