ALTER TABLE AS_ITM
ADD  ( FOREIGN KEY (ID_DPT_POS)
REFERENCES ID_DPT_PS ) ;

ALTER TABLE AS_ITM
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE AS_ITM_BLK
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM_STK ) ;

ALTER TABLE AS_ITM_RTL_STR
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE AS_ITM_STK
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE AS_ITM_STK
ADD  ( FOREIGN KEY (LU_UOM)
REFERENCES CO_UOM ) ;

ALTER TABLE AS_TL
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE AS_TR
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE AS_TR
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM_BLK ) ;

ALTER TABLE AS_TR
ADD  ( FOREIGN KEY (LU_UOM)
REFERENCES CO_UOM ) ;

ALTER TABLE CO_ACS_PSWD
ADD  ( FOREIGN KEY (ID_STR_RT, ID_OPR)
REFERENCES PA_OPR ) ;

ALTER TABLE CO_ASCTN_RLTD_ITM
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE CO_ASCTN_RLTD_ITM
ADD  ( FOREIGN KEY (ID_ITM_RLTD)
REFERENCES AS_ITM ) ;

ALTER TABLE CO_CFG_BTTN
ADD  ( FOREIGN KEY (ID_CFG)
REFERENCES CO_CFG ) ;

ALTER TABLE CO_CFG_CPN
ADD  ( FOREIGN KEY (ID_CFG)
REFERENCES CO_CFG ) ;

ALTER TABLE CO_CFG_MNY_ORD
ADD  ( FOREIGN KEY (ID_CFG)
REFERENCES CO_CFG ) ;

ALTER TABLE CO_CFG_PDT_RST
ADD  ( FOREIGN KEY (ID_CFG)
REFERENCES CO_CFG ) ;

ALTER TABLE CO_CFG_PY_IN_OT
ADD  ( FOREIGN KEY (ID_CFG)
REFERENCES CO_CFG ) ;

ALTER TABLE CO_CFG_SPR_PY_TYP
ADD  ( FOREIGN KEY (ID_CFG)
REFERENCES CO_CFG ) ;

ALTER TABLE CO_CFG_TND_TYP
ADD  ( FOREIGN KEY (ID_CFG)
REFERENCES CO_CFG ) ;

ALTER TABLE CO_CTAF
ADD  ( FOREIGN KEY (ID_CT)
REFERENCES PA_KY_CT ) ;

ALTER TABLE CO_CTAF
ADD  ( FOREIGN KEY (ID_GP_ID)
REFERENCES PA_GP_CT ) ;

ALTER TABLE CO_EV_MNT
ADD  ( FOREIGN KEY (ID_STR_RT, ID_EV)
REFERENCES CO_EV ) ;

ALTER TABLE CO_ITM_CFG
ADD  ( FOREIGN KEY (ID_STR_CFG)
REFERENCES CO_STR_CFG ) ;

ALTER TABLE CO_MNT_ITM
ADD  ( FOREIGN KEY (ID_STR_RT, ID_EV)
REFERENCES CO_EV_MNT ) ;

ALTER TABLE CO_PLN_EM_CMN
ADD  ( FOREIGN KEY (ID_STR_RT, ID_ACNT_LDG)
REFERENCES LE_ACNT_STR_FN ) ;

ALTER TABLE CO_PST
ADD  ( FOREIGN KEY (CD_JOB)
REFERENCES ST_JOB ) ;

ALTER TABLE CO_STR_CFG
ADD  ( FOREIGN KEY (ID_CFG)
REFERENCES CO_CFG ) ;

ALTER TABLE CO_TH_MPR_UN
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE CO_TH_MPR_UN
ADD  ( FOREIGN KEY (LU_UOM)
REFERENCES CO_UOM ) ;

ALTER TABLE DO_CF_GF
ADD  ( FOREIGN KEY (TY_GF_CF)
REFERENCES CO_CLS_GF_CF ) ;

ALTER TABLE ID_DPT_PS
ADD  ( FOREIGN KEY (ID_DPT_POS_PRNT)
REFERENCES ID_DPT_PS ) ;

ALTER TABLE ID_IDN_PS
ADD  ( FOREIGN KEY (ID_ITM, CURRENCY_CODE)
REFERENCES AS_ITM_RTL_STR ) ;

ALTER TABLE LE_HST_ITM_SLS_PRC
ADD  ( FOREIGN KEY (ID_STR_RT, ID_EV)
REFERENCES CO_MNT_ITM ) ;

ALTER TABLE LE_PRC_SPL_CT_TYP
ADD  ( FOREIGN KEY (ID_GP_ID)
REFERENCES PA_GP_CT ) ;

ALTER TABLE LE_PRC_SPL_CT_TYP
ADD  ( FOREIGN KEY (ID_ITM, CURRENCY_CODE)
REFERENCES AS_ITM_RTL_STR ) ;

ALTER TABLE LO_ADS_LCN_PHY
ADD  ( FOREIGN KEY (ID_ADS)
REFERENCES LO_ADS ) ;

ALTER TABLE LO_ADS_LCN_PHY
ADD  ( FOREIGN KEY (TY_CRDN, CD_LCN_PHY)
REFERENCES LO_LCN_PHY ) ;

ALTER TABLE LO_ADS_PRTY
ADD  ( FOREIGN KEY (ID_ADS)
REFERENCES LO_ADS ) ;

ALTER TABLE LO_ADS_PRTY
ADD  ( FOREIGN KEY (ID_PRTY, TY_RO_PRTY)
REFERENCES PA_RO_PRTY ) ;

ALTER TABLE LO_EML_ADS
ADD  ( FOREIGN KEY (ID_PRTY)
REFERENCES PA_PRTY ) ;

ALTER TABLE LO_LCN_PHY
ADD  ( FOREIGN KEY (TY_CRDN)
REFERENCES LO_CRDN_TYP ) ;

ALTER TABLE LO_PH
ADD  ( FOREIGN KEY (ID_PH_TYP)
REFERENCES LO_PH_TYP ) ;

ALTER TABLE LO_PH
ADD  ( FOREIGN KEY (ID_PRTY)
REFERENCES PA_PRTY ) ;

ALTER TABLE MA_CRT_ITM
ADD  ( FOREIGN KEY (ID_STR_RT, ID_EV)
REFERENCES CO_MNT_ITM ) ;

ALTER TABLE MA_DLT_ITM
ADD  ( FOREIGN KEY (ID_STR_RT, ID_EV)
REFERENCES CO_MNT_ITM ) ;

ALTER TABLE MA_ITM_PRN_PRC_ITM
ADD  ( FOREIGN KEY (ID_EV, ID_STR_RT)
REFERENCES TR_CHN_PRN_PRC ) ;

ALTER TABLE MA_ITM_TMP_PRC_CHN
ADD  ( FOREIGN KEY (ID_EV, ID_STR_RT)
REFERENCES TR_CHN_TMP_PRC ) ;

ALTER TABLE MA_PRC_ITM
ADD  ( FOREIGN KEY (ID_STR_RT, ID_EV)
REFERENCES CO_MNT_ITM ) ;

ALTER TABLE MA_UPDT_ITM_DSCR
ADD  ( FOREIGN KEY (ID_STR_RT, ID_EV)
REFERENCES CO_MNT_ITM ) ;

ALTER TABLE PA_CT
ADD  ( FOREIGN KEY (ID_PRTY, TY_RO_PRTY)
REFERENCES PA_RO_PRTY ) ;

ALTER TABLE PA_EM
ADD  ( FOREIGN KEY (ID_PLN_EM_CMN)
REFERENCES CO_PLN_EM_CMN ) ;

ALTER TABLE PA_EM
ADD  ( FOREIGN KEY (ID_PRTY, TY_RO_PRTY)
REFERENCES PA_RO_PRTY ) ;

ALTER TABLE PA_EM
ADD  ( FOREIGN KEY (SC_EM)
REFERENCES RK_EMP_STATUS ) ;

ALTER TABLE PA_KY_CT
ADD  ( FOREIGN KEY (ID_CT)
REFERENCES PA_CT ) ;

ALTER TABLE PA_OPR
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE PA_ORGN
ADD  ( FOREIGN KEY (ID_PRTY_ORGN)
REFERENCES PA_PRTY ) ;

ALTER TABLE PA_PRS
ADD  ( FOREIGN KEY (ID_PRTY_PRS)
REFERENCES PA_PRTY ) ;

ALTER TABLE PA_RO_PRTY
ADD  ( FOREIGN KEY (ID_PRTY)
REFERENCES PA_PRTY ) ;

ALTER TABLE PA_RO_PRTY
ADD  ( FOREIGN KEY (TY_RO_PRTY)
REFERENCES PA_RO_PRTY_TYP ) ;

ALTER TABLE PA_STR_RTL
ADD  ( FOREIGN KEY (ID_PRTY, TY_RO_PRTY)
REFERENCES PA_RO_PRTY ) ;

ALTER TABLE RK_COLLECTION
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE RK_COMP_PRM_PK
ADD  ( FOREIGN KEY (ID_ITM, CURRENCY_CODE, ID_RU_PRDV)
REFERENCES RK_PRM_ITM ) ;

ALTER TABLE RK_COMP_PRM_PK
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RK_PRM_PK ) ;

ALTER TABLE RK_EMP_APP_FORM
ADD  ( FOREIGN KEY (APPLYING_FOR)
REFERENCES ST_JOB ) ;

ALTER TABLE RK_EMP_FORM
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE RK_EMP_FORM
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_EMP_FORM
ADD  ( FOREIGN KEY (TYPE_ID)
REFERENCES RK_FORM_TYPE ) ;

ALTER TABLE RK_EMP_GL_CH_DT
ADD  ( FOREIGN KEY (ID_EM, ID_STR_RT)
REFERENCES RK_EMP_GOAL ) ;

ALTER TABLE RK_EMP_GOAL
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE RK_EMP_GOAL
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES RK_STR_GOAL ) ;

ALTER TABLE RK_EMP_HISTORY
ADD  ( FOREIGN KEY (FORM_ID)
REFERENCES RK_EMP_APP_FORM ) ;

ALTER TABLE RK_EMP_REFERENCE
ADD  ( FOREIGN KEY (FORM_ID)
REFERENCES RK_EMP_APP_FORM ) ;

ALTER TABLE RK_EMP_RSC
ADD  ( FOREIGN KEY (EMPLOYEE_ID)
REFERENCES PA_EM ) ;

ALTER TABLE RK_EMP_RSC
ADD  ( FOREIGN KEY (STORE_ID)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_EMP_RSC_ROL
ADD  ( FOREIGN KEY (EMPLOYEE_ID)
REFERENCES RK_EMP_RSC ) ;

ALTER TABLE RK_EMP_RSC_ROL
ADD  ( FOREIGN KEY (ROLE_ID)
REFERENCES RK_ROLE ) ;

ALTER TABLE RK_EMP_RSC_ROL
ADD  ( FOREIGN KEY (TYPE_ID)
REFERENCES RK_EMP_RSC_ROL_TY ) ;

ALTER TABLE RK_EMP_SALE
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE RK_EMP_SALE
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_EMP_TIMECARD
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE RK_EMP_TIMECARD
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_EOD
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_TRN ) ;

ALTER TABLE RK_I9_FORM
ADD  ( FOREIGN KEY (EXAMINER_ID)
REFERENCES PA_EM ) ;

ALTER TABLE RK_I9_FORM
ADD  ( FOREIGN KEY (ID)
REFERENCES RK_EMP_FORM ) ;

ALTER TABLE RK_I9_FORM
ADD  ( FOREIGN KEY (PREPARER_ID)
REFERENCES PA_EM ) ;

ALTER TABLE RK_ID_DOC
ADD  ( FOREIGN KEY (FORM_ID)
REFERENCES RK_I9_FORM ) ;

ALTER TABLE RK_ID_DOC
ADD  ( FOREIGN KEY (TYPE_ID)
REFERENCES RK_ID_DOC_TYPE ) ;

ALTER TABLE RK_LAY
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_RTL ) ;

ALTER TABLE RK_LAY
ADD  ( FOREIGN KEY (ID_CT)
REFERENCES PA_CT ) ;

ALTER TABLE RK_LAY_PAY
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE RK_LAY_PAY
ADD  ( FOREIGN KEY (ORIGINAL_ID)
REFERENCES RK_LAY ) ;

ALTER TABLE RK_LAY_PAY_INFO
ADD  ( FOREIGN KEY (ID)
REFERENCES RK_LAY ) ;

ALTER TABLE RK_LAY_RTS
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE RK_LAY_RTS
ADD  ( FOREIGN KEY (ORGN_LAY_ID)
REFERENCES RK_LAY ) ;

ALTER TABLE RK_LOT
ADD  ( FOREIGN KEY (ITEM_ID)
REFERENCES AS_ITM ) ;

ALTER TABLE RK_LOT
ADD  ( FOREIGN KEY (STORE_ID)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_LOT_TRN
ADD  ( FOREIGN KEY (LOT_ID)
REFERENCES RK_LOT ) ;

ALTER TABLE RK_LOT_TRN
ADD  ( FOREIGN KEY (TRANSACTION_ID)
REFERENCES TR_TRN ) ;

ALTER TABLE RK_NO_SALE
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE RK_PAID_OUT
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE RK_PAY_SUM
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE RK_PAY_SUM
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_PAY_TRN
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_TRN ) ;

ALTER TABLE RK_PAY_TRN
ADD  ( FOREIGN KEY (TYPE_ID)
REFERENCES CO_TYP_TRN ) ;

ALTER TABLE RK_POS_LAY
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_RTL ) ;

ALTER TABLE RK_POS_LN_ITM_DTL
ADD  ( FOREIGN KEY (AI_TRN, AI_LN_ITM)
REFERENCES TR_LTM_RTL_TRN ) ;

ALTER TABLE RK_PRM_IT
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RU_PRDV ) ;

ALTER TABLE RK_PRM_ITM
ADD  ( FOREIGN KEY (ID_ITM, CURRENCY_CODE)
REFERENCES AS_ITM_RTL_STR ) ;

ALTER TABLE RK_PRM_ITM
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RU_PRDV ) ;

ALTER TABLE RK_PRM_MB
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RU_PRDV ) ;

ALTER TABLE RK_PRM_MU
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RU_PRDV ) ;

ALTER TABLE RK_PRM_PK
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RU_PRDV ) ;

ALTER TABLE RK_PRM_PK_AMT
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RK_PRM_PK ) ;

ALTER TABLE RK_PRM_PK_PE
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RK_PRM_PK ) ;

ALTER TABLE RK_REDM_BYBK
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE RK_REDM_BYBK
ADD  ( FOREIGN KEY (ID_NMB_SRZ_GF_CF, TY_GF_CF)
REFERENCES DO_CF_GF ) ;

ALTER TABLE RK_REDM_HIST
ADD  ( FOREIGN KEY (ID_NMB_SRZ_GF_CF, TY_GF_CF)
REFERENCES DO_CF_GF ) ;

ALTER TABLE RK_REDUCTION
ADD  ( FOREIGN KEY (AI_TRN, AI_LN_ITM, DETAIL_SEQ_NUMBER)
REFERENCES RK_POS_LN_ITM_DTL ) ;

ALTER TABLE RK_RELATED_EMP
ADD  ( FOREIGN KEY (FORM_ID)
REFERENCES RK_EMP_APP_FORM ) ;

ALTER TABLE RK_RTN_POS_LN_ITM
ADD  ( FOREIGN KEY (RTN_AI_TRN, RTN_AI_LN_ITM, SEQUENCE_NUMBER)
REFERENCES RK_POS_LN_ITM_DTL ) ;

ALTER TABLE RK_RTN_POS_LN_ITM
ADD  ( FOREIGN KEY (SALE_AI_TRN, SALE_AI_LN_ITM,
SALE_DTL_SEQ_NUM)
REFERENCES RK_POS_LN_ITM_DTL ) ;

ALTER TABLE RK_SALES_SUMMARY
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE RK_SALES_SUMMARY
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE RK_SALES_SUMMARY
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_SCHEDULE
ADD  ( FOREIGN KEY (STORE_ID)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_SHIFT
ADD  ( FOREIGN KEY (EMPLOYEE_ID)
REFERENCES PA_EM ) ;

ALTER TABLE RK_SHIFT
ADD  ( FOREIGN KEY (ROLE_ID)
REFERENCES RK_ROLE ) ;

ALTER TABLE RK_SHIFT
ADD  ( FOREIGN KEY (SCHEDULE_ID)
REFERENCES RK_SCHEDULE ) ;

ALTER TABLE RK_SHIP_REQ
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_RTL ) ;

ALTER TABLE RK_SOS
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_TRN ) ;

ALTER TABLE RK_STR_GL_CHG_DATE
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES RK_STR_GOAL ) ;

ALTER TABLE RK_STR_GOAL
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_TIMECARD
ADD  ( FOREIGN KEY (ID_OP)
REFERENCES PA_EM ) ;

ALTER TABLE RK_TIMECARD
ADD  ( FOREIGN KEY (ID_RPSTY_TND, ID_STR_RT)
REFERENCES AS_TL ) ;

ALTER TABLE RK_TIMECARD
ADD  ( FOREIGN KEY (TY_TRN)
REFERENCES CO_TYP_TRN ) ;

ALTER TABLE RK_TIMECARD
ADD  ( FOREIGN KEY (WEEK_ENDING, ID_EM)
REFERENCES RK_EMP_TIMECARD ) ;

ALTER TABLE RK_TIMECARD_BEN
ADD  ( FOREIGN KEY (ID)
REFERENCES RK_TIMECARD ) ;

ALTER TABLE RK_TIMECARD_MOD
ADD  ( FOREIGN KEY (ID)
REFERENCES RK_TIMECARD ) ;

ALTER TABLE RK_TIMECARD_MOD
ADD  ( FOREIGN KEY (NEW_ID)
REFERENCES RK_TIMECARD ) ;

ALTER TABLE RK_TIMECARD_MOD
ADD  ( FOREIGN KEY (OLD_ID)
REFERENCES RK_TIMECARD ) ;

ALTER TABLE RK_TIME_RANGE
ADD  ( FOREIGN KEY (EMPLOYEE_ID)
REFERENCES RK_EMP_RSC ) ;

ALTER TABLE RK_TIME_RANGE
ADD  ( FOREIGN KEY (TYPE_ID)
REFERENCES RK_TIME_RANGE_TYPE ) ;

ALTER TABLE RK_TRANSFER
ADD  ( FOREIGN KEY (ID)
REFERENCES TR_TRN ) ;

ALTER TABLE RK_TRANSFER
ADD  ( FOREIGN KEY (TRN_TYPE_ID)
REFERENCES CO_TYP_TRN ) ;

ALTER TABLE RK_TRANSFER_IN
ADD  ( FOREIGN KEY (ID)
REFERENCES RK_TRANSFER ) ;

ALTER TABLE RK_TRANSFER_IN
ADD  ( FOREIGN KEY (TRANSFER_OUT_ID)
REFERENCES RK_TRANSFER_OUT ) ;

ALTER TABLE RK_TRANSFER_LN_ITM
ADD  ( FOREIGN KEY (ITEM_ID)
REFERENCES AS_ITM ) ;

ALTER TABLE RK_TRANSFER_LN_ITM
ADD  ( FOREIGN KEY (TRANSFER_ID)
REFERENCES RK_TRANSFER ) ;

ALTER TABLE RK_TRANSFER_OUT
ADD  ( FOREIGN KEY (ID)
REFERENCES RK_TRANSFER ) ;

ALTER TABLE RK_TXN_TY_SUM
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE RK_TXN_TY_SUM
ADD  ( FOREIGN KEY (ID_STR_RT)
REFERENCES PA_STR_RTL ) ;

ALTER TABLE RK_VAC_REQ_DATE
ADD  ( FOREIGN KEY (FORM_ID)
REFERENCES RK_VAC_REQ_FORM ) ;

ALTER TABLE RK_VAC_REQ_FORM
ADD  ( FOREIGN KEY (AUTH_MGR_ID)
REFERENCES PA_EM ) ;

ALTER TABLE RK_VAC_REQ_FORM
ADD  ( FOREIGN KEY (ID)
REFERENCES RK_EMP_FORM ) ;

ALTER TABLE RK_VAC_REQ_FORM
ADD  ( FOREIGN KEY (SUPERVISOR_ID)
REFERENCES PA_EM ) ;

ALTER TABLE RK_VOID_TRANSFER
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_TRN ) ;

ALTER TABLE RK_VOID_TRANSFER
ADD  ( FOREIGN KEY (ORIGINAL_ID)
REFERENCES RK_TRANSFER ) ;

ALTER TABLE RK_VOID_TRN
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE RK_W4_FORM
ADD  ( FOREIGN KEY (ID)
REFERENCES RK_EMP_FORM ) ;

ALTER TABLE RU_DS
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE RU_PRDV_ITM
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RU_PRDV ) ;

ALTER TABLE RU_PRM_PRDV
ADD  ( FOREIGN KEY (ID_PRM)
REFERENCES CO_PRM ) ;

ALTER TABLE RU_PRM_PRDV
ADD  ( FOREIGN KEY (ID_RU_PRDV)
REFERENCES RU_PRDV ) ;

ALTER TABLE ST_ASGMT_EM_STR
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE ST_EM_ASGMT
ADD  ( FOREIGN KEY (ID_EM)
REFERENCES PA_EM ) ;

ALTER TABLE ST_EM_ASGMT
ADD  ( FOREIGN KEY (ID_PST)
REFERENCES CO_PST ) ;

ALTER TABLE TR_CHN_PRN_PRC
ADD  ( FOREIGN KEY (ID_EV, ID_STR_RT)
REFERENCES MA_PRC_ITM ) ;

ALTER TABLE TR_CHN_TMP_PRC
ADD  ( FOREIGN KEY (ID_EV, ID_STR_RT)
REFERENCES MA_PRC_ITM ) ;

ALTER TABLE TR_LTM_CHK_TND
ADD  ( FOREIGN KEY (AI_TRN, AI_LN_ITM)
REFERENCES TR_LTM_TND ) ;

ALTER TABLE TR_LTM_CHK_TND
ADD  ( FOREIGN KEY (LU_CLS_TND)
REFERENCES CO_CLS_TND ) ;

ALTER TABLE TR_LTM_CPN_TND
ADD  ( FOREIGN KEY (AI_TRN, AI_LN_ITM)
REFERENCES TR_LTM_TND ) ;

ALTER TABLE TR_LTM_CRDB_CRD_TN
ADD  ( FOREIGN KEY (AI_TRN, AI_LN_ITM)
REFERENCES TR_LTM_TND ) ;

ALTER TABLE TR_LTM_CRDB_CRD_TN
ADD  ( FOREIGN KEY (LU_CLS_TND)
REFERENCES CO_CLS_TND ) ;

ALTER TABLE TR_LTM_DSC
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_RTL ) ;

ALTER TABLE TR_LTM_DSC
ADD  ( FOREIGN KEY (TY_DSC)
REFERENCES TR_DSC ) ;

ALTER TABLE TR_LTM_EM__DSC
ADD  ( FOREIGN KEY (AI_TRN, AI_LN_ITM)
REFERENCES TR_LTM_DSC ) ;

ALTER TABLE TR_LTM_GF_CF
ADD  ( FOREIGN KEY (AI_TRN, AI_LN_ITM)
REFERENCES TR_LTM_RTL_TRN ) ;

ALTER TABLE TR_LTM_GF_CF_TND
ADD  ( FOREIGN KEY (AI_TRN, AI_LN_ITM)
REFERENCES TR_LTM_TND ) ;

ALTER TABLE TR_LTM_GF_CF_TND
ADD  ( FOREIGN KEY (LU_CLS_TND)
REFERENCES CO_CLS_TND ) ;

ALTER TABLE TR_LTM_RTL_TRN
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES TR_RTL ) ;

ALTER TABLE TR_LTM_RTL_TRN
ADD  ( FOREIGN KEY (ID_ITM)
REFERENCES AS_ITM ) ;

ALTER TABLE TR_LTM_RTL_TRN
ADD  ( FOREIGN KEY (POS_LN_ITM_TY_ID)
REFERENCES RK_POS_LN_ITM_TYP ) ;

ALTER TABLE TR_LTM_TND
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE TR_LTM_TND
ADD  ( FOREIGN KEY (LU_CLS_TND)
REFERENCES CO_CLS_TND ) ;

ALTER TABLE TR_RTL
ADD  ( FOREIGN KEY (AI_TRN)
REFERENCES RK_PAY_TRN ) ;

ALTER TABLE TR_RTL
ADD  ( FOREIGN KEY (ID_CT)
REFERENCES PA_CT ) ;

ALTER TABLE TR_TRN
ADD  ( FOREIGN KEY (ID_RPSTY_TND, ID_STR_RT)
REFERENCES AS_TL ) ;

ALTER TABLE TR_TRN
ADD  ( FOREIGN KEY (TY_TRN)
REFERENCES CO_TYP_TRN ) ;

