CREATE OR REPLACE FORCE VIEW V_ARM_CUST_RULE_DATA
(NET_AMOUNT, QUANTITY, PRODUCT_CD, RECORD_TYPE, ID_CT, 
 PRIORITY, ED_CO, CURRENCY_TYPE, SOCIETY_CODE)
 AS 
SELECT Arm_Util_Pkg.CONVERT_TO_CURRENCY(NET_AMOUNT, TY_CNY, '0') NET_AMOUNT, QUANTITY, 
 PRODUCT_CD, RECORD_TYPE, ID_CT,PRIORITY, ED_CO ,TY_CNY,ID_CMY 
 FROM 
  ( 
    SELECT SUM(DECODE(TXN_TYPE, 'SALE', Arm_Util_Pkg.CONVERT_TO_NUMBER(TXN_AMOUNT, PA_STR_RTL.TY_CNY), 'RETN', Arm_Util_Pkg.CONVERT_TO_NUMBER(TXN_AMOUNT, PA_STR_RTL.TY_CNY) * -1, 0)) NET_AMOUNT, 
   SUM(0) QUANTITY, 
   '' PRODUCT_CD, 
   RECORD_TYPE, 
   ID_CT, 
   ARM_EMP_ALERT_RULE. PRIORITY, 
   PA_PRTY.ED_CO, 
   PA_STR_RTL.TY_CNY, 
   PA_STR_RTL.ID_CMY 
   FROM ARM_CUST_SALE_SUMMARY 
   INNER JOIN PA_STR_RTL ON ARM_CUST_SALE_SUMMARY.ID_STR_RT = PA_STR_RTL.ID_STR_RT 
   INNER JOIN ARM_EMP_ALERT_RULE ON ARM_EMP_ALERT_RULE.RECORD_TYPE = 'TOT' 
   AND ARM_CUST_SALE_SUMMARY.TXN_DATE BETWEEN ARM_EMP_ALERT_RULE.START_DATE AND ARM_EMP_ALERT_RULE.END_DATE 
   INNER JOIN PA_PRTY ON ARM_CUST_SALE_SUMMARY.ID_STR_RT=PA_PRTY.ID_PRTY AND ARM_EMP_ALERT_RULE.CD_CO = PA_PRTY.ED_CO 
   GROUP BY RECORD_TYPE,ID_CT, PRIORITY,PA_PRTY.ED_CO,PA_STR_RTL.TY_CNY,PA_STR_RTL.ID_STR_RT,PA_STR_RTL.ID_CMY 
    UNION ALL 
	SELECT SUM(0) NET_AMOUNT, 
   SUM(TR_LTM_RTL_TRN.QUANTITY) QUANTITY, 
   PRODUCT_CD, 
   RULE.RECORD_TYPE, 
   RK_PAY_TRN.CUST_ID, 
   RULE. PRIORITY, 
   PA_PRTY.ED_CO, 
   '' TY_CNY , 
   PA_STR_RTL.ID_CMY 
   FROM RK_PAY_TRN, TR_LTM_RTL_TRN, AS_ITM, ARM_EMP_ALERT_RULE RULE, TR_TRN, PA_PRTY ,PA_STR_RTL 
   WHERE RK_PAY_TRN.AI_TRN = TR_LTM_RTL_TRN.AI_TRN 
   AND TR_LTM_RTL_TRN.ID_ITM = AS_ITM.ID_ITM 
   AND AS_ITM.PRODUCT_NUM = RULE.PRODUCT_CD 
   AND RK_PAY_TRN.AI_TRN = TR_TRN.AI_TRN 
   AND TR_TRN.TS_TRN_PRC BETWEEN RULE.START_DATE AND RULE.END_DATE 
   AND TR_TRN.ID_STR_RT = PA_PRTY.ID_PRTY 
   AND RULE.CD_CO = PA_PRTY.ED_CO 
   AND RULE.RECORD_TYPE = 'PRO' 
   AND TR_TRN.ID_STR_RT  = PA_STR_RTL.ID_STR_RT 
   GROUP BY PRIORITY ,PRODUCT_CD, RULE.RECORD_TYPE,RK_PAY_TRN.CUST_ID, PA_PRTY.ED_CO,TR_TRN.ID_STR_RT,PA_STR_RTL.ID_CMY);


