
DROP TABLE MA_ITM_TMP_PRC_CHN CASCADE CONSTRAINTS;

DROP TABLE TR_CHN_TMP_PRC CASCADE CONSTRAINTS;

DROP TABLE AS_TR CASCADE CONSTRAINTS;

DROP TABLE AS_ITM_BLK CASCADE CONSTRAINTS;

DROP TABLE AS_ITM_STK CASCADE CONSTRAINTS;

DROP TABLE CO_TH_MPR_UN CASCADE CONSTRAINTS;

DROP TABLE RU_DS CASCADE CONSTRAINTS;

DROP TABLE rk_sales_summary CASCADE CONSTRAINTS;

DROP TABLE rk_rtn_pos_ln_itm CASCADE CONSTRAINTS;

DROP TABLE rk_reduction CASCADE CONSTRAINTS;

DROP TABLE rk_pos_ln_itm_dtl CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_GF_CF CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_RTL_TRN CASCADE CONSTRAINTS;

DROP TABLE rk_transfer_ln_itm CASCADE CONSTRAINTS;

DROP TABLE rk_lot_trn CASCADE CONSTRAINTS;

DROP TABLE rk_lot CASCADE CONSTRAINTS;

DROP TABLE CO_ASCTN_RLTD_ITM CASCADE CONSTRAINTS;

DROP TABLE rk_comp_prm_pk CASCADE CONSTRAINTS;

DROP TABLE rk_prm_itm CASCADE CONSTRAINTS;

DROP TABLE LE_PRC_SPL_CT_TYP CASCADE CONSTRAINTS;

DROP TABLE ID_IDN_PS CASCADE CONSTRAINTS;

DROP TABLE AS_ITM_RTL_STR CASCADE CONSTRAINTS;

DROP TABLE AS_ITM CASCADE CONSTRAINTS;

DROP TABLE ID_DPT_PS CASCADE CONSTRAINTS;

DROP TABLE MA_ITM_PRN_PRC_ITM CASCADE CONSTRAINTS;

DROP TABLE TR_CHN_PRN_PRC CASCADE CONSTRAINTS;

DROP TABLE CO_EV_MNT CASCADE CONSTRAINTS;

DROP TABLE LE_HST_ITM_SLS_PRC CASCADE CONSTRAINTS;

DROP TABLE MA_PRC_ITM CASCADE CONSTRAINTS;

DROP TABLE CO_MNT_ITM CASCADE CONSTRAINTS;

DROP TABLE MA_UPDT_ITM_DSCR CASCADE CONSTRAINTS;

DROP TABLE MA_DLT_ITM CASCADE CONSTRAINTS;

DROP TABLE MA_CRT_ITM CASCADE CONSTRAINTS;

DROP TABLE CO_EV CASCADE CONSTRAINTS;

DROP TABLE rk_prm_pk_amt CASCADE CONSTRAINTS;

DROP TABLE rk_prm_pk_pe CASCADE CONSTRAINTS;

DROP TABLE rk_prm_mb CASCADE CONSTRAINTS;

DROP TABLE rk_prm_pk CASCADE CONSTRAINTS;

DROP TABLE rk_prm_it CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_GF_CF_TND CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_CHK_TND CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_CRDB_CRD_TN CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_TND CASCADE CONSTRAINTS;

DROP TABLE CO_CLS_TND CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_CPN_TND CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_SLS_RTN CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_EM__DSC CASCADE CONSTRAINTS;

DROP TABLE TR_LTM_DSC CASCADE CONSTRAINTS;

DROP TABLE TR_DSC CASCADE CONSTRAINTS;

DROP TABLE rk_time_range CASCADE CONSTRAINTS;

DROP TABLE rk_time_range_type CASCADE CONSTRAINTS;

DROP TABLE rk_shift CASCADE CONSTRAINTS;

DROP TABLE rk_schedule CASCADE CONSTRAINTS;

DROP TABLE rk_emp_rsc_rol CASCADE CONSTRAINTS;

DROP TABLE rk_role CASCADE CONSTRAINTS;

DROP TABLE rk_emp_rsc_rol_ty CASCADE CONSTRAINTS;

DROP TABLE rk_emp_rsc CASCADE CONSTRAINTS;

DROP TABLE rk_timecard_ben CASCADE CONSTRAINTS;

DROP TABLE rk_timecard_mod CASCADE CONSTRAINTS;

DROP TABLE rk_timecard CASCADE CONSTRAINTS;

DROP TABLE rk_emp_timecard CASCADE CONSTRAINTS;

DROP TABLE rk_emp_sale CASCADE CONSTRAINTS;

DROP TABLE rk_emp_gl_ch_dt CASCADE CONSTRAINTS;

DROP TABLE rk_emp_goal CASCADE CONSTRAINTS;

DROP TABLE rk_txn_ty_sum CASCADE CONSTRAINTS;

DROP TABLE rk_pay_sum CASCADE CONSTRAINTS;

DROP TABLE ST_EM_ASGMT CASCADE CONSTRAINTS;

DROP TABLE rk_id_doc CASCADE CONSTRAINTS;

DROP TABLE rk_i9_form CASCADE CONSTRAINTS;

DROP TABLE rk_vac_req_date CASCADE CONSTRAINTS;

DROP TABLE rk_vac_req_form CASCADE CONSTRAINTS;

DROP TABLE rk_w4_form CASCADE CONSTRAINTS;

DROP TABLE rk_emp_form CASCADE CONSTRAINTS;

DROP TABLE ST_ASGMT_EM_STR CASCADE CONSTRAINTS;

DROP TABLE CO_ACS_PSWD CASCADE CONSTRAINTS;

DROP TABLE PA_OPR CASCADE CONSTRAINTS;

DROP TABLE PA_EM CASCADE CONSTRAINTS;

DROP TABLE rk_emp_status CASCADE CONSTRAINTS;

DROP TABLE rk_redm_bybk CASCADE CONSTRAINTS;

DROP TABLE rk_no_sale CASCADE CONSTRAINTS;

DROP TABLE rk_lay_pay CASCADE CONSTRAINTS;

DROP TABLE rk_lay_rts CASCADE CONSTRAINTS;

DROP TABLE rk_paid_out CASCADE CONSTRAINTS;

DROP TABLE rk_collection CASCADE CONSTRAINTS;

DROP TABLE rk_lay_pay_info CASCADE CONSTRAINTS;

DROP TABLE rk_lay CASCADE CONSTRAINTS;

DROP TABLE rk_pos_lay CASCADE CONSTRAINTS;

DROP TABLE rk_ship_req CASCADE CONSTRAINTS;

DROP TABLE TR_RTL CASCADE CONSTRAINTS;

DROP TABLE rk_void_trn CASCADE CONSTRAINTS;

DROP TABLE rk_pay_trn CASCADE CONSTRAINTS;

DROP TABLE rk_related_emp CASCADE CONSTRAINTS;

DROP TABLE rk_id_doc_type CASCADE CONSTRAINTS;

DROP TABLE rk_form_type CASCADE CONSTRAINTS;

DROP TABLE rk_emp_reference CASCADE CONSTRAINTS;

DROP TABLE rk_emp_history CASCADE CONSTRAINTS;

DROP TABLE rk_emp_app_form CASCADE CONSTRAINTS;

DROP TABLE rk_void_transfer CASCADE CONSTRAINTS;

DROP TABLE rk_transfer_in CASCADE CONSTRAINTS;

DROP TABLE rk_transfer_out CASCADE CONSTRAINTS;

DROP TABLE rk_transfer CASCADE CONSTRAINTS;

DROP TABLE rk_eod CASCADE CONSTRAINTS;

DROP TABLE rk_sos CASCADE CONSTRAINTS;

DROP TABLE TR_TRN CASCADE CONSTRAINTS;

DROP TABLE AS_TL CASCADE CONSTRAINTS;

DROP TABLE CO_PST CASCADE CONSTRAINTS;

DROP TABLE CO_PLN_EM_CMN CASCADE CONSTRAINTS;

DROP TABLE LE_ACNT_STR_FN CASCADE CONSTRAINTS;

DROP TABLE ST_JOB CASCADE CONSTRAINTS;

DROP TABLE LO_ADS_LCN_PHY CASCADE CONSTRAINTS;

DROP TABLE LO_LCN_PHY CASCADE CONSTRAINTS;

DROP TABLE LO_CRDN_TYP CASCADE CONSTRAINTS;

DROP TABLE LO_PH CASCADE CONSTRAINTS;

DROP TABLE LO_PH_TYP CASCADE CONSTRAINTS;

DROP TABLE rk_str_gl_chg_date CASCADE CONSTRAINTS;

DROP TABLE rk_str_goal CASCADE CONSTRAINTS;

DROP TABLE PA_STR_RTL CASCADE CONSTRAINTS;

DROP TABLE PA_PRS CASCADE CONSTRAINTS;

DROP TABLE CO_CTAF CASCADE CONSTRAINTS;

DROP TABLE PA_KY_CT CASCADE CONSTRAINTS;

DROP TABLE PA_CT CASCADE CONSTRAINTS;

DROP TABLE LO_ADS_PRTY CASCADE CONSTRAINTS;

DROP TABLE PA_RO_PRTY CASCADE CONSTRAINTS;

DROP TABLE PA_RO_PRTY_TYP CASCADE CONSTRAINTS;

DROP TABLE LO_EML_ADS CASCADE CONSTRAINTS;

DROP TABLE PA_PRTY CASCADE CONSTRAINTS;

DROP TABLE ST_ORGN_STRC CASCADE CONSTRAINTS;

DROP TABLE PA_ORGN CASCADE CONSTRAINTS;

DROP TABLE LO_ADS_NSTD CASCADE CONSTRAINTS;

DROP TABLE LO_ADS CASCADE CONSTRAINTS;

DROP TABLE CO_TYP_TRN CASCADE CONSTRAINTS;

DROP TABLE rk_pos_ln_itm_typ CASCADE CONSTRAINTS;

DROP TABLE rk_redm_hist CASCADE CONSTRAINTS;

DROP TABLE DO_CF_GF CASCADE CONSTRAINTS;

DROP TABLE CO_CLS_GF_CF CASCADE CONSTRAINTS;

DROP TABLE rk_holiday CASCADE CONSTRAINTS;

DROP TABLE PA_GP_CT CASCADE CONSTRAINTS;

DROP TABLE RU_PRDV_ITM CASCADE CONSTRAINTS;

DROP TABLE rk_prm_mu CASCADE CONSTRAINTS;

DROP TABLE RU_PRM_PRDV CASCADE CONSTRAINTS;

DROP TABLE RU_PRDV CASCADE CONSTRAINTS;

DROP TABLE CO_PRM CASCADE CONSTRAINTS;

DROP TABLE rk_th_prm CASCADE CONSTRAINTS;

DROP TABLE CO_CFG_BTTN CASCADE CONSTRAINTS;

DROP TABLE CO_ITM_CFG CASCADE CONSTRAINTS;

DROP TABLE CO_STR_CFG CASCADE CONSTRAINTS;

DROP TABLE CO_CFG CASCADE CONSTRAINTS;

DROP TABLE CO_CFG_CPN CASCADE CONSTRAINTS;

DROP TABLE CO_CFG_MNY_ORD CASCADE CONSTRAINTS;

DROP TABLE CO_CFG_PY_IN_OT CASCADE CONSTRAINTS;

DROP TABLE CO_CFG_PDT_RST CASCADE CONSTRAINTS;

DROP TABLE CO_CFG_SPR_PY_TYP CASCADE CONSTRAINTS;

DROP TABLE CO_CFG_TND_TYP CASCADE CONSTRAINTS;

DROP TABLE CO_UOM CASCADE CONSTRAINTS;


