CREATE TABLE ARM_EOD_GROUP
(
	CD_GROUP VARCHAR2(50),
	DE_GROUP VARCHAR2(100)
);

ALTER TABLE ARM_EOD_GROUP
ADD PRIMARY KEY (CD_GROUP);

CREATE TABLE ARM_EOD_DTL
(
	AI_TRN VARCHAR2(128),
	CD_GROUP VARCHAR2(50),
	CD_TYPE  VARCHAR2(50),
	TOTAL VARCHAR2(75),
	COUNT NUMBER(3)
);

ALTER TABLE ARM_EOD_DTL
ADD PRIMARY KEY (AI_TRN, CD_GROUP, CD_TYPE);
 
ALTER TABLE ARM_EOD_DTL
ADD FOREIGN KEY (AI_TRN) REFERENCES RK_EOD(AI_TRN);

ALTER TABLE ARM_EOD_DTL
ADD FOREIGN KEY (CD_GROUP) REFERENCES ARM_EOD_GROUP(CD_GROUP);


alter table RK_SHIP_REQ add ADS_FORMAT varchar2(40);

alter table LO_ADS_NSTD add ADS_FORMAT varchar2(40);


update LO_ADS_NSTD set ADS_FORMAT=MU_NM, MU_NM=null;