CREATE TABLE ARM_TAX_FREE (
    STORE_CODE          VARCHAR2(20) NOT NULL,
    DETAX_CODE          VARCHAR2(50) NOT NULL,
    DESC_CODE           VARCHAR2(50),
    RATIO               NUMBER(9,2),
    START_DATE          DATE NOT NULL,
    NET_MIN_VALUE       VARCHAR2(75),
    GROSS_MIN_VALUE     VARCHAR2(75),
    PAYMENT_CODE        VARCHAR2(20),
    MIN_PRICE           VARCHAR2(75),
    MAX_PRICE           VARCHAR2(75),
    MIN_AMOUNT          VARCHAR2(75),
    MAX_AMOUNT          VARCHAR2(75),
    REFUND_AMOUNT       VARCHAR2(75),
    REFUND_PERCENT      VARCHAR2(10),
    COMMISSION          VARCHAR2(20)
);

ALTER TABLE ARM_TAX_FREE ADD PRIMARY KEY (STORE_CODE, DETAX_CODE, START_DATE);

CREATE TABLE ARM_FISCAL_DOC_NO (
    REGISTER_ID         VARCHAR2(10) NOT NULL,
    ID_STR_RT           VARCHAR2(20) NOT NULL,
    LAST_DDT_NO         VARCHAR2(20),
    LAST_VAT_NO         VARCHAR2(20),
    LAST_CREDIT_NOTE    VARCHAR2(20)
);

ALTER TABLE ARM_FISCAL_DOC_NO ADD PRIMARY KEY (REGISTER_ID, ID_STR_RT);

ALTER TABLE ARM_FISCAL_DOC_NO ADD FOREIGN KEY (REGISTER_ID, ID_STR_RT) REFERENCES AS_TL(ID_RPSTY_TND, ID_STR_RT);

CREATE TABLE ARM_POS_RSV ( 
  AI_TRN          VARCHAR2 (128)  NOT NULL, 
  ID_RESERVATION  VARCHAR2 (128),
  EXP_DT          DATE,
  REASON_CODE     VARCHAR2(20),
  DEPOSIT_AMT	  VARCHAR2(75),
  ORIG_RSV_ID	  VARCHAR2(128)
); 

ALTER TABLE ARM_POS_RSV ADD PRIMARY KEY (ID_RESERVATION);

ALTER TABLE ARM_POS_RSV ADD FOREIGN KEY (ORIG_RSV_ID) REFERENCES ARM_POS_RSV(ID_RESERVATION);

ALTER TABLE ARM_POS_RSV ADD FOREIGN KEY (AI_TRN) REFERENCES TR_RTL (AI_TRN);

CREATE TABLE ARM_RSV_LN_ITM_DTL ( 
  AI_TRN          VARCHAR2 (128)  NOT NULL, 
  AI_LN_ITM       NUMBER        NOT NULL, 
  SEQUENCE_NUM    NUMBER (3)    NOT NULL, 
  ORG_AI_TRN      VARCHAR2 (128), 
  ORIG_AI_LN_ITM  NUMBER, 
  ORIG_SEQ_NUM    NUMBER (3)
); 

ALTER TABLE ARM_RSV_LN_ITM_DTL ADD PRIMARY KEY ( AI_TRN, AI_LN_ITM, SEQUENCE_NUM );

ALTER TABLE ARM_RSV_LN_ITM_DTL ADD 
  FOREIGN KEY (AI_TRN,AI_LN_ITM,SEQUENCE_NUM) REFERENCES RK_POS_LN_ITM_DTL (AI_TRN,AI_LN_ITM,SEQUENCE_NUMBER);

ALTER TABLE ARM_RSV_LN_ITM_DTL ADD 
  FOREIGN KEY (ORG_AI_TRN,ORIG_AI_LN_ITM,ORIG_SEQ_NUM) REFERENCES RK_POS_LN_ITM_DTL (AI_TRN,AI_LN_ITM,SEQUENCE_NUMBER);


CREATE TABLE ARM_FISCAL_DOCUMENT (
	AI_TRN		VARCHAR2(128) NOT NULL,
	DOC_NUM		VARCHAR2(20) NOT NULL,
	TY_DOC		VARCHAR2(10) NOT NULL,
	REFUND_AMOUNT   VARCHAR2(50),
	VAT_NUM		VARCHAR2(50),
	DESTINATION	VARCHAR2(50),
	TY_PKG		VARCHAR2(50),
	WEIGHT		NUMBER(5,2),
	NOTE		VARCHAR2(100),
	COMPANY_NAME    VARCHAR2(50) NOT NULL,
	COMPANY_NAME2   VARCHAR2(50) NOT NULL,
	ADDRESS_LINE_1  VARCHAR2(50) NOT NULL,
	ADDRESS_LINE_2  VARCHAR2(50),
	CITY		VARCHAR2(50) NOT NULL,
	COUNTY		VARCHAR2(50) NOT NULL,
	ZIP_CODE	VARCHAR2(10) NOT NULL,
	STATE		VARCHAR2(50) NOT NULL,
	COUNTRY		VARCHAR2(50) NOT NULL,
	CD_DEST		VARCHAR2(10),
	SENDER		VARCHAR2(10),
	CD_SENDER	VARCHAR2(10),
	TY_CARRIER	VARCHAR2(10),
	CD_EXPEDITION   VARCHAR2(10),
	GOODS_NUM	VARCHAR2(50),
	CD_CARRIER	VARCHAR2(10),
	DE_CARRIER	VARCHAR2(50),
	TY_PACKAGE	VARCHAR2(10),
	TY_PAYMENT	VARCHAR2(10)
);

ALTER TABLE ARM_FISCAL_DOCUMENT
ADD PRIMARY KEY (AI_TRN, DOC_NUM);


CREATE TABLE ARM_ASIS_TXN_DATA (
	AI_TRN			VARCHAR2(128) NOT NULL,
	COMPANY_CODE		VARCHAR2(20),
	STORE_ID		VARCHAR2(20),
	REGISTER_ID		VARCHAR2(20),
	TXN_NO			VARCHAR2(50),
	TXN_DATE		VARCHAR2(25),
	FISCAL_RECEIPT_NO	VARCHAR2(20),
	FISCAL_RECEIPT_DATE	VARCHAR2(25),
	FISCAL_DOC_NO		VARCHAR2(20),
	FISCAL_DOC_DATE		VARCHAR2(25),
	FISCAL_DOC_TYPE		VARCHAR2(20),
	CUSTOMER_NO		VARCHAR2(20),
	CUSTOMER_NAME		VARCHAR2(50),
	COMMENTS		VARCHAR2(200)
);

ALTER TABLE ARM_ASIS_TXN_DATA
ADD FOREIGN KEY (AI_TRN) REFERENCES TR_TRN(AI_TRN);

ALTER TABLE TR_LTM_RTL_TRN
ADD ( ST_EXCHANGE VARCHAR2(2),
DOC_NUM VARCHAR2(10),
VAT_COMMENTS VARCHAR2(130)
);

ALTER TABLE TR_RTL 
ADD FISCAL_DOC_NUMBERS VARCHAR2(2000);

CREATE TABLE ARM_CUST_DEPOSIT_HIST
(     
  DC_TRANSACTION        DATE            NOT NULL,
  ID_STR_RT             VARCHAR2(128)   NOT NULL, 
  AI_TRN		VARCHAR2(128)   NOT NULL,
  TY_TRN		VARCHAR2(60)    NOT NULL,
  CUST_ID               VARCHAR2(128)   NOT NULL,
  ASSOC                 VARCHAR2(128),
  AMOUNT                VARCHAR2(75) 
   
);

ALTER TABLE ARM_CUST_DEPOSIT_HIST ADD FOREIGN KEY (CUST_ID) REFERENCES PA_CT(ID_CT);

ALTER TABLE PA_CT ADD CUST_BALANCE VARCHAR2(75);

ALTER TABLE TR_TRN
ADD (
	FISCAL_RECEIPT_NUMBER	VARCHAR2(128),
	FISCAL_RECEIPT_DATE	DATE
);
 
ALTER TABLE TR_LTM_RTL_TRN
ADD DOC_NUM VARCHAR2(20);

ALTER TABLE TR_LTM_RTL_TRN
ADD FOREIGN KEY (AI_TRN, DOC_NUM) REFERENCES ARM_FISCAL_DOCUMENT(AI_TRN, DOC_NUM);

ALTER TABLE TR_LTM_RTL_TRN
ADD FL_EXCHANGE DECIMAL(1);