ALTER TABLE TR_RTL
MODIFY ITEMS_IDS VARCHAR2(4000);

ALTER TABLE RK_SALES_SUMMARY
ADD (
	MARKDOWN_AMT	VARCHAR2(75),
	TYPE		CHAR(1)
);

CREATE OR REPLACE VIEW V_ARM_ITEM_SALE
(ID_STR_RT, DEPT_ID, DEPT_NM, CLASS_ID, CLASS_NM, 
 ITEM_ID, ITEM_NM, SALES_DATE, SALE_MARKDOWN_AMT, NET_SALE_AMT, 
 TOTAL_SALE_QTY, RTN_MARKDOWN_AMT, NET_RTN_AMT, TOTAL_RTN_QTY)
AS 
( 
SELECT SUMM.ID_STR_RT ID_STR_RT, ITEM.ID_DPT_POS DEPT_ID, DEPT.NM_DPT_POS DEPT_NM  , 
NVL(ITEM.ID_CLSS,'NONE') CLASS_ID, NVL(CLASS.NM_CLSS,'NONE') CLASS_NM, 
SUMM.ID_ITM ITEM_ID,  ITEMSTORE.NM_ITM ITEM_NM,SUMM.SALES_DATE SALES_DATE, 
NVL(SUMM.MARKDOWN_AMT,0)  SALE_MARKDOWN_AMT, 
NVL(SUMM.NET_AMOUNT,0) NET_SALE_AMT, 
TOTAL_QUANTITY TOTAL_SALE_QTY, 
 '0' RTN_MARKDOWN_AMT, 
'0' NET_RTN_AMT, 
 0 TOTAL_RTN_QTY 
FROM 
RK_SALES_SUMMARY SUMM, AS_ITM ITEM,  AS_ITM_RTL_STR ITEMSTORE, ID_DPT_PS DEPT,  ARM_CLASS CLASS 
WHERE SUMM.ID_ITM = ITEM.ID_ITM 
AND ITEM.ID_ITM = ITEMSTORE.ID_ITM  AND SUMM.ID_STR_RT = ITEMSTORE.ID_STR_RT 
AND ITEM.ID_DPT_POS = DEPT.ID_DPT_POS 
AND ITEM.ID_DPT_POS = CLASS.ID_DPT(+) 
AND ITEM.ID_CLSS = CLASS.ID_CLSS(+) 
AND NVL(SUMM.TYPE,'S') ='S' 
UNION ALL 
SELECT SUMM.ID_STR_RT ID_STR_RT, ITEM.ID_DPT_POS DEPT_ID, DEPT.NM_DPT_POS DEPT_NM  , 
NVL(ITEM.ID_CLSS,'NONE') CLASS_ID, NVL(CLASS.NM_CLSS,'NONE') CLASS_NM, 
SUMM.ID_ITM ITEM_ID,  ITEMSTORE.NM_ITM ITEM_NM, SUMM.SALES_DATE SALES_DATE, 
'0' SALE_MARKDOWN_AMT, 
'0' NET_SALE_AMT, 
0 TOTAL_SALE_QTY, 
NVL(SUMM.MARKDOWN_AMT,0)  RTN_MARKDOWN_AMT, 
NVL(SUMM.NET_AMOUNT,0) NET_RTN_AMT, 
TOTAL_QUANTITY TOTAL_RTN_QTY 
FROM 
RK_SALES_SUMMARY SUMM, AS_ITM ITEM,  AS_ITM_RTL_STR ITEMSTORE, ID_DPT_PS DEPT, ARM_CLASS CLASS 
WHERE SUMM.ID_ITM = ITEM.ID_ITM 
AND ITEM.ID_ITM = ITEMSTORE.ID_ITM  AND SUMM.ID_STR_RT = ITEMSTORE.ID_STR_RT 
AND ITEM.ID_DPT_POS = DEPT.ID_DPT_POS 
AND ITEM.ID_DPT_POS = CLASS.ID_DPT(+) 
AND ITEM.ID_CLSS = CLASS.ID_CLSS(+) 
AND NVL(SUMM.TYPE,'S') ='R' 
);


