CREATE OR REPLACE VIEW RK_TXN_HEADER ("CUST_ID",
    "TY_TRN","ID_STR_RT","TY_STR_RT","ID_OPR","TS_TRN_PRC",
    "TS_TRN_SBM","TY_GUI_TRN","PAY_TYPES","TOTAL_AMT","AI_TRN",
    "CONSULTANT_ID","REDUCTION_AMOUNT","NET_AMOUNT",
    "DISCOUNT_TYPES","ITEMS_IDS","REGISTER_ID","FN_PRS","LN_PRS",
    "EXP_DT","REF_ID","CURRENCY_CD","IS_SHIPPING") AS 
SELECT RK_PAY_TRN.CUST_ID, TR_TRN.TY_TRN, TR_TRN.ID_STR_RT, 
    PA_STR_RTL.ID_BRAND, OPR.ARM_EXTERNAL_ID ID_OPR, TR_TRN.TS_TRN_PRC, 
    TR_TRN.TS_TRN_SBM, TR_TRN.TY_GUI_TRN, RK_PAY_TRN.PAY_TYPES, 
    RK_PAY_TRN.TOTAL_AMT, RK_PAY_TRN.AI_TRN, ASSOCIATE.ARM_EXTERNAL_ID CONSULTANT_ID, 
    TR_RTL.REDUCTION_AMOUNT, TR_RTL.NET_AMOUNT, TR_RTL.DISCOUNT_TYPES, 
    TR_RTL.ITEMS_IDS, TR_TRN.ID_RPSTY_TND, PA_PRS.FN_PRS, PA_PRS.LN_PRS, 
    DECODE(RK_PAY_TRN.TYPE_ID, 'TRNPSO', ARM_POS_PRS.EXP_DT, 'TRNCGO', ARM_POS_CSG.EXP_DT, NULL) EXP_DT, 
    DECODE(RK_PAY_TRN.TYPE_ID, 'TRNPSO', ARM_POS_PRS.ID_PRESALE, 'TRNCGO', ARM_POS_CSG.ID_CONSIGNMENT, NULL) REF_ID, 
    PA_STR_RTL.TY_CNY CURRENCY_CD, DECODE(RK_SHIP_REQ.SEQ_NUM, NULL, 0, 1) IS_SHIPPING 
FROM TR_TRN INNER JOIN 
( 
 	 RK_PAY_TRN LEFT OUTER JOIN 
	 ( 
	 	 TR_RTL LEFT OUTER JOIN PA_PRS ON TR_RTL.CONSULTANT_ID = PA_PRS.ID_PRTY_PRS 
		 LEFT OUTER JOIN PA_EM ASSOCIATE ON TR_RTL.CONSULTANT_ID=ASSOCIATE.ID_EM 
		 LEFT OUTER JOIN RK_SHIP_REQ ON (RK_SHIP_REQ.AI_TRN=TR_RTL.AI_TRN AND RK_SHIP_REQ.SEQ_NUM=0) 
		 LEFT OUTER JOIN ARM_POS_PRS ON TR_RTL.AI_TRN = ARM_POS_PRS.AI_TRN 
		 LEFT OUTER JOIN ARM_POS_CSG ON TR_RTL.AI_TRN = ARM_POS_CSG.AI_TRN 
	 ) 
	 ON RK_PAY_TRN.AI_TRN = TR_RTL.AI_TRN 
) 
ON TR_TRN.AI_TRN=RK_PAY_TRN.AI_TRN AND TR_TRN.TY_TRN IN ('TRNPAY') 
INNER JOIN
(  
	PA_OPR INNER JOIN PA_EM OPR ON PA_OPR.ID_EM=OPR.ID_EM
)
ON TR_TRN.ID_OPR=PA_OPR.ID_EM
INNER JOIN PA_STR_RTL ON TR_TRN.ID_STR_RT=PA_STR_RTL.ID_STR_RT;

alter table tr_rtl modify discount_types varchar2(2000);


ALTER TABLE RK_SALES_SUMMARY
ADD (ITEM_DEPT_ID VARCHAR2(20),
ITEM_CLSS_ID VARCHAR2(20),
MISC_ITEM_ID VARCHAR2(20));

CREATE OR REPLACE VIEW "V_ARM_ITEM_SALE" ("ID_STR_RT",
    "DIV","DEPT_ID","DEPT_NM","CLASS_ID","CLASS_NM","ITEM_ID",
    "ITEM_NM","BARCODE","SALES_DATE","SALE_MARKDOWN_AMT",
    "NET_SALE_AMT","TOTAL_SALE_QTY","RTN_MARKDOWN_AMT",
    "NET_RTN_AMT","TOTAL_RTN_QTY") AS (  
SELECT SUMM.ID_STR_RT ID_STR_RT,  
	DECODE(TO_NUMBER(SUBSTR(SUMM.ITEM_DEPT_ID,1, 1)), '1', 'GAW', '2', 'GAM', '3', 'GAUJUN', '4', 'EAW', '5', 'EAM', '6', 'EAU', '7', 'ACGIFT', '8', 'ACTEXT', '9', 'ACTABLE', '99') DIV,  
	SUMM.ITEM_DEPT_ID DEPT_ID, DEPT.NM_DPT_POS DEPT_NM  , NVL(SUMM.ITEM_CLSS_ID,'NONE') CLASS_ID, NVL(CLASS.NM_CLSS,'NONE') CLASS_NM,  
	SUMM.ID_ITM ITEM_ID,  ITEMSTORE.NM_ITM ITEM_NM, DECODE(SUMM.MISC_ITEM_ID, NULL, ITEM.BARCODE, SUMM.MISC_ITEM_ID) BARCODE,  
	SUMM.SALES_DATE SALES_DATE,  
	NVL(SUMM.MARKDOWN_AMT,0)  SALE_MARKDOWN_AMT, NVL(SUMM.NET_AMOUNT,0) NET_SALE_AMT, TOTAL_QUANTITY TOTAL_SALE_QTY,  
	'0' RTN_MARKDOWN_AMT, '0' NET_RTN_AMT, 0 TOTAL_RTN_QTY  
FROM RK_SALES_SUMMARY SUMM, AS_ITM ITEM, AS_ITM_RTL_STR ITEMSTORE, ID_DPT_PS DEPT,  ARM_CLASS CLASS  
WHERE SUMM.ID_ITM = ITEM.ID_ITM  
	AND ITEM.ID_ITM = ITEMSTORE.ID_ITM  
	AND SUMM.ID_STR_RT = ITEMSTORE.ID_STR_RT  
	AND SUMM.ITEM_DEPT_ID = DEPT.ID_DPT_POS(+)  
	AND SUMM.ITEM_DEPT_ID = CLASS.ID_DPT(+)  
	AND SUMM.ITEM_CLSS_ID = CLASS.ID_CLSS(+)  
	AND NVL(SUMM.TYPE,'S') ='S'  
UNION ALL  
SELECT SUMM.ID_STR_RT ID_STR_RT,  
	DECODE(TO_NUMBER(SUBSTR(SUMM.ITEM_DEPT_ID,1, 1)), '1', 'GAW', '2', 'GAM', '3', 'GAUJUN', '4', 'EAW', '5', 'EAM', '6', 'EAU', '7', 'ACGIFT', '8', 'ACTEXT', '9', 'ACTABLE', '99') DIV,  
	SUMM.ITEM_DEPT_ID DEPT_ID, DEPT.NM_DPT_POS DEPT_NM  , NVL(SUMM.ITEM_CLSS_ID,'NONE') CLASS_ID, NVL(CLASS.NM_CLSS,'NONE') CLASS_NM,  
	SUMM.ID_ITM ITEM_ID,  ITEMSTORE.NM_ITM ITEM_NM, DECODE(SUMM.MISC_ITEM_ID, NULL, ITEM.BARCODE, SUMM.MISC_ITEM_ID) BARCODE,  
	SUMM.SALES_DATE SALES_DATE,  
	'0' SALE_MARKDOWN_AMT, '0' NET_SALE_AMT, 0 TOTAL_SALE_QTY, NVL(SUMM.MARKDOWN_AMT,0)  RTN_MARKDOWN_AMT,  
	NVL(SUMM.NET_AMOUNT,0) NET_RTN_AMT, TOTAL_QUANTITY TOTAL_RTN_QTY  
FROM RK_SALES_SUMMARY SUMM, AS_ITM ITEM,  AS_ITM_RTL_STR ITEMSTORE, ID_DPT_PS DEPT, ARM_CLASS CLASS  
WHERE SUMM.ID_ITM = ITEM.ID_ITM  
	AND ITEM.ID_ITM = ITEMSTORE.ID_ITM  
	AND SUMM.ID_STR_RT = ITEMSTORE.ID_STR_RT  
	AND SUMM.ITEM_DEPT_ID = DEPT.ID_DPT_POS(+)  
	AND SUMM.ITEM_DEPT_ID = CLASS.ID_DPT(+)  
	AND SUMM.ITEM_CLSS_ID = CLASS.ID_CLSS(+)  
	AND NVL(SUMM.TYPE,'S') ='R'  
);

CREATE TABLE "ARM_CT_CRDB_CRD_DTL" (
"ID_CT" VARCHAR2(20),
"ID_STR_RT" VARCHAR2(20), 
"ID_ACNT_DB_CR_CRD" VARCHAR2(100),
"EXPIRATION_DATE" DATE,
"ZIP_CODE" VARCHAR2(10),
"TY_CRD" VARCHAR2(20)
); 