CREATE SEQUENCE ARM_SEQ_CSG_PRS_ID
  START WITH 10000000
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE ARM_CSG_POS_LN_ITM_DTL
ADD FL_VD_LN_ITM CHAR(1) DEFAULT 0;

ALTER TABLE ARM_PRS_POS_LN_ITM_DTL
ADD FL_VD_LN_ITM CHAR(1) DEFAULT 0;
