ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_SPR) REFERENCES ARM_SPR;

ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_COLOR) REFERENCES ARM_COLOR;

ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_DPT_PoS, ID_CLSS) REFERENCEs ARM_CLASS;

ALTER TABLE ARM_SUBCLASS ADD FOREIGN KEY (ID_DPT, ID_CLSS) REFERENCES ARM_CLASS;

ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_DPT_POS, ID_CLSS, ID_SBCL) REFERENCES ARM_SUBCLASS;

ALTER TABLE ID_IDN_PS
ADD FOREIGN KEY (ID_ITM, ID_STR_RT) REFERENCES AS_ITM_RTL_STR;

ALTER TABLE ARM_ITM_HIST
ADD FOREIGN KEY (ID_ITM, ID_STR_RT) REFERENCES AS_ITM_RTL_STR;

ALTER TABLE RK_COMP_PRM_PK
ADD FOREIGN KEY (ID_ITM, ID_STR_RT, CURRENCY_CODE, ID_RU_PRDV)
                             REFERENCES RK_PRM_ITM;

ALTER TABLE TR_LTM_DSC_DTL ADD FOREIGN KEY (AI_TRN,DSC_SEQ_NUM) REFERENCES TR_LTM_DSC(AI_TRN,AI_LN_ITM);

ALTER TABLE TR_LTM_DSC_DTL ADD FOREIGN KEY (AI_TRN, AL_LN_ITM) REFERENCES TR_LTM_RTL_TRN (AI_TRN,AI_LN_ITM);

ALTER TABLE ARM_POS_PRS ADD FOREIGN KEY (AI_TRN) REFERENCES TR_RTL (AI_TRN);

ALTER TABLE ARM_PRS_POS_LN_ITM_DTL ADD 
  FOREIGN KEY (AI_TRN,AI_LN_ITM,SEQUENCE_NUM) REFERENCES RK_POS_LN_ITM_DTL (AI_TRN,AI_LN_ITM,SEQUENCE_NUMBER);

ALTER TABLE ARM_PRS_POS_LN_ITM_DTL ADD 
  FOREIGN KEY (ORG_AI_TRN,ORIG_AI_LN_ITM,ORIG_SEQ_NUM) REFERENCES RK_POS_LN_ITM_DTL (AI_TRN,AI_LN_ITM,SEQUENCE_NUMBER);

ALTER TABLE ARM_POS_CSG ADD FOREIGN KEY (AI_TRN) REFERENCES TR_RTL (AI_TRN);

ALTER TABLE ARM_CSG_POS_LN_ITM_DTL ADD 
  FOREIGN KEY (AI_TRN,AI_LN_ITM,SEQUENCE_NUM) REFERENCES RK_POS_LN_ITM_DTL (AI_TRN,AI_LN_ITM,SEQUENCE_NUMBER);

ALTER TABLE ARM_CSG_POS_LN_ITM_DTL ADD 
  FOREIGN KEY (ORG_AI_TRN,ORIG_AI_LN_ITM,ORIG_SEQ_NUM) REFERENCES RK_POS_LN_ITM_DTL (AI_TRN,AI_LN_ITM,SEQUENCE_NUMBER);

ALTER TABLE ARM_ITM_SOH ADD FOREIGN KEY (ITEM_ID, STORE_ID) REFERENCES AS_ITM_RTL_STR(ID_ITM, ID_STR_RT);

ALTER TABLE ARM_CT_DTL ADD FOREIGN KEY (ID_CT) REFERENCES PA_CT(ID_CT);

ALTER TABLE ARM_ADS_PH ADD FOREIGN KEY (ID_ADS) REFERENCES LO_ADS_NSTD(ID_ADS);

ALTER TABLE ARM_CT_ASSOC ADD FOREIGN KEY (ID_CT) REFERENCES PA_CT(ID_CT);

ALTER TABLE ARM_CT_COMMENTS ADD FOREIGN KEY (ID_CT) REFERENCES PA_CT(ID_CT);

ALTER TABLE ARM_ALTERN_LN_ITM_DTL ADD FOREIGN KEY (AI_TRN, AI_LN_ITM, DET_SEQ_NUM) 
REFERENCES RK_POS_LN_ITM_DTL (AI_TRN, AI_LN_ITM, SEQUENCE_NUMBER);

ALTER TABLE ARM_ALTERN_DTL ADD FOREIGN KEY (AI_TRN, AI_LN_ITM, DET_SEQ_NUM, ALTERN_SEQ_NUM) 
REFERENCES ARM_ALTERN_LN_ITM_DTL (AI_TRN, AI_LN_ITM, DET_SEQ_NUM, SEQ_NUM);

ALTER TABLE ARM_FISCAL_DOC_NO ADD FOREIGN KEY (REGISTER_ID, ID_STR_RT) REFERENCES AS_TL(ID_RPSTY_TND, ID_STR_RT);

ALTER TABLE ARM_POS_RSV ADD FOREIGN KEY (ORIG_RSV_ID) REFERENCES ARM_POS_RSV(ID_RESERVATION);

ALTER TABLE ARM_POS_RSV ADD FOREIGN KEY (AI_TRN) REFERENCES TR_RTL (AI_TRN);

ALTER TABLE ARM_RSV_POS_LN_ITM_DTL ADD 
  FOREIGN KEY (AI_TRN,AI_LN_ITM,SEQUENCE_NUM) REFERENCES RK_POS_LN_ITM_DTL (AI_TRN,AI_LN_ITM,SEQUENCE_NUMBER);

ALTER TABLE ARM_RSV_POS_LN_ITM_DTL ADD 
  FOREIGN KEY (ORG_AI_TRN,ORIG_AI_LN_ITM,ORIG_SEQ_NUM) REFERENCES RK_POS_LN_ITM_DTL (AI_TRN,AI_LN_ITM,SEQUENCE_NUMBER);

ALTER TABLE ARM_ASIS_TXN_DATA
ADD FOREIGN KEY (AI_TRN) REFERENCES TR_TRN(AI_TRN);

ALTER TABLE ARM_CUST_DEPOSIT_HIST ADD FOREIGN KEY (CUST_ID) REFERENCES PA_CT(ID_CT);

ALTER TABLE TR_LTM_RTL_TRN
ADD FOREIGN KEY (AI_TRN, DOC_NUM, TY_DOC) REFERENCES ARM_FISCAL_DOCUMENT(AI_TRN, DOC_NUM, TY_DOC);

ALTER TABLE ARM_EOD_DTL
ADD FOREIGN KEY (AI_TRN) REFERENCES RK_EOD(AI_TRN);

ALTER TABLE ARM_EOD_DTL
ADD FOREIGN KEY (CD_GROUP) REFERENCES ARM_EOD_GROUP(CD_GROUP);

ALTER TABLE ARM_ALTERN_CLSS_GRP
ADD  ( FOREIGN KEY (GROUP_ID)
REFERENCES ARM_ALTERN_GRP) ;

ALTER TABLE ARM_ALTERN_CODE
ADD  ( FOREIGN KEY (GROUP_ID)
REFERENCES ARM_ALTERN_GRP) ;


