ALTER TABLE AS_ITM
ADD (
      ID_BRN  VARCHAR2(6),
      BARCODE VARCHAR2(50),
      STYLE_NUM VARCHAR2(10),
      ID_COLOR VARCHAR2(6),
      ID_SPR   VARCHAR2(10),
      ID_SIZE  VARCHAR2(6),
      ID_KIDS_SIZE  VARCHAR2(6),
      MODEL VARCHAR2(10),
      FABRIC VARCHAR2(10),
      GENDER VARCHAR2(10),
      SUBLINE VARCHAR2(30),
      VARIANT VARCHAR2(30),
      LABEL VARCHAR2(30),
      ITEM_DROP VARCHAR2(30),
      CATEGORY VARCHAR2(50),
      PRODUCT_NUM VARCHAR2(50),
      ID_SEASON   VARCHAR2(10)
);

CREATE TABLE ARM_BRN
(
	ID_BRN	VARCHAR2(6),
	NM_BRN	VARCHAR2(30),
	ED_CO	VARCHAR2(20),
	ED_LA	VARCHAR2(20)
);

ALTER TABLE ARM_BRN ADD PRIMARY KEY (ID_BRN, ED_CO, ED_LA);

CREATE TABLE ARM_SPR
(
	ID_SPR VARCHAR2(10),
	NM_SPR VARCHAR2(30)
);

ALTER TABLE ARM_SPR ADD PRIMARY KEY (ID_SPR);

ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_SPR) REFERENCES ARM_SPR;

CREATE TABLE ARM_SEASON
(
	ID_SEASON VARCHAR2(6),
	DE_SEASON VARCHAR2(30),
	ED_CO	VARCHAR2(20),
	ED_LA	VARCHAR2(20)
);

ALTER TABLE ARM_SEASON ADD PRIMARY KEY (ID_SEASON, ED_CO, ED_LA);

CREATE TABLE ARM_SIZE
(
	ID_SIZE VARCHAR2(6),
	DE_SIZE VARCHAR2(30),
	SIZE_INDEX VARCHAR2(10),
	EXT_SIZE_INDEX VARCHAR2(10),
	ED_CO	VARCHAR2(20),
	ED_LA	VARCHAR2(20)
);

ALTER TABLE ARM_SIZE ADD PRIMARY KEY (ID_SIZE, ED_CO, ED_LA);

CREATE TABLE ARM_KIDS_SIZE
(
	ID_SIZE VARCHAR2(6),
	DE_SIZE VARCHAR2(30),
	ED_CO	VARCHAR2(20),
	ED_LA	VARCHAR2(20)
);

CREATE TABLE ARM_COLOR
(
	ID_COLOR VARCHAR2(6),
	DE_COLOR VARCHAR2(30)
);

ALTER TABLE ARM_COLOR ADD PRIMARY KEY (ID_COLOR);

ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_COLOR) REFERENCES ARM_COLOR;

CREATE TABLE ARM_CLASS
(
	ID_DPT VARCHAR2(128),
	ID_CLSS VARCHAR2(128),
	NM_CLSS VARCHAR2(10)
);

ALTER TABLE ARM_CLASS ADD PRIMARY KEY (ID_DPT, ID_CLSS);

ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_DPT_PoS, ID_CLSS) REFERENCEs ARM_CLASS;

CREATE TABLE ARM_SUBCLASS
(
	ID_DPT VARCHAR2(128),
	ID_CLSS VARCHAR2(128),
	ID_SBCL VARCHAR2(128),
	NM_SBCL VARCHAR2(20)
);

ALTER TABLE ARM_SUBCLASS ADD PRIMARY KEY (ID_DPT, ID_CLSS, ID_SBCL);

ALTER TABLE ARM_SUBCLASS ADD FOREIGN KEY (ID_DPT, ID_CLSS) REFERENCES ARM_CLASS;

ALTER TABLE AS_ITM ADD FOREIGN KEY (ID_DPT_POS, ID_CLSS, ID_SBCL) REFERENCES ARM_SUBCLASS;

CREATE TABLE ARM_LABEL
(
	ID_LABEL VARCHAR2(30),
	NM_LABEL VARCHAR2(30),
	ED_CO VARCHAR2(20),
	ED_LA VARCHAR2(20)
);

ALTER TABLE ARM_LABEL ADD PRIMARY KEY (ID_LABEL, ED_CO, ED_LA);

CREATE TABLE ARM_SUBLINE
(
	ID_SUBLINE VARCHAR2(30),
	DE_SUBLINE VARCHAR2(30),
	ED_CO	VARCHAR2(20),
	ED_LA	VARCHAR2(20)
);

ALTER TABLE ARM_SUBLINE ADD PRIMARY KEY (ID_SUBLINE, ED_CO, ED_LA);

CREATE TABLE ARM_GENDER
(
	ID_GENDER VARCHAR2(30),
	DE_GENDER VARCHAR2(30),
	ED_CO	VARCHAR2(20),
	ED_LA	VARCHAR2(20)
);

ALTER TABLE ARM_GENDER ADD PRIMARY KEY (ID_GENDER, ED_CO, ED_LA);

CREATE TABLE ARM_CATEGORY
(
	ID_CATEGORY VARCHAR2(30),
	NM_CATEGORY VARCHAR2(30),
	ED_CO	VARCHAR2(20),
	ED_LA	VARCHAR2(20)
);

ALTER TABLE ARM_CATEGORY ADD PRIMARY KEY (ID_CATEGORY, ED_CO, ED_LA);

CREATE TABLE ARM_DROP
(
	ID_DROP VARCHAR2(30),
	DE_DROP VARCHAR2(30),
	ED_CO	VARCHAR2(20),
	ED_LA	VARCHAR2(20)
);

ALTER TABLE ARM_DROP ADD PRIMARY KEY (ID_DROP, ED_CO, ED_LA);

CREATE TABLE ARM_PRODUCT
(
	ID_PRODUCT VARCHAR2(30),
	DE_PRODUCT VARCHAR2(30)
);

ALTER TABLE ARM_PRODUCT ADD PRIMARY KEY (ID_PRODUCT);

CREATE TABLE ARM_ITM_HIST
(
        ID_ITM VARCHAR2(128),
        ID_STR_RT VARCHAR2(128),
        ID_ITM_HIST VARCHAR2(128),
        KEY VARCHAR2(25),
        VALUE VARCHAr2(255),
        EFFECTIVE_DT DATE,
        EXPIRATION_DT DATE
);

ALTER TABLE AS_ITM_RTL_STR
ADD (
      LU_EXM_TX VARCHAR2(2),
      UPDATE_DT DATE,
      NM_ITM VARCHAR2(40)	
);

ALTER TABLE AS_ITM_RTL_STR 
DROP PRIMARY KEY CASCADE;

ALTER TABLE AS_ITM_RTL_STR 
ADD PRIMARY KEY (ID_ITM, ID_STR_RT);

ALTER TABLE ID_IDN_PS
ADD (ID_STR_RT VARCHAR2(128));

ALTER TABLE ID_IDN_PS
ADD FOREIGN KEY (ID_ITM, ID_STR_RT) REFERENCES AS_ITM_RTL_STR;

ALTER TABLE ARM_ITM_HIST
ADD FOREIGN KEY (ID_ITM, ID_STR_RT) REFERENCES AS_ITM_RTL_STR;


ALTER TABLE RK_COMP_PRM_PK
ADD (ID_STR_RT VARCHAR2(128));

ALTER TABLE RK_PRM_ITM
DROP PRIMARY KEY CASCADE;

ALTER TABLE RK_PRM_ITM
ADD PRIMARY KEY (ID_ITM, ID_STR_RT, CURRENCY_CODE, ID_RU_PRDV);


ALTER TABLE RK_COMP_PRM_PK
ADD FOREIGN KEY (ID_ITM, ID_STR_RT, CURRENCY_CODE, ID_RU_PRDV)
                             REFERENCES RK_PRM_ITM;

-- New View Added
CREATE OR REPLACE VIEW ARM_ITM_HIST_NOW ( 
ID_ITM,
ID_STR_RT,
ID_ITM_HIST,
KEY, VALUE,
EFFECTIVE_DT,
EXPIRATION_DT
) 
AS
select   id_itm
       , id_str_rt
       , id_itm_hist
       , key
       , value
       , effective_dt
       , nvl(expiration_dt,sysdate) expiration_dt
from   arm_itm_hist  
where  sysdate between effective_dt and  nvl(expiration_dt,sysdate);

CREATE OR REPLACE VIEW RK_ITEM_VW
(ID_ITM, BARCODE, ID_STR_RT, RETAIL_VALUE, MARKDOWN_VALUE, 
 TAXABLE_VALUE, VAT_RATE, FY, SEASON, DE_SEASON, 
 ID_BRN, NM_BRN, LABEL, NM_LABEL, SUBLINE, 
 DE_SUBLINE, GENDER, DE_GENDER, CATEGORY, NM_CATEGORY, 
 ITEM_DROP, DE_DROP, VARIANT, ID_SIZE, DE_SIZE, 
 SIZE_INDEX, EXT_SIZE_INDEX, ID_SIZE_KIDS, DE_SIZE_KIDS, ID_SPR, 
 NM_SPR, MODEL, FABRIC, ID_COLOR, DE_COLOR, 
 PRODUCT_NUM, DE_PRODUCT, NM_ITM, ID_DPT_POS, NM_DPT_POS, 
 ID_CLASS, NM_CLASS, ID_SBCL, NM_SBCL, STYLE_NUM, 
 SC_ITM_SLS, CURRENCY_CODE, FL_EN_PRC_RQ, ID_RU_PRDV, UPDATE_DT)
AS 
SELECT
AS_ITM.ID_ITM			ID_ITM
, AS_ITM.BARCODE		BARCODE
, AS_ITM_RTL_STR.ID_STR_RT	ID_STR_RT
, HISTORY_TABLE_RETAIL.VALUE	RETAIL_VALUE
, HISTORY_TABLE_MARKDOWN.VALUE	MARKDOWN_VALUE
, HISTORY_TABLE_TAXABLE.VALUE	TAXABLE_VALUE
, HISTORY_TABLE_VAT.VALUE	VAT_RATE
, AS_ITM.FY			FY
, ARM_SEASON.ID_SEASON		SEASON
, ARM_SEASON.DE_SEASON		DE_SEASON
, ARM_BRN.ID_BRN		ID_BRN
, ARM_BRN.NM_BRN		NM_BRN
, ARM_LABEL.ID_LABEL		LABEL
, ARM_LABEL.NM_LABEL		NM_LABEL
, ARM_SUBLINE.ID_SUBLINE	SUBLINE
, ARM_SUBLINE.DE_SUBLINE	DE_SUBLINE
, ARM_GENDER.ID_GENDER		GENDER
, ARM_GENDER.DE_GENDER		DE_GENDER
, ARM_CATEGORY.ID_CATEGORY	CATEGORY
, ARM_CATEGORY.NM_CATEGORY	NM_CATEGORY
, ARM_DROP.ID_DROP		ITEM_DROP
, ARM_DROP.DE_DROP		DE_DROP
, AS_ITM.VARIANT		VARIANT
, ARM_SIZE.ID_SIZE		ID_SIZE
, ARM_SIZE.DE_SIZE		DE_SIZE
, ARM_SIZE.SIZE_INDEX		SIZE_INDEX
, ARM_SIZE.EXT_SIZE_INDEX	EXT_SIZE_INDEX
, ARM_KIDS_SIZE.ID_SIZE		ID_SIZE_KIDS
, ARM_KIDS_SIZE.DE_SIZE		DE_SIZE_KIDS
, ARM_SPR.ID_SPR		ID_SPR
, ARM_SPR.NM_SPR		NM_SPR
, AS_ITM.MODEL			MODEL
, AS_ITM.FABRIC			FABRIC
, ARM_COLOR.ID_COLOR		ID_COLOR
, ARM_COLOR.DE_COLOR		DE_COLOR
, ARM_PRODUCT.ID_PRODUCT	PRODUCT_NUM
, ARM_PRODUCT.DE_PRODUCT	DE_PRODUCT
, AS_ITM.NM_ITM			NM_ITM
, ID_DPT_PS.ID_DPT_POS		ID_DPT_POS
, ID_DPT_PS.NM_DPT_POS		NM_DPT_POS
, ARM_CLASS.ID_CLSS		ID_CLASS
, ARM_CLASS.NM_CLSS		NM_CLASS
, ARM_SUBCLASS.ID_SBCL		ID_SBCL
, ARM_SUBCLASS.NM_SBCL		NM_SBCL
, AS_ITM.STYLE_NUM		STYLE_NUM
, HISTORY_TABLE_STATUS.VALUE	SC_ITM_SLS
, AS_ITM_RTL_STR.currency_code Currency_code
, HISTORY_TABLE_MANUAL_PRICE.VALUE	FL_EN_PRC_RQ
, RK_PRM_ITM.ID_RU_PRDV		ID_RU_PRDV
, AS_ITM_RTL_STR.UPDATE_DT	UPDATE_DT
FROM
AS_ITM INNER JOIN
(
	AS_ITM_RTL_STR INNER JOIN PA_PRTY ON AS_ITM_RTL_STR.ID_STR_RT =
PA_PRTY.ID_PRTY
	LEFT OUTER JOIN RK_PRM_ITM ON (AS_ITM_RTL_STR.ID_ITM=RK_PRM_ITM.ID_ITM AND
	AS_ITM_RTL_STR.ID_STR_RT=RK_PRM_ITM.ID_STR_RT)
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_RETAIL ON
	(HISTORY_TABLE_RETAIL.ID_ITM=AS_ITM_RTL_STR.ID_ITM
	AND HISTORY_TABLE_RETAIL.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND
	HISTORY_TABLE_RETAIL.KEY='RETAIL_PRICE' )
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_MARKDOWN ON
	(HISTORY_TABLE_MARKDOWN.ID_ITM=AS_ITM_RTL_STR.ID_ITM
	AND HISTORY_TABLE_MARKDOWN.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND
	HISTORY_TABLE_MARKDOWN.KEY='MARKDOWN' )
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_TAXABLE ON
	(HISTORY_TABLE_TAXABLE.ID_ITM=AS_ITM_RTL_STR.ID_ITM
	AND HISTORY_TABLE_TAXABLE.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND
	HISTORY_TABLE_TAXABLE.KEY='TAXABLE' )
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_STATUS ON
	(HISTORY_TABLE_STATUS.ID_ITM=AS_ITM_RTL_STR.ID_ITM
	AND HISTORY_TABLE_STATUS.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND
	HISTORY_TABLE_STATUS.KEY='STATUS' )
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_VAT ON
	(HISTORY_TABLE_VAT.ID_ITM=AS_ITM_RTL_STR.ID_ITM
	AND HISTORY_TABLE_VAT.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND
	HISTORY_TABLE_VAT.KEY='VAT_RATE')
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_MANUAL_PRICE ON
	(HISTORY_TABLE_MANUAL_PRICE.ID_ITM=AS_ITM_RTL_STR.ID_ITM
	AND HISTORY_TABLE_MANUAL_PRICE.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND
	HISTORY_TABLE_MANUAL_PRICE.KEY='MANUAL_PRICE_ENTRY')
)
ON AS_ITM.ID_ITM = AS_ITM_RTL_STR.ID_ITM
LEFT OUTER JOIN ARM_BRN ON (AS_ITM.ID_BRN=ARM_BRN.ID_BRN AND
PA_PRTY.ED_LA=ARM_BRN.ED_LA AND PA_PRTY.ED_CO=ARM_BRN.ED_CO)
LEFT OUTER JOIN ID_DPT_PS ON (AS_ITM.ID_DPT_POS= ID_DPT_PS.ID_DPT_POS)
LEFT OUTER JOIN ARM_CLASS ON (AS_ITM.ID_CLSS=ARM_CLASS.ID_CLSS AND
AS_ITM.ID_DPT_POS= ARM_CLASS.ID_DPT)
LEFT OUTER JOIN ARM_SUBCLASS ON (AS_ITM.ID_DPT_POS=ARM_SUBCLASS.ID_DPT AND
AS_ITM.ID_CLSS=ARM_SUBCLASS.ID_CLSS AND AS_ITM.ID_SBCL=ARM_SUBCLASS.ID_SBCL)
LEFT OUTER JOIN ARM_SEASON ON (AS_ITM.ID_SEASON=ARM_SEASON.ID_SEASON AND
PA_PRTY.ED_LA=ARM_BRN.ED_LA AND PA_PRTY.ED_CO=ARM_SEASON.ED_CO)
LEFT OUTER JOIN ARM_COLOR ON (AS_ITM.ID_COLOR=ARM_COLOR.ID_COLOR)
LEFT OUTER JOIN ARM_SIZE ON (AS_ITM.ID_SIZE=ARM_SIZE.ID_SIZE AND
PA_PRTY.ED_LA=ARM_SIZE.ED_LA AND PA_PRTY.ED_CO=ARM_SIZE.ED_CO)
LEFT OUTER JOIN ARM_KIDS_SIZE ON (AS_ITM.ID_SIZE=ARM_KIDS_SIZE.ID_SIZE AND
PA_PRTY.ED_LA=ARM_KIDS_SIZE.ED_LA AND PA_PRTY.ED_CO=ARM_KIDS_SIZE.ED_CO)
LEFT OUTER JOIN ARM_SUBLINE ON (AS_ITM.SUBLINE=ARM_SUBLINE.ID_SUBLINE AND
PA_PRTY.ED_LA=ARM_SUBLINE.ED_LA AND PA_PRTY.ED_CO=ARM_SUBLINE.ED_CO)
LEFT OUTER JOIN ARM_GENDER ON (AS_ITM.GENDER=ARM_GENDER.ID_GENDER AND
PA_PRTY.ED_LA=ARM_GENDER.ED_LA AND PA_PRTY.ED_CO=ARM_GENDER.ED_CO)
LEFT OUTER JOIN ARM_CATEGORY ON (AS_ITM.CATEGORY=ARM_CATEGORY.ID_CATEGORY
AND PA_PRTY.ED_LA=ARM_CATEGORY.ED_LA AND PA_PRTY.ED_CO=ARM_CATEGORY.ED_CO)
LEFT OUTER JOIN ARM_DROP ON (AS_ITM.ITEM_DROP=ARM_DROP.ID_DROP AND
PA_PRTY.ED_LA=ARM_DROP.ED_LA AND PA_PRTY.ED_CO=ARM_DROP.ED_CO)
LEFT OUTER JOIN ARM_PRODUCT ON (AS_ITM.PRODUCT_NUM=ARM_PRODUCT.ID_PRODUCT)
LEFT OUTER JOIN ARM_SPR ON (AS_ITM.ID_SPR=ARM_SPR.ID_SPR)
LEFT OUTER JOIN ARM_LABEL ON (AS_ITM.LABEL=ARM_LABEL.ID_LABEL AND
PA_PRTY.ED_LA=ARM_LABEL.ED_LA AND PA_PRTY.ED_CO=ARM_LABEL.ED_CO);
