CREATE TABLE ARM_ALTERN_LN_ITM_DTL 
( 
  AI_TRN		VARCHAR2(128)	NOT NULL,
  AI_LN_ITM		NUMBER		NOT NULL, 
  DET_SEQ_NUM		NUMBER (3)	NOT NULL,
  SEQ_NUM		NUMBER (3)	NOT NULL,
  ID_ALTERN		VARCHAR2 (128)	NOT NULL,
  TRY_DT		DATE,
  PROMISE_DT		DATE,
  FITTER_ID		VARCHAR2(128),
  TAILOR		VARCHAR2(128),
  TOTAL_PRICE		VARCHAR2(128),
  COMMENTS		VARCHAR2(150)
);

ALTER TABLE ARM_ALTERN_LN_ITM_DTL ADD  PRIMARY KEY ( AI_TRN, AI_LN_ITM, DET_SEQ_NUM, SEQ_NUM );

ALTER TABLE ARM_ALTERN_LN_ITM_DTL ADD FOREIGN KEY (AI_TRN, AI_LN_ITM, DET_SEQ_NUM) 
REFERENCES RK_POS_LN_ITM_DTL (AI_TRN, AI_LN_ITM, SEQUENCE_NUMBER);

CREATE TABLE ARM_ALTERN_DTL 
( 
  AI_TRN		VARCHAR2(128)	NOT NULL,
  AI_LN_ITM		NUMBER		NOT NULL, 
  DET_SEQ_NUM		NUMBER (3)	NOT NULL,
  ALTERN_SEQ_NUM	NUMBER(3)	NOT NULL,
  CD_ALTERN		VARCHAR2 (128)	NOT NULL,
  DESCRIPTION		VARCHAR2  (128),
  ESTIMATED_PRICE	VARCHAR2(128),
  ESTIMATED_TIME	DATE,
  ACTUAL_PRICE		VARCHAR2(128),
  ACTUAL_TIME		DATE  
);

ALTER TABLE ARM_ALTERN_DTL ADD PRIMARY KEY ( AI_TRN, AI_LN_ITM, DET_SEQ_NUM, ALTERN_SEQ_NUM, CD_ALTERN);

ALTER TABLE ARM_ALTERN_DTL ADD FOREIGN KEY (AI_TRN, AI_LN_ITM, DET_SEQ_NUM, ALTERN_SEQ_NUM) 
REFERENCES ARM_ALTERN_LN_ITM_DTL (AI_TRN, AI_LN_ITM, DET_SEQ_NUM, SEQ_NUM);

CREATE OR REPLACE VIEW RK_ITEM_VW ( ID_ITM, 
BARCODE, ID_STR_RT, RETAIL_VALUE, MARKDOWN_VALUE, 
TAXABLE_VALUE, VAT_RATE, FY, SEASON, 
DE_SEASON, ID_BRN, NM_BRN, LABEL, 
NM_LABEL, SUBLINE, DE_SUBLINE, GENDER, 
DE_GENDER, CATEGORY, NM_CATEGORY, ITEM_DROP, 
DE_DROP, VARIANT, ID_SIZE, DE_SIZE, 
SIZE_INDEX, EXT_SIZE_INDEX, ID_SIZE_KIDS, DE_SIZE_KIDS, 
ID_SPR, NM_SPR, MODEL, FABRIC, 
ID_COLOR, DE_COLOR, PRODUCT_NUM, DE_PRODUCT, 
NM_ITM, ID_DPT_POS, NM_DPT_POS, ID_CLASS, 
NM_CLASS, ID_SBCL, NM_SBCL, STYLE_NUM, 
SC_ITM_SLS, CURRENCY_CODE, FL_EN_PRC_RQ, ID_RU_PRDV, 
QU_AVAILABLE, QU_UNAVAILABLE, QU_STORE_AVAILABLE, QU_STORE_UNAVAILABLE, 
NM_ORGN, UPDATE_DT ) 
AS 
SELECT 
AS_ITM.ID_ITM			ID_ITM 
, AS_ITM.BARCODE		BARCODE 
, AS_ITM_RTL_STR.ID_STR_RT	ID_STR_RT 
, HISTORY_TABLE_RETAIL.VALUE	RETAIL_VALUE 
, HISTORY_TABLE_MARKDOWN.VALUE	MARKDOWN_VALUE 
, HISTORY_TABLE_TAXABLE.VALUE	TAXABLE_VALUE 
, HISTORY_TABLE_VAT.VALUE	VAT_RATE 
, AS_ITM.FY			FY 
, AS_ITM.ID_SEASON		SEASON 
, ARM_SEASON.DE_SEASON		DE_SEASON 
, AS_ITM.ID_BRN		ID_BRN 
, ARM_BRN.NM_BRN		NM_BRN 
, AS_ITM.LABEL		LABEL 
, ARM_LABEL.NM_LABEL		NM_LABEL 
, AS_ITM.SUBLINE	SUBLINE 
, ARM_SUBLINE.DE_SUBLINE	DE_SUBLINE 
, AS_ITM.GENDER		GENDER 
, ARM_GENDER.DE_GENDER		DE_GENDER 
, AS_ITM.CATEGORY	CATEGORY 
, ARM_CATEGORY.NM_CATEGORY	NM_CATEGORY 
, AS_ITM.ITEM_DROP		ITEM_DROP 
, ARM_DROP.DE_DROP		DE_DROP 
, AS_ITM.VARIANT		VARIANT 
, AS_ITM.ID_SIZE		ID_SIZE 
, ARM_SIZE.DE_SIZE		DE_SIZE 
, ARM_SIZE.SIZE_INDEX		SIZE_INDEX 
, ARM_SIZE.EXT_SIZE_INDEX	EXT_SIZE_INDEX 
, AS_ITM.ID_SIZE		ID_SIZE_KIDS 
, ARM_KIDS_SIZE.DE_SIZE		DE_SIZE_KIDS 
, AS_ITM.ID_SPR		ID_SPR 
, ARM_SPR.NM_SPR		NM_SPR 
, AS_ITM.MODEL			MODEL 
, AS_ITM.FABRIC			FABRIC 
, AS_ITM.ID_COLOR		ID_COLOR 
, ARM_COLOR.DE_COLOR		DE_COLOR 
, AS_ITM.PRODUCT_NUM	PRODUCT_NUM 
, ARM_PRODUCT.DE_PRODUCT	DE_PRODUCT 
, AS_ITM.NM_ITM			NM_ITM 
, AS_ITM.ID_DPT_POS		ID_DPT_POS 
, ID_DPT_PS.NM_DPT_POS		NM_DPT_POS 
, AS_ITM.ID_CLSS		ID_CLASS 
, ARM_CLASS.NM_CLSS		NM_CLASS 
, AS_ITM.ID_SBCL		ID_SBCL 
, ARM_SUBCLASS.NM_SBCL		NM_SBCL 
, AS_ITM.STYLE_NUM		STYLE_NUM 
, HISTORY_TABLE_STATUS.VALUE	SC_ITM_SLS 
, AS_ITM_RTL_STR.currency_code Currency_code 
, HISTORY_TABLE_MANUAL_PRICE.VALUE	FL_EN_PRC_RQ 
, RK_PRM_ITM.ID_RU_PRDV		ID_RU_PRDV 
,NVL(ARM_ITM_SOH.QU_AVAILABLE,0) QU_AVAILABLE 
, NVL(ARM_ITM_SOH.QU_UNAVAILABLE,0) QU_UNAVAILABLE 
, NVL(ARM_ITM_SOH.QU_STORE_AVAILABLE,0) QU_STORE_AVAILABLE 
, NVL(ARM_ITM_SOH.QU_STORE_UNAVAILABLE,0) QU_STORE_UNAVAILABLE 
,PA_ORGN.NM_ORGN NM_ORGN 
, AS_ITM_RTL_STR.UPDATE_DT	UPDATE_DT 
FROM 
AS_ITM INNER JOIN 
( 
	AS_ITM_RTL_STR INNER JOIN PA_PRTY ON AS_ITM_RTL_STR.ID_STR_RT = 
PA_PRTY.ID_PRTY 
	LEFT OUTER JOIN RK_PRM_ITM ON (AS_ITM_RTL_STR.ID_ITM=RK_PRM_ITM.ID_ITM AND 
	AS_ITM_RTL_STR.ID_STR_RT=RK_PRM_ITM.ID_STR_RT) 
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_RETAIL ON 
	(HISTORY_TABLE_RETAIL.ID_ITM=AS_ITM_RTL_STR.ID_ITM 
	AND HISTORY_TABLE_RETAIL.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND 
	HISTORY_TABLE_RETAIL.KEY='RETAIL_PRICE' ) 
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_MARKDOWN ON 
	(HISTORY_TABLE_MARKDOWN.ID_ITM=AS_ITM_RTL_STR.ID_ITM 
	AND HISTORY_TABLE_MARKDOWN.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND 
	HISTORY_TABLE_MARKDOWN.KEY='MARKDOWN' ) 
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_TAXABLE ON 
	(HISTORY_TABLE_TAXABLE.ID_ITM=AS_ITM_RTL_STR.ID_ITM 
	AND HISTORY_TABLE_TAXABLE.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND 
	HISTORY_TABLE_TAXABLE.KEY='TAXABLE' ) 
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_STATUS ON 
	(HISTORY_TABLE_STATUS.ID_ITM=AS_ITM_RTL_STR.ID_ITM 
	AND HISTORY_TABLE_STATUS.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND 
	HISTORY_TABLE_STATUS.KEY='STATUS' ) 
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_VAT ON 
	(HISTORY_TABLE_VAT.ID_ITM=AS_ITM_RTL_STR.ID_ITM 
	AND HISTORY_TABLE_VAT.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND 
	HISTORY_TABLE_VAT.KEY='VAT_RATE') 
	LEFT OUTER JOIN ARM_ITM_HIST_NOW HISTORY_TABLE_MANUAL_PRICE ON 
	(HISTORY_TABLE_MANUAL_PRICE.ID_ITM=AS_ITM_RTL_STR.ID_ITM 
	AND HISTORY_TABLE_MANUAL_PRICE.ID_STR_RT=AS_ITM_RTL_STR.ID_STR_RT AND 
	HISTORY_TABLE_MANUAL_PRICE.KEY='MANUAL_PRICE_ENTRY') 
) 
ON AS_ITM.ID_ITM = AS_ITM_RTL_STR.ID_ITM 
LEFT OUTER JOIN ARM_BRN ON (AS_ITM.ID_BRN=ARM_BRN.ID_BRN AND 
PA_PRTY.ED_LA=ARM_BRN.ED_LA AND PA_PRTY.ED_CO=ARM_BRN.ED_CO) 
LEFT OUTER JOIN ID_DPT_PS ON (AS_ITM.ID_DPT_POS= ID_DPT_PS.ID_DPT_POS) 
LEFT OUTER JOIN ARM_CLASS ON (AS_ITM.ID_CLSS=ARM_CLASS.ID_CLSS AND 
AS_ITM.ID_DPT_POS= ARM_CLASS.ID_DPT) 
LEFT OUTER JOIN ARM_SUBCLASS ON (AS_ITM.ID_DPT_POS=ARM_SUBCLASS.ID_DPT AND 
AS_ITM.ID_CLSS=ARM_SUBCLASS.ID_CLSS AND AS_ITM.ID_SBCL=ARM_SUBCLASS.ID_SBCL) 
LEFT OUTER JOIN ARM_SEASON ON (AS_ITM.ID_SEASON=ARM_SEASON.ID_SEASON AND 
PA_PRTY.ED_LA=ARM_BRN.ED_LA AND PA_PRTY.ED_CO=ARM_SEASON.ED_CO) 
LEFT OUTER JOIN ARM_COLOR ON (AS_ITM.ID_COLOR=ARM_COLOR.ID_COLOR) 
LEFT OUTER JOIN ARM_SIZE ON (AS_ITM.ID_SIZE=ARM_SIZE.ID_SIZE AND 
PA_PRTY.ED_LA=ARM_SIZE.ED_LA AND PA_PRTY.ED_CO=ARM_SIZE.ED_CO) 
LEFT OUTER JOIN ARM_KIDS_SIZE ON (AS_ITM.ID_SIZE=ARM_KIDS_SIZE.ID_SIZE AND 
PA_PRTY.ED_LA=ARM_KIDS_SIZE.ED_LA AND PA_PRTY.ED_CO=ARM_KIDS_SIZE.ED_CO) 
LEFT OUTER JOIN ARM_SUBLINE ON (AS_ITM.SUBLINE=ARM_SUBLINE.ID_SUBLINE AND 
PA_PRTY.ED_LA=ARM_SUBLINE.ED_LA AND PA_PRTY.ED_CO=ARM_SUBLINE.ED_CO) 
LEFT OUTER JOIN ARM_GENDER ON (AS_ITM.GENDER=ARM_GENDER.ID_GENDER AND 
PA_PRTY.ED_LA=ARM_GENDER.ED_LA AND PA_PRTY.ED_CO=ARM_GENDER.ED_CO) 
LEFT OUTER JOIN ARM_CATEGORY ON (AS_ITM.CATEGORY=ARM_CATEGORY.ID_CATEGORY 
AND PA_PRTY.ED_LA=ARM_CATEGORY.ED_LA AND PA_PRTY.ED_CO=ARM_CATEGORY.ED_CO) 
LEFT OUTER JOIN ARM_DROP ON (AS_ITM.ITEM_DROP=ARM_DROP.ID_DROP AND 
PA_PRTY.ED_LA=ARM_DROP.ED_LA AND PA_PRTY.ED_CO=ARM_DROP.ED_CO) 
LEFT OUTER JOIN ARM_PRODUCT ON (AS_ITM.PRODUCT_NUM=ARM_PRODUCT.ID_PRODUCT) 
LEFT OUTER JOIN ARM_SPR ON (AS_ITM.ID_SPR=ARM_SPR.ID_SPR) 
LEFT OUTER JOIN ARM_LABEL ON (AS_ITM.LABEL=ARM_LABEL.ID_LABEL AND 
PA_PRTY.ED_LA=ARM_LABEL.ED_LA AND PA_PRTY.ED_CO=ARM_LABEL.ED_CO) 
LEFT OUTER JOIN ARM_ITM_SOH ON (ARM_ITM_SOH.ITEM_ID = AS_ITM_RTL_STR.ID_ITM AND ARM_ITM_SOH.STORE_ID=AS_ITM_RTL_STR.ID_STR_RT) 
INNER JOIN PA_ORGN ON PA_ORGN.ID_PRTY_ORGN = AS_ITM_RTL_STR.ID_STR_RT;

ALTER TABLE DO_CF_GF ADD (
ID_CT VARCHAR2(128),
DC_EXPIRATION DATE
);

ALTER TABLE TR_LTM_GF_CF_TND ADD (
MANUAL_AUTH_CODE VARCHAR2(50),
FL_MANUAL CHAR(1)
);

ALTER TABLE RK_COLLECTION
ADD REDEEMABLE_CONTROL_ID VARCHAR2(50);

CREATE OR REPLACE VIEW V_ARM_TXN_HDR
(CUST_ID, TY_TRN, PAY_TRN_TYPE, ID_STR_RT, ID_OPR, 
 TS_TRN_PRC, TS_TRN_SBM, TY_GUI_TRN, PAY_TYPES, TOTAL_AMT, 
 AI_TRN, CONSULTANT_ID, REDUCTION_AMOUNT, NET_AMOUNT, DISCOUNT_TYPES, 
 ITEMS_IDS, REGISTER_ID, FN_PRS, LN_PRS, EXP_DT, 
 REF_ID, VOID_ID)
AS 
SELECT RK_PAY_TRN.CUST_ID, TR_TRN.TY_TRN, RK_PAY_TRN.TYPE_ID PAY_TRN_TYPE, TR_TRN.ID_STR_RT,
TR_TRN.ID_OPR, TR_TRN.TS_TRN_PRC, TR_TRN.TS_TRN_SBM,
TR_TRN.TY_GUI_TRN, RK_PAY_TRN.PAY_TYPES, RK_PAY_TRN.TOTAL_AMT,
RK_PAY_TRN.AI_TRN, TR_RTL.CONSULTANT_ID, TR_RTL.REDUCTION_AMOUNT,
TR_RTL.NET_AMOUNT, TR_RTL.DISCOUNT_TYPES, TR_RTL.ITEMS_IDS,
TR_RTL.REGISTER_ID, PA_PRS.FN_PRS, PA_PRS.LN_PRS,
ARM_POS_PRS.EXP_DT, ARM_POS_PRS.ID_PRESALE REF_ID, TR_TRN.ID_VOID
FROM TR_TRN INNER JOIN
(
RK_PAY_TRN INNER JOIN
(
TR_RTL INNER JOIN ARM_POS_PRS ON TR_RTL.AI_TRN=ARM_POS_PRS.AI_TRN
LEFT OUTER JOIN PA_PRS ON TR_RTL.CONSULTANT_ID=PA_PRS.ID_PRTY_PRS
INNER JOIN (SELECT AI_TRN, COUNT(*) FROM RK_POS_LN_ITM_DTL WHERE FL_PROCESSED IS NULL GROUP BY AI_TRN   HAVING COUNT(*) > 0) LN_ITM_DTL
ON TR_RTL.AI_TRN = LN_ITM_DTL.AI_TRN
)
ON RK_PAY_TRN.AI_TRN = TR_RTL.AI_TRN
)
ON TR_TRN.AI_TRN = RK_PAY_TRN.AI_TRN
UNION ALL
SELECT RK_PAY_TRN.CUST_ID, TR_TRN.TY_TRN, RK_PAY_TRN.TYPE_ID PAY_TRN_TYPE, TR_TRN.ID_STR_RT,
TR_TRN.ID_OPR, TR_TRN.TS_TRN_PRC, TR_TRN.TS_TRN_SBM,
TR_TRN.TY_GUI_TRN, RK_PAY_TRN.PAY_TYPES, RK_PAY_TRN.TOTAL_AMT,
RK_PAY_TRN.AI_TRN, TR_RTL.CONSULTANT_ID, TR_RTL.REDUCTION_AMOUNT,
TR_RTL.NET_AMOUNT, TR_RTL.DISCOUNT_TYPES, TR_RTL.ITEMS_IDS,
TR_RTL.REGISTER_ID, PA_PRS.FN_PRS, PA_PRS.LN_PRS,
ARM_POS_CSG.EXP_DT, ARM_POS_CSG.ID_CONSIGNMENT REF_ID, TR_TRN.ID_VOID
FROM TR_TRN INNER JOIN
(
RK_PAY_TRN INNER JOIN
(
TR_RTL INNER JOIN ARM_POS_CSG ON TR_RTL.AI_TRN=ARM_POS_CSG.AI_TRN
LEFT OUTER JOIN PA_PRS ON TR_RTL.CONSULTANT_ID=PA_PRS.ID_PRTY_PRS
INNER JOIN (SELECT AI_TRN, COUNT(*) FROM RK_POS_LN_ITM_DTL WHERE FL_PROCESSED IS NULL GROUP BY AI_TRN   HAVING COUNT(*) > 0) LN_ITM_DTL
ON TR_RTL.AI_TRN = LN_ITM_DTL.AI_TRN
)
ON RK_PAY_TRN.AI_TRN = TR_RTL.AI_TRN
)
ON TR_TRN.AI_TRN = RK_PAY_TRN.AI_TRN;

ALTER TABLE RK_PAY_SUM 
ADD MEDIA_COUNT NUMBER DEFAULT 0;

