INSERT INTO ARM_EOD_GROUP(CD_GROUP,DE_GROUP) VALUES('TND','EOD - Tender Details');
INSERT INTO ARM_EOD_GROUP(CD_GROUP,DE_GROUP) VALUES('TXN','EOD - Transaction Details');
INSERT INTO ARM_EOD_GROUP(CD_GROUP,DE_GROUP) VALUES('TAX','EOD - Tax Details');