INSERT INTO CO_CLS_TND ( LU_CLS_TND, DE_CLS_TND ) VALUES ('OUT_OF_AREA_CHECK', 'OUT_OF_AREA_CHECK'); 
INSERT INTO CO_CLS_TND ( LU_CLS_TND, DE_CLS_TND ) VALUES ('LOCAL_CHECK', 'LOCAL_CHECK'); 
INSERT INTO CO_CLS_TND ( LU_CLS_TND, DE_CLS_TND ) VALUES ('ROUND_PAYMENT', 'ROUND_PAYMENT'); 
INSERT INTO CO_CLS_TND ( LU_CLS_TND, DE_CLS_TND ) VALUES ('MONETA', 'MONETA'); 

INSERT INTO RK_POS_LN_ITM_TYP (ID, DESCRIPTION) values (6, 'RESERVATION');
INSERT INTO RK_POS_LN_ITM_TYP (ID, DESCRIPTION) values (7, 'VOID');
INSERT INTO RK_POS_LN_ITM_TYP (ID, DESCRIPTION) values (8, 'NOSALE');

INSERT INTO CO_TYP_TRN ( TY_TRN, ID_RS ) VALUES ('TRNRSV', '171'); 
INSERT INTO CO_TYP_TRN ( TY_TRN, ID_RS ) VALUES ('TRNNFS', '172'); 

