insert into CO_CLS_GF_CF(TY_GF_CF, ID_STR_RT, ID_ACNT_LDG, DE_TYP_GF_CF, NM_AF_BSN_GF_CF, QU_DY_RDM_PRD, ID_FRM_GF_CF, DP_BLNC_UNSP_GF_CF)
values('REWARD_CARD', null, null, 'REWARD_CARD', null, 0, null, null);

insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1011', 'CASHIER');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1012', 'TECHNICAL SUPPORT');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1013', 'NON STORE ASSOCIATE');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1014', 'TAILOR');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1015', 'FITTER');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1001', 'MANAGER LEVEL 1');
insert into ST_JOB(CD_JOB, DE_JOB) VALUES ('1004', 'SALES LEVEL 1');

