INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','HOME','US','en','Home',0);

INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','SECR','US','en','Secondary Home',1);

INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','WORK','US','en','Work',2);

INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','VACA','US','en','Vaccation Home',3);

INSERT INTO ARM_CFG_DETAIL VALUES('ADDRESS_TYPE','DORM','US','en','Dorm',4);


INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','1','US','en','Home',2);

INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','2','US','en','Cellular',1);

INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','3','US','en','Office',3);

INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','4','US','en','Alternate',4);

INSERT INTO ARM_CFG_DETAIL VALUES('PHONE_TYPE','5','US','en','Fax',5);


INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','1','US','en',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','2','US','en','Preferred',1);

INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','3','US','en','Premio',2);

INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','4','US','en','VIP',3);

INSERT INTO ARM_CFG_DETAIL VALUES('CUSTOMER_TYPE','5','US','en','Employee',4);


INSERT INTO ARM_CFG_DETAIL VALUES('GENDER','1','US','en',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('GENDER','2','US','en','Male',1);

INSERT INTO ARM_CFG_DETAIL VALUES('GENDER','3','US','en','Female',2);


INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','1','US','en',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','2','US','en','Executive',1);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','3','US','en','Finance',2);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','4','US','en','Media/Publishing',3);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','5','US','en','Healthcare',4);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','6','US','en','Sales',5);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','7','US','en','Technology/IT',6);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','8','US','en','Education',7);

INSERT INTO ARM_CFG_DETAIL VALUES('PROFESSION','9','US','en','Other',8);


INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','1','US','en',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','2','US','en','Graduate',1);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','3','US','en','College',2);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','4','US','en','Some College',3);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','5','US','en','High School',4);

INSERT INTO ARM_CFG_DETAIL VALUES('EDUCATION','6','US','en','Other',5);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','1','US','en',' ',0);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','2','US','en','Birthday',1);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','3','US','en','Anniversary',2);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','4','US','en','Baby Arrival',3);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','5','US','en','Religious Event',4);

INSERT INTO ARM_CFG_DETAIL VALUES('SPECIAL_EVT_TYPE','6','US','en','Other',4);


INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','0','US','en','Austria',0);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','1','US','en','Belgium',1);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','2','US','en','Cyprus',2);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','3','US','en','Czech Republic',3);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','4','US','en','Denmark',4);

INSERT INTO ARM_CFG_DETAIL VALUES('COUNTRY','5','US','en','Others',5);