INSERT INTO ARM_CFG_DETAIL VALUES('POST_VOID_REASON_CD','1','US','en','Wrong Tender',0);

INSERT INTO ARM_CFG_DETAIL VALUES('POST_VOID_REASON_CD','2','US','en','Customer Changed Mind',1);

INSERT INTO ARM_CFG_DETAIL VALUES('POST_VOID_REASON_CD','3','US','en','Entry Error',2);


INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','01','US','en','PUBLIC RELATIONS',0);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','02','US','en','PROMOTION',1);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','03','US','en','PREMIO',2);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','04','US','en','VIP',3);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','05','US','en','OTHER',4);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','06','US','en','EMPLOYEE DISCOUNT',5);

INSERT INTO ARM_CFG_DETAIL VALUES('DISCOUNT_CD','07','US','en','FRIENDS AND FAMILY',6);


INSERT INTO ARM_CFG_DETAIL VALUES('NO_SL_REASON_CD','1','US','en','Customer Change',1);

INSERT INTO ARM_CFG_DETAIL VALUES('NO_SL_REASON_CD','2','US','en','Cash Pick-Up',2);

INSERT INTO ARM_CFG_DETAIL VALUES('NO_SL_REASON_CD','3','US','en','LP Audit',3);


INSERT INTO ARM_CFG_DETAIL VALUES('PRICE_OVERRIDE_REASON_CD','1','US','en','Wrong Marked Price',1);

INSERT INTO ARM_CFG_DETAIL VALUES('PRICE_OVERRIDE_REASON_CD','2','US','en','Sale',2);

INSERT INTO ARM_CFG_DETAIL VALUES('PRICE_OVERRIDE_REASON_CD','3','US','en','Other',3);